src/alias/AliasList.java, src/alias/PatchGroupAlias.java, src/module/decode/p25/P25DecoderState.java
enhances patch group alias to include any existing alias for the patch talkgroup ID in the rolled-up alias.  Streaming channels for the alias now includes any channels designated for the existing alias as well as the highest audio priority.  Alias name for the patch group alias is either the existing alias name, or the label "Patch:" and the patch group ID.
=> #100 patch group alias enhancement

src/dsp/filter/design/FilterViewer.java, src/module/decode/DecoderFactory.java, src/module/decode/mpt1327/MPT1327Decoder.java
Converts the post-demodulation filter from a band pass filter to a low-pass filter with 60 dB attenuation and a cutoff of 3200 Hz.  This is then followed by a high-pass filter at the decimated channel rate, internal to the decoder that performs DC removal and removes any CTCSS tones prior to the FSK decoder.
=> #130 MPT-1327 Decoder Filter issue resolved.  

src/playlist/PlaylistManager.java
Resolves #112 issue with loading/discovering playlist V2 filename from the system properties.  V2 playlist name is now hard-coded until a future enhancement that supports multiple user playlists.
=> Resolves #112 issue with loading/discovering playlist V2 filename

src/audio/broadcast/icecast/IcecastBroadcastMetadataUpdater.java
mountpoint was not URL encoded.
Thanks to mcode for the patch!
=> Resolves #140 issue with updating metadata on Icecast2 servers

src/audio/broadcast/AudioBroadcaster.java, src/audio/broadcast/BroadcastConfiguration.java, src/audio/broadcast/BroadcastEvent.java, src/audio/broadcast/BroadcastModel.java, src/audio/broadcast/broadcastify/BroadcastifyConfigurationEditor.java, src/audio/broadcast/icecast/IcecastHTTPConfigurationEditor.java, src/audio/broadcast/icecast/IcecastTCPConfigurationEditor.java, src/audio/broadcast/shoutcast/v1/ShoutcastV1ConfigurationEditor.java, src/audio/broadcast/shoutcast/v2/ShoutcastV2ConfigurationEditor.java
Calls that sit in the streaming queue for too long will be aged off if their start time exceeds the delay time plus maximum recording age limit.  A new column is added to the streaming status table to reflect the number of calls that have been aged off.  This would be an indicator to the user that they have too many talkgroups tagged to stream for a given channel and may want to change their settings to avoid age off.  This mainly prevents excessive streaming queue build-up that might never get streamed and could potentially impact application memory usage.
=> Resolves #111 - adds 'Maximum Age Limit' setting to streaming queues

src/source/tuner/usb/USBTransferProcessor.java
Adds to the previous commit by adding handler for clearing an endpoint halt when there is a USB pipe error while resubmitting a buffer transfer.
=> Resolves #155 - adds usb endpoint clear halt when attempting to resubmit transfer buffer

src/source/tuner/rtl/RTL2832TunerController.java, src/source/tuner/rtl/e4k/E4KTunerController.java, src/source/tuner/usb/USBTransferProcessor.java
Resolves null pointer error in E4000 tuner and tweaks settings in the USB transfer processor to improve latency in IQ buffer handling.
=> Resolves #161 - E4000 tuner error.  

src/audio/AudioPanel.java
Adds a screen reader accessible label to the mute button. Label switches between mute and unmute to match the action that will be taken when the button is next pressed.
=> Add a Text Label to the Mute Image Button

src/audio/broadcast/icecast/IcecastBroadcastMetadataUpdater.java
Resolves #165 issue where P25 Patch Group management was causing a logic error and causing the decoder's dispatcher thread to die.
=> 165 - P25 Channel stops decoding

src/alias/id/broadcast/BroadcastChannel.java, src/audio/broadcast/BroadcastModel.java, src/audio/broadcast/icecast/IcecastTCPAudioBroadcaster.java, src/record/AudioRecorder.java
A) streaming connection errors - detects errors and if currently connected, resets the connection.
B)duplicate calls being streamed - issue with comparison of broadcast channels allowed the same broadcast channel to be queued two or more times for the list of channels to stream a recording.
=> Resolves #176 - resolves 2 streaming related issues

src/audio/broadcast/shoutcast/v2/ShoutcastV2AudioBroadcaster.java, src/audio/broadcast/shoutcast/v2/ultravox/UltravoxMetadata.java
Resolves #189 - add UTF-8 encoding to shoutcast v2 (ultravox) XML metadata update values.
=> Resolves #189 - add UTF-8 encoding to shoutcast v2 

src/audio/broadcast/shoutcast/v2/ultravox/UltravoxMetadata.java
Resolves #199 issue where metadata is UTF-8 URL encoded versus UTF-8 String encoding.
=> Resolves issue with UTF-8 encoding of Shoutcast 2 metadata updates.

src/record/RecorderManager.java, src/record/wave/RealBufferWaveRecorder.java, src/record/wave/WaveWriter.java
Resolves issue #198 for periodic instances of audio recorders not being shutdown correctly.  Adds recorder monitor as a fail-safe to automatically shutdown recorders that don't receive an end-call indication.
=> Resolves issue audio recorders left open

src/channel/state/ChannelState.java, src/controller/channel/Channel.java, src/controller/channel/ChannelProcessingManager.java, src/dsp/filter/cic/ComplexPrimeCICDecimate.java, src/instrument/InstrumentableProcessingChain.java, src/module/ProcessingChain.java, src/module/decode/p25/C4FMSymbolFilter.java, src/module/decode/p25/P25Decoder.java, src/module/decode/p25/P25MessageFramer.java, src/module/decode/p25/P25_C4FMDecoder.java, src/module/decode/p25/P25_LSMDecoder.java, src/sample/Broadcaster.java, src/source/Source.java, src/source/mixer/RealMixerSource.java, src/source/tuner/TunerChannelSource.java, src/source/tuner/frequency/IFrequencyChangeProvider.java, src/source/wave/ComplexWaveSource.java, src/source/wave/RealWaveSource.java, src/spectrum/OverlayPanel.java, src/spectrum/SpectrumPanel.java
Resolves #222 frequency change event handling in the processing chain and updates spectral display to better show frequency correction values and the PPM correction that needs to be applied to the source tuner to compensate for the error ... when the error is not in the transmitted signal itself.
=> Frequency change event handling in the processing chain

src/channel/traffic/TrafficChannelManager.java, src/module/decode/DecoderFactory.java
Resolves #228 - traffic channel manager now allocates traffic channels even when the alias is marked as do not monitor
=> Traffic channel manager now allocates traffic channels for do not monitor aliases

src/audio/AudioChannelPanel.java, src/audio/AudioChannelsPanel.java
Resolves #234 - adjusts layout manager to allow jlabel text truncation.
=> Long alias names cause audio label to wrap

src/module/ProcessingChain.java
Resolves #245 where a NPE is thrown for frequency change event listener when using a sound card/mixer as a signal source.
Sound card sources do not expose a frequency change event listener to allow the signal source to be fine tuned ... feature is only exposed by tuners.
=> Using sound card or mixer as a source throws an error

src/module/decode/p25/P25DecoderState.java, src/module/decode/p25/audio/P25AudioModule.java, src/module/decode/p25/message/hdu/HDUMessage.java, src/module/decode/p25/message/ldu/LDU1Message.java, src/module/decode/p25/message/ldu/LDU2Message.java, src/module/decode/p25/message/ldu/LDUMessage.java
Resolves issue #244 - updates the P25 IMBE audio module to correctly detect encrypted audio state so that encrypted audio is not (incorrectly) decoded and played back to the user.  P25 audio decryption is not supported.
Processes HDU and LDU2 messages to identify encrypted call state.  Once established, all subsequent LDU1/2 messages are decoded only if the call is unencrypted.  If an LDU1 message is received out-of-sequence, meaning that the initial HDU message was missed, then the LDU1 is cached until we receive an LDU2 message and correctly determine the call encryption state.
=> 244 Prevent P25 Encrypted Audio Decoding/Playback

src/sample/OverflowableTransferQueue.java, src/source/tuner/usb/USBTransferProcessor.java
Resolves #252 issue where the tuner's buffer processor is logging that an overflow state has been cleared, caused by a clearing of the buffer when the tuner is being shutdown because there are no more channel consumers registered on the tuner.
Tweaked buffer size limits and buffer handling to attempt to avoid overflow situations in the first place.
Resolved an issue where the tuner processor was not deregistering correctly from the LIBUSB tuner processor during tuner shutdown.
=> 252 USB transfer processor erroneous logging and performance enhancements

src/channel/heartbeat/Heartbeat.java, src/channel/heartbeat/IHeartbeatListener.java, src/channel/heartbeat/IHeartbeatProvider.java, src/channel/state/ChannelState.java, src/module/ProcessingChain.java, src/module/decode/p25/P25DecoderState.java, src/source/Source.java, src/source/mixer/RealMixerSource.java, src/source/tuner/TunerChannelSource.java, src/source/wave/ComplexWaveSource.java, src/source/wave/RealWaveSource.java
Resolves #249 - removes the state monitor runnable from the channel state and replaces it with a processing chain heartbeat that is generated by the sample source.
Previously, the state monitor was running on a separate thread and this was causing multi-threading issues.  With this update, all channel state operations (and all module operations) occur on the source's buffer processing thread.
=> 249 Channel TEARDOWN/OVERFLOW state lockup

build/build.xml, scripts/run_sdrtrunk_linux.sh, scripts/run_sdrtrunk_windows.bat
Resolves #272.  Updates build script and windows/linux launch scripts to detect Java 8 or 9 version and respond accordingly.
The primary issue is with Java 9's refactoring the xml bind package to the java.se.ee package and tagging it as @deprecated in future versions.  The Java 9 build and launch scripts require using the --add-modules flag so that the compile and runtime dependencies are resolved.
=> 272 java 9 compatibility

src/source/tuner/TunerController.java
Resolves #276 Traffic Channel threads locking in overflow state.  Issue occured when the ChannelProcessionManager was allocating a new channel
causing the tuner to invoke the updateLOFrequency() method that was
trying to find a center tune frequency that would accommodate all of the
channels, specifically in the instance where the distance between the
highest channel and the middle channel was exactly one-half of the
tuner's bandwidth.  This situation would cause the calculated adjustment
to be zero and would cause an infinite loop, locking all channels from
accessing the any channel startup/teardown events and causing running
channels to block with buffer overflows. Added 1 to the adjustment to
ensure that the initial adjustment placed the center overlapping channel
fully to the left of …
=> 276 TrafficController Infinite Loop

src/source/tuner/TunerController.java
occured when the ChannelProcessionManager was allocating a new channel
causing the tuner to invoke the updateLOFrequency() method that was
trying to find a center tune frequency that would accommodate all of the
channels, specifically in the instance where the distance between the
highest channel and the middle channel was exactly one-half of the
tuner's bandwidth.  This situation would cause the calculated adjustment
to be zero and would cause an infinite loop, locking all channels from
accessing the any channel startup/teardown events and causing running
channels to block with buffer overflows. Added 1 to the adjustment to
ensure that the initial adjustment placed the center overlapping channel
fully to the left of the center DC spike so that on the next iteration
that channel would no …
=> Resolves #276 Traffic Channel threads locking in overflow state.  Issue

src/audio/broadcast/shoutcast/v2/ultravox/AuthenticateBroadcast.java
#289 resolves issue with encrypting username and password with XTEA algorithm using credential values longer than 8 characters/bytes.
=> 289 Shoutcast 2 Login Error

src/channel/traffic/TrafficChannelManager.java, src/module/decode/DecoderFactory.java, src/module/log/EventLogManager.java, src/module/log/EventLogger.java
#299 - adds support for traffic channel event logging of binary or decoded messages and event logging, as inherited from the parent control channel's configuration.
=> 299 Traffic Channel Event Logging

src/main/java/io/github/dsheirer/channel/metadata/Metadata.java, src/main/java/io/github/dsheirer/channel/state/AlwaysUnsquelchedDecoderState.java, src/main/java/io/github/dsheirer/record/RecorderManager.java, src/main/java/io/github/dsheirer/record/wave/AudioPacketWaveRecorder.java, src/main/java/io/github/dsheirer/record/wave/ComplexBufferWaveRecorder.java, src/main/java/io/github/dsheirer/record/wave/WaveMetadata.java, src/main/java/io/github/dsheirer/record/wave/WaveMetadataType.java, src/main/java/io/github/dsheirer/record/wave/WaveUtils.java, src/main/java/io/github/dsheirer/record/wave/WaveWriter.java
Updates the WAV audio recorders to append an INFO/LIST and ID3 metadata chunks to the end of the recording when the recorder.stop() is invoked.  Both LIST and ID3 chunks are included for greater compatibility with audio playback applications.
Several custom tags were created to capture all of the available metadata details.  The complete listing of LIST and ID3 tags are detailed in the WaveMetadataType enumeration.  See WaveMetadata.createFrom() method to view the matching between metadata tags and information elements.
=> 278 Add Metadata to WAV audio recordings

src/main/java/io/github/dsheirer/spectrum/DFTProcessor.java, src/main/java/io/github/dsheirer/spectrum/OverflowableBufferStream.java
Resolves #318.  Redesigns DFT processor to use a non-blocking queue approach to access incoming buffer streams coupled with an overflowable queue that limits the quantity of complex buffers that are cached for the DFT processor.
=> 318 DFT Processor Non-Blocking Queue redesign

src/main/java/io/github/dsheirer/channel/traffic/TrafficChannelManager.java, src/main/java/io/github/dsheirer/controller/channel/AutoStartChannelModel.java, src/main/java/io/github/dsheirer/controller/channel/Channel.java, src/main/java/io/github/dsheirer/controller/channel/ChannelAutoStartFrame.java, src/main/java/io/github/dsheirer/controller/channel/ChannelController.java, src/main/java/io/github/dsheirer/controller/channel/ChannelEditor.java, src/main/java/io/github/dsheirer/controller/channel/ChannelEvent.java, src/main/java/io/github/dsheirer/controller/channel/ChannelModel.java, src/main/java/io/github/dsheirer/controller/channel/ChannelProcessingManager.java, src/main/java/io/github/dsheirer/controller/channel/ChannelUtils.java, src/main/java/io/github/dsheirer/controller/channel/NameConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/SDRTrunk.java, src/main/java/io/github/dsheirer/spectrum/ChannelSpectrumPanel.java, src/main/java/io/github/dsheirer/spectrum/OverlayPanel.java
Resolves #328 Channel Auto-Start capability.  
Adds auto-start and auto-start ordering to each channel configuration to provide the user with greater control over initial application startup configuration.
Adds new dialog window that displays on startup that allows the user to invoke/cancel auto-start, or simply allow the timer to expire whereby the channels will be auto-started.
Updates channel table model to include an auto-start column and relabels the 'Enabled' column to read 'Playing'.
Updates channel editor to change the 'Enable/Disable' button to read 'Start/Stop'.
Changes the 'enabled' property of the channel configuration to indicate the current 'processing' status - isProcessing().
Channel's XML configuration re-purposes the 'enabled' property to indicate auto-start and adds a …
=> 328 Channel Auto-Start capability

src/main/java/io/github/dsheirer/record/RecorderManager.java, src/main/java/io/github/dsheirer/record/wave/AudioPacketWaveRecorder.java, src/main/java/io/github/dsheirer/record/wave/WaveWriter.java
Resolves #336.  Updates audio recorder to use a *.tmp file extension while the file is open/in-use and change the file extension to *.wav when the recording is closed.
This change allows better monitoring of audio recording file creation/completion events.
=> 336 - Audio recording temporary file name

src/main/java/io/github/dsheirer/dsp/psk/InterpolatingSampleBuffer.java, src/main/java/io/github/dsheirer/module/decode/p25/P25_C4FMDecoder.java
Adds automatic gain control to P25 C4FM decoder to condition the samples prior to interpolation.
Resolves issue with using incorrect quadrature index when pulling a
sample from the interpolating buffer.
Resolves issue where the instrumented version of the interpolating
buffer was being constructed in the non-interpolated decoder component.
=> 344 Add AGC to P25 C4FM decoder

src/main/java/io/github/dsheirer/dsp/filter/channelizer/AbstractComplexPolyphaseChannelizer.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/ChannelCalculator.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/ComplexPolyphaseChannelizerM2.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelManager.java, src/main/java/io/github/dsheirer/gui/control/JFrequencyControl.java, src/main/java/io/github/dsheirer/source/tuner/Tuner.java, src/main/java/io/github/dsheirer/source/tuner/TunerEvent.java, src/main/java/io/github/dsheirer/source/tuner/TunerModel.java, src/main/java/io/github/dsheirer/source/tuner/TunerViewPanel.java, src/main/java/io/github/dsheirer/source/tuner/airspy/AirspyTunerController.java, src/main/java/io/github/dsheirer/source/tuner/airspy/AirspyTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/configuration/TunerConfigurationEditor.java, src/main/java/io/github/dsheirer/source/tuner/fcd/proV1/FCD1TunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/fcd/proplusV2/FCD2TunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/frequency/FrequencyController.java, src/main/java/io/github/dsheirer/source/tuner/hackrf/HackRFTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/rtl/e4k/E4KTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/rtl/r820t/R820TTunerEditor.java
Resolves #170 adding support for Airspy Mini tuner's 3 and 6 MHz sample rates.
Resolves issue in PolyphaseChannelManager responding to sample rate
changes in the tuner.  The manager now recreates the channelizer when
needed if the tuner's sample rate has changed since the last time the
channelizer was used.
Updates the Tuner selection view to reflect tuner lock state.  Updates
the tuner editors to enable/disable frequency controller and sample
rate controls according to the tuner's lock state.
=> #170 Add Support for Airspy Mini tuner's 3 and 6 MHz

src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelManager.java, src/main/java/io/github/dsheirer/dsp/psk/pll/CostasLoop.java, src/main/java/io/github/dsheirer/module/decode/p25/P25DecoderC4FM.java, src/main/java/io/github/dsheirer/module/decode/p25/P25DecoderLSM.java, src/main/java/io/github/dsheirer/source/tuner/frequency/FrequencyController.java
Resolves #364.
The C4FM and LSM decoders were issuing a PLL reset with each new
channel that was allocated, causing any existing decoding channels to
be disrupted until PLL lock was re-achieved.  Decoding re-sync delays or 
inability to recapture the signal for decoding would likely result as the tuner's overall PPM caused misadjustment in the channel.
Resolved a NPE that was occurring in the FrequencyController for sample rate changes.
=> #364 Excessive P25 PLL Sync Lock Timelines

src/main/java/io/github/dsheirer/gui/SDRTrunk.java, src/main/java/io/github/dsheirer/source/tuner/TunerEvent.java, src/main/java/io/github/dsheirer/source/tuner/TunerModel.java, src/main/java/io/github/dsheirer/source/tuner/TunerSpectralDisplayManager.java, src/main/java/io/github/dsheirer/spectrum/ClearTunerMenuItem.java, src/main/java/io/github/dsheirer/spectrum/DFTProcessor.java, src/main/java/io/github/dsheirer/spectrum/OverlayPanel.java, src/main/java/io/github/dsheirer/spectrum/ShowTunerMenuItem.java, src/main/java/io/github/dsheirer/spectrum/SpectralDisplayPanel.java, src/main/java/io/github/dsheirer/spectrum/SpectrumFrame.java, src/main/java/io/github/dsheirer/spectrum/SpectrumPanel.java, src/main/java/io/github/dsheirer/spectrum/WaterfallPanel.java
Resolves #96
Adds capability to disable spectral display.
Adds right-click context
menu items to disable display and/or reenable display by selecting
another tuner.
Adds view menu items to disable spectral display or show a tuner.
Persists spectral display enabled state across application run sessions.
=> #96 Disable Spectral Display Option

src/main/java/io/github/dsheirer/source/tuner/TunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/TunerViewPanel.java, src/main/java/io/github/dsheirer/source/tuner/airspy/AirspyTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/configuration/TunerConfigurationEditor.java, src/main/java/io/github/dsheirer/source/tuner/fcd/proV1/FCD1TunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/fcd/proplusV2/FCD2TunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/hackrf/HackRFTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/rtl/e4k/E4KTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/rtl/r820t/R820TTunerEditor.java
Resolves an issue with the previous implementation where the tuner
editor was being refreshed repeatedly to update the lock state for the
tuner, rendering the editor almost completely unusable.
Now updates only the frequency control and the sample rate control to
reflect the tuner's lock state.
=> Resolved #370 Tuner Editor Lock State

src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelManager.java
Updates polyphase channel manager to correctly calculate the number of channels for each sample rate change.
Resolves #374
=> 374 RTL Tuner Sample Rates Not Supported (1.44 & 2.88 MHz)

src/main/java/io/github/dsheirer/source/tuner/rtl/RTL2832TunerController.java, src/main/java/io/github/dsheirer/source/tuner/rtl/e4k/E4KTunerController.java, src/main/java/io/github/dsheirer/source/tuner/usb/USBTransferProcessor.java
Resolves #381.  Updates USB transfer processor to use native transfer
buffer sizes that adapt to the selected sample rate.
This was previously causing choppy buffer processing (and choppy audio output) when the RTL tuner was running at sample rates below 300 kHz.
=> 381 Adaptive USB Transfer Buffer Sizes for RTL2832 Tuners

src/main/java/io/github/dsheirer/source/tuner/rtl/RTL2832TunerController.java
Resolves #382 - Adds additional sample rate options for the RTL2832 tuner and adjusts the low sample rate buffer size down to 16 kb.
=> 382 - Additional Sample Rate Options for RTL2832 Tuners

src/main/java/io/github/dsheirer/audio/broadcast/AudioBroadcaster.java, src/main/java/io/github/dsheirer/audio/broadcast/BroadcastState.java, src/main/java/io/github/dsheirer/audio/broadcast/BroadcastStatusPanel.java, src/main/java/io/github/dsheirer/audio/broadcast/icecast/IcecastBroadcastMetadataUpdater.java, src/main/java/io/github/dsheirer/audio/broadcast/icecast/IcecastTCPAudioBroadcaster.java
Resolves #372 - Icecast reconnect following network outage.  Updates
the lost connection timeout from default of 60 seconds down to 5 seconds
so that the connection state updates more quickly.  Removed complex
error handling and replaced with a simpler approach to catch an error
and disconnect and then attempt a reconnect.
Added new 'Network Unavailable' error state that detects when the network
connection is unavaialable.
Updated the icecast metadata updater to close the TCP session after
successfully writing metadata to the socket.
=> 372 Icecast Streaming Reconnect and Metadata Updates

src/main/java/io/github/dsheirer/channel/metadata/AttributeMonitor.java, src/main/java/io/github/dsheirer/channel/metadata/ChannelMetadataPanel.java, src/main/java/io/github/dsheirer/channel/state/ChannelState.java, src/main/java/io/github/dsheirer/channel/state/State.java, src/main/java/io/github/dsheirer/module/decode/p25/P25DecoderState.java
Adds 'ACTIVE' as a valid channel state to indicate that the channel is actively decoding, but no call or data is being transmitted.  This is primarily used for P25 channels when TDU Link Control messages are
being transmitted in between voice or data transmissions on a channel.
Updated several of the P25 decoder state message processing sections to keep the channel state UI updated with current call identifiers and states.
Hard-coded channel state colors to remove inefficiency in the way that channel state coloration was being handled.
=> 389 Add ACTIVE Channel State and Update P25 Decoder State processing

src/main/java/io/github/dsheirer/dsp/symbol/DibitToByteBufferAssembler.java, src/main/java/io/github/dsheirer/module/decode/DecoderFactory.java, src/main/java/io/github/dsheirer/module/decode/p25/P25Decoder.java, src/main/java/io/github/dsheirer/module/decode/p25/P25DecoderC4FM.java, src/main/java/io/github/dsheirer/module/decode/p25/P25DecoderC4FMInstrumented.java, src/main/java/io/github/dsheirer/module/decode/p25/P25DecoderLSM.java, src/main/java/io/github/dsheirer/module/decode/p25/P25DecoderLSMInstrumented.java, src/main/java/io/github/dsheirer/module/decode/p25/P25MessageFramer.java, src/main/java/io/github/dsheirer/module/decode/p25/P25MessageProcessor.java, src/main/java/io/github/dsheirer/record/binary/BinaryRecorder.java
Resolves #394 
Updates P25 decoder (C4FM and LSM) to output reusable byte buffers so that the demodulated bit stream can be recorded to a *.bits file.
Updates binary recorder for max recording size of 500 kB
=> 394 P25 bit stream output

src/main/java/io/github/dsheirer/dsp/filter/FilterFactory.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelManager.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/output/ChannelOutputProcessor.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/output/OneChannelOutputProcessor.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/output/TwoChannelOutputProcessor.java, src/main/java/io/github/dsheirer/dsp/filter/design/FilterViewer.java, src/main/java/io/github/dsheirer/gui/channelizer/SynthesizerViewer.java, src/main/java/io/github/dsheirer/sample/buffer/ReusableComplexBuffer.java, src/main/java/io/github/dsheirer/source/tuner/usb/USBTransferProcessor.java
Resolves issue where gain to compensate for channelization loss was being incorrectly applied to the channelizer filter versus applying the gain to the output channels was causing synthesized channels to have a dropout at the channel join.
Updated code to remove gain compensation from filter and apply gain at the channel output processor.
=> 375 channelizer synthesizer gain issue

src/main/java/io/github/dsheirer/dsp/filter/design/FilterViewer.java, src/main/java/io/github/dsheirer/dsp/psk/DQPSKDecisionDirectedSymbolEvaluator.java, src/main/java/io/github/dsheirer/dsp/psk/DQPSKGardnerSymbolEvaluator.java, src/main/java/io/github/dsheirer/gui/instrument/DemodulatorViewerFX.java, src/main/java/io/github/dsheirer/gui/instrument/RecentFilesMenu.java, src/main/java/io/github/dsheirer/gui/instrument/chart/DoubleLineChart.java, src/main/java/io/github/dsheirer/gui/instrument/chart/SamplesPerSymbolChart.java, src/main/java/io/github/dsheirer/gui/instrument/decoder/P25Phase1LSMPane.java, src/main/java/io/github/dsheirer/sample/buffer/ReusableComplexDelayBuffer.java, src/main/java/io/github/dsheirer/source/SourceEvent.java, src/main/java/io/github/dsheirer/source/mixer/ComplexMixer.java, src/main/java/io/github/dsheirer/source/mixer/MixerReader.java, src/main/java/io/github/dsheirer/source/tuner/TunerController.java, src/main/java/io/github/dsheirer/source/tuner/airspy/AirspyTunerController.java, src/main/java/io/github/dsheirer/source/tuner/channel/CICTunerChannelSource.java, src/main/java/io/github/dsheirer/source/tuner/fcd/FCDTunerController.java, src/main/java/io/github/dsheirer/source/tuner/hackrf/HackRFTunerController.java, src/main/java/io/github/dsheirer/source/tuner/manager/HeterodyneChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/rtl/RTL2832TunerController.java, src/main/java/io/github/dsheirer/source/tuner/test/TestTunerController.java, src/main/java/io/github/dsheirer/source/wave/ComplexWaveSource.java
Implements a complex sample delay buffer integrated into the tuner
channel manager so that channel source requests can have a start
timestamp specified and the channel can be preloaded with samples from
the delay buffer.  If no timestamp is specified, current time is assumed.
This feature requires corresponding updates to any decoder that wishes
to implement the timestamped sample preloading functionality.
=> 406 Tuner Sample Delay Buffer

src/main/java/io/github/dsheirer/controller/channel/ChannelProcessingManager.java, src/main/java/io/github/dsheirer/dsp/filter/cic/ComplexPrimeCICDecimate.java, src/main/java/io/github/dsheirer/dsp/filter/fir/FIRFilterSpecification.java, src/main/java/io/github/dsheirer/gui/channelizer/ChannelizerViewer.java, src/main/java/io/github/dsheirer/gui/channelizer/ChannelizerViewer2.java, src/main/java/io/github/dsheirer/module/decode/DecoderFactory.java, src/main/java/io/github/dsheirer/module/decode/DecoderType.java, src/main/java/io/github/dsheirer/source/SourceManager.java, src/main/java/io/github/dsheirer/source/tuner/TunerModel.java, src/main/java/io/github/dsheirer/source/tuner/channel/CICTunerChannelSource.java, src/main/java/io/github/dsheirer/source/tuner/channel/ChannelSpecification.java, src/main/java/io/github/dsheirer/source/tuner/manager/ChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/HeterodyneChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/PolyphaseChannelSourceManager.java
Resolves #411
Updates decoder types to specify channel sample rate and pass/stop
frequencies for requested channels.  Updates tuner channel source
managers to accept a channel specification for channels that are
allocated.
=> #411 Update Tuner Source Manager to provide variable sample rate channels

src/main/java/io/github/dsheirer/source/tuner/TunerManager.java, src/main/java/io/github/dsheirer/source/tuner/TunerModel.java, src/main/java/io/github/dsheirer/source/tuner/usb/USBMasterProcessor.java
Resolves #405
Adds 500 ms delay to initial registering for samples from all tuners to
feed the spectral display/waterfall.  The existing approach of immediately
registering for samples was causing the airspy tuner to lockup
aperiodically.  Investigation via debugger didn't show any application
thread locks ... usb master processor was continuing to service libusb
timeouts.  Unable to debug internal airspy processes.  Adding the delay
to startup seems to be a usable solution.
=> 405 Airspy Spectrum/Waterfall Freezes

src/main/java/io/github/dsheirer/source/tuner/channel/CICTunerChannelSource.java
Correctly implements the buffer overflow listener registration so that decoding channels can be notified when the internal buffer goes into and out of overflow state.
=> 415 Buffer Overflow State Listener Registration

src/main/java/io/github/dsheirer/source/tuner/TunerController.java, src/main/java/io/github/dsheirer/source/tuner/manager/CenterFrequencyCalculator.java, src/main/java/io/github/dsheirer/source/tuner/manager/HeterodyneChannelSourceManager.java
Resolves #419
Updates the heterodyne channelizer's center frequency calculator to only update the center frequency when needed and to place the set of decoding channels adjacent to the right side of the tuner's center
frequency when the complete set of channels fit into the usable half bandwidth of the tuner.
=> 419 Heterodyne Channelizer Center Frequency Calculations

src/main/java/io/github/dsheirer/channel/state/ChannelState.java, src/main/java/io/github/dsheirer/record/config/RecordConfiguration.java, src/main/java/io/github/dsheirer/record/wave/AudioPacketWaveRecorder.java, src/main/java/io/github/dsheirer/sample/OverflowableTransferQueue.java
Updated audio packet wave recorder to correctly dequeue audio packets
to ensure that the overflowable buffer queue accounting process was
working correctly.
Updated overflowable buffer queue's poll() method to correctly decrement
the queue size counter.
Resolved issue where the mutable metadata was being prematurely reset
and causing the end audio packet to be mis-identified.  This resulted
in the recording manager not stopping the recording on command with the
timeout mechanism kicking in after a brief delay.
=> Resolves #387 (P25) 10 second/10 minute audio recording time limit.

build.gradle
This PR resolves issue #442 Runtime error on Java 11.
=> Bumping Jide to 3.6.18 to fix Java 11 reflections error

build.gradle
This PR resolves issue #440 -Update java4usb library to 1.3 and libusb to 1.0.22
=> Bumping usb4java to 1.3.0

src/main/java/io/github/dsheirer/sample/buffer/AbstractReusableBuffer.java
Method doc for decrementUserCount reads that the method is thread-safe, but there exist no locking to ensure thread safety on call into recycle method. Modifying the decrementUserCount method to block other callers to ensure thread-safe access.
This appears to be a hot area of code and there may be a performance hit by doing this, please double check my work here.
=> Fix for issue #441 Audio Recording Stops After Encountering Error

src/main/java/io/github/dsheirer/dsp/filter/cic/ComplexPrimeCICDecimate.java, src/main/java/io/github/dsheirer/gui/SDRTrunk.java, src/main/java/io/github/dsheirer/gui/channelizer/ChannelizerViewer.java, src/main/java/io/github/dsheirer/gui/channelizer/ChannelizerViewer2.java, src/main/java/io/github/dsheirer/gui/preference/PreferenceEditorFactory.java, src/main/java/io/github/dsheirer/gui/preference/PreferenceEditorType.java, src/main/java/io/github/dsheirer/gui/preference/PreferencesEditor.java, src/main/java/io/github/dsheirer/gui/preference/TalkgroupFormatPreferenceEditor.java, src/main/java/io/github/dsheirer/gui/preference/tuner/TunerPreferenceEditor.java, src/main/java/io/github/dsheirer/module/decode/p25/P25DecoderState.java, src/main/java/io/github/dsheirer/module/decode/p25/message/lc/LinkControlWord.java, src/main/java/io/github/dsheirer/module/decode/p25/message/pdu/ambtc/osp/AMBTCGroupDataChannelGrant.java, src/main/java/io/github/dsheirer/module/decode/p25/message/tsbk/TSBKMessage.java, src/main/java/io/github/dsheirer/preference/UserPreferences.java, src/main/java/io/github/dsheirer/preference/tuner/ChannelizerType.java, src/main/java/io/github/dsheirer/preference/tuner/TunerPreference.java, src/main/java/io/github/dsheirer/source/SourceManager.java, src/main/java/io/github/dsheirer/source/tuner/Tuner.java, src/main/java/io/github/dsheirer/source/tuner/TunerManager.java, src/main/java/io/github/dsheirer/source/tuner/airspy/AirspyTuner.java, src/main/java/io/github/dsheirer/source/tuner/fcd/FCDTuner.java, src/main/java/io/github/dsheirer/source/tuner/hackrf/HackRFTuner.java, src/main/java/io/github/dsheirer/source/tuner/rtl/RTL2832Tuner.java, src/main/java/io/github/dsheirer/source/tuner/test/TestTuner.java
Resolves #431 
Adds tuner preference editor with channelizer type options.  
Updates tuners to use the preference to select either polyphase or heterodyne channelizers.
=> 431 Tuner Channelizer User Preference

src/main/java/io/github/dsheirer/controller/channel/ChannelAutoStartFrame.java
Resolves #433
Adds toFront() to channel auto start frame to force the window to the front
=> 433 Channel Auto Start Window To Front

src/main/java/io/github/dsheirer/alias/AliasList.java, src/main/java/io/github/dsheirer/alias/id/talkgroup/TalkgroupRange.java
Resolves #462
Updates alias list to support talkgroup range and patch groups.
Note: see also #463 which adds support for multiple aliases matching a patch group.
=> 462 AliasList Support For TalkgroupRange and PatchGroup

src/main/java/io/github/dsheirer/module/decode/DecoderFactory.java
Resolves #476 
Adds support for rotating control channels to MPT1327 decoder.
=> 476 Adds support to MPT1327 decoder for rotating control channels.

src/main/java/io/github/dsheirer/gui/preference/PreferenceEditorFactory.java, src/main/java/io/github/dsheirer/gui/preference/PreferenceEditorType.java, src/main/java/io/github/dsheirer/gui/preference/PreferencesEditor.java, src/main/java/io/github/dsheirer/gui/preference/decoder/JmbeLibraryPreferenceEditor.java, src/main/java/io/github/dsheirer/module/decode/DecoderFactory.java, src/main/java/io/github/dsheirer/module/decode/p25/audio/P25AudioModule.java, src/main/java/io/github/dsheirer/preference/PreferenceType.java, src/main/java/io/github/dsheirer/preference/UserPreferences.java, src/main/java/io/github/dsheirer/preference/decoder/JmbeLibraryPreference.java
Resolves #488
Adds a new JMBE Audio Library preference to the user preferences editor so that users can set the library path once and it will persist across application upgrades so that they do NOT have to copy the library to
their application install with each upgrade.
=> 488 JMBE Audio Library Location - User Preference

src/main/java/io/github/dsheirer/audio/AudioMetadataProcessor.java, src/main/java/io/github/dsheirer/audio/AudioModule.java, src/main/java/io/github/dsheirer/module/decode/DecoderFactory.java, src/main/java/io/github/dsheirer/module/decode/am/AMDecoderEditor.java, src/main/java/io/github/dsheirer/module/decode/am/DecodeConfigAM.java, src/main/java/io/github/dsheirer/module/decode/nbfm/DecodeConfigNBFM.java, src/main/java/io/github/dsheirer/module/decode/nbfm/NBFMDecoderEditor.java
Resolves #494
Adds support to AM and FM decoders to record all audio produced by the decoder.
This overcomes a limitation in the current approach of using aliases to designate when audio should be recorded.  The user can now select to record all AM/FM audio by checking a box in the Decoder tab of the channel configuration.
=> 494 AM/FM Decoder Audio Recording

build.gradle, src/main/java/io/github/dsheirer/audio/playback/AudioChannelPanel.java
Resolves #499 
Resolves issue where non-aliased talkgroup values were not displaying in the audio playback panels (left/right/mono).
Adds buildSdr build target back into gradle script that was previously removed for Java 11 upgrade.
=> 499 Audio Playback Talkgroup Display

build.gradle
Resolves #501
Updates beryx gradle plugin to resolve issue where launcher script did not like '&' ampersand in the execution path.
=> 501 Beryx Gradle Plugin - Launch Script 

src/main/java/io/github/dsheirer/preference/identifier/talkgroup/APCO25TalkgroupFormatter.java, src/main/java/io/github/dsheirer/preference/identifier/talkgroup/MDC1200TalkgroupFormatter.java, src/main/java/io/github/dsheirer/preference/identifier/talkgroup/PassportTalkgroupFormatter.java
Resolves issue with missing case statements in talkgroup format classes.
Resolves #504
=> 504 Talkgroup Format - Missing Case Statements

src/main/java/io/github/dsheirer/alias/AliasList.java, src/main/java/io/github/dsheirer/alias/id/talkgroup/TalkgroupRange.java
Adds logging/warning when alias list contains talkgroups or talkgroup range collisions or overlaps.
Resolves #507
=> 507 Detect and Log Talkgroup/Range Collisions or Overlaps

src/main/java/io/github/dsheirer/alias/AliasController.java
Resolves #510.
Updates alias controller so that when adding an alias to a filtered column view it doesn't throw an error.
=> 510 Add Alias to Filtered Column View

src/main/java/io/github/dsheirer/audio/playback/AudioChannelPanel.java, src/main/java/io/github/dsheirer/audio/playback/AudioChannelsPanel.java, src/main/java/io/github/dsheirer/audio/playback/AudioOutput.java, src/main/java/io/github/dsheirer/channel/state/ChannelState.java, src/main/java/io/github/dsheirer/identifier/IdentifierCollection.java, src/main/java/io/github/dsheirer/identifier/MutableIdentifierCollection.java
Resolves #519
- Clears stale patch groups
- Reworks the audio playback panel label update code to properly update
talkgroups and aliases in concert with the audio playback.
- Removes code that was truncating playback aliases at 32 characters.
=> 519 Stale Patch Groups and Audio Playback Display

build.gradle
Resolves #522
Resolves #501 
Updates build script to use latest beryx runtime zip plugin and adds validation to check for each of the platform-specific JDKs before executing the runtimeZip task.
=> 501/522 Platform-Specific Gradle Build Issues

build.gradle
Resolves #531 
Updates gradle build script to remove extra jfx runtimes
=> 531 Update Gradle Build to Remove Extra JavaFX Runtime Libraries

src/main/java/io/github/dsheirer/audio/broadcast/icecast/IcecastHTTPAudioBroadcaster.java
Updates Icecast HTTP (2.4) streaming client to perpetually attempt to
reconnect to the server, even if there are (temp) errors.
Resolves #535
=> 535 Icecast Http Reconnect After Errors

src/main/java/org/jdesktop/swingx/JXMapViewer.java, src/main/java/org/jdesktop/swingx/OSMTileFactoryInfo.java, src/main/java/org/jdesktop/swingx/mapviewer/AbstractTileFactory.java
Resolves #570 
Updates OSM to use HTTP connection and sets the User-Agent connection property so that OSM doesn't reject the connection with an HTTP 429 Too Many Requests error.
Updates the default loading placeholder image to use one of the font awesome icons.
=> 570 OpenStreetMap Tile Data Not Downloading

src/main/java/io/github/dsheirer/channel/state/DecoderStateEvent.java, src/main/java/io/github/dsheirer/channel/state/MultiChannelState.java, src/main/java/io/github/dsheirer/channel/state/SingleChannelState.java, src/main/java/io/github/dsheirer/source/tuner/channel/ChannelRotationMonitor.java
rotating channel frequency configurations failing to maintain lock
on the channel.
Converted the ChannelRotationMonitor from using identifier updates to
now using DecoderStateEvents so that the ChannelState can supply a
steady stream of channel state events to the monitor.
=> Resolves issue with the multi-frequency tuner source and P25/MPT1327

src/main/java/io/github/dsheirer/module/decode/p25/phase2/P25P2DecoderEditor.java
Resolves #610.  P25P2 Editor Doesn't accept scramble parameter values.
=> #610 P25P2 Config Editor Doesn't Accept Scramble Parameters

src/main/java/io/github/dsheirer/module/decode/DecoderType.java
Resolves #612 P25P2 bit recording filenames indicated incorrect protocol type.
=> #612 P25P2 Bitstream Recording Protocol Type Incorrect

build.gradle
Updates radio reference library to 15.1.2 to resolve issue with logback config collision.
Updates OS build names to better reflect processor types: x86_64 (64-bit) or x86_32 (32-bit)
=> #616 Update Build Version to 0.4.0 beta 2.

src/main/java/io/github/dsheirer/playlist/PlaylistManager.java, src/main/java/io/github/dsheirer/playlist/PlaylistUpdater.java
Resolves #628.  Adds P25 talkgroup alias identifier conversions to radio identifiers for any talkgroups or ranges that have values greater than 65,535.  Updates playlist version to 4.
=> #628 Playlist Auto-Conversion P25 Alias Talkgroups > 65535 to Radio Identifier

src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1NetworkConfigurationMonitor.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/tsbk/TSBKMessageFactory.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/P25P2NetworkConfigurationMonitor.java
Resolves #576 
-Updates P25 activity summaries to show network identifiers in both hex and decimal
-Resolves issue with displaying FCC station licence information
-Resolves issue with P25 explicit channel uplink frequency calculation
-Resolves issue with recording tuner error on loading a wideband recording.
=> 576 Update P25 Activity Summary To Provide Network Values in Hex and Decimal

src/main/java/io/github/dsheirer/module/decode/p25/identifier/channel/P25ExplicitChannel.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DecoderState.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1NetworkConfigurationMonitor.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/standard/LCRFSSStatusBroadcastExplicit.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/tsbk/Opcode.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/tsbk/TSBKMessageFactory.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/tsbk/motorola/osp/MotorolaTrafficChannel.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/P25P2NetworkConfigurationMonitor.java, src/main/java/io/github/dsheirer/source/tuner/manager/PassThroughSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/recording/RecordingTuner.java, src/main/java/io/github/dsheirer/source/tuner/recording/RecordingTunerController.java
#576 Updates P25 activity summaries to list values in hex and decimal.  Resolves issue with P25 explicit channel uplink frequency calculations.  Resolves issue with Motorola base station id messages and traffic channel messages.  Resolves issue with RFSS link control message control channel frequency calculations.  Resolves issue with error when using recording tuners.
=> #576 P25 Activity Summary Hex and Decimal Network Values

build.gradle
Resolves #630 
Updates gradle build to allow runtime image builds without locally installed JDKs.  Updates build version to 0.4.0 beta 3
=> #630 Gradle Build Without Locally Installed OS-Specific JDKs

build.gradle
Resolves #644 
NoClassDefFound error when Icecast metadata updater runs.  
Updates build to version 0.4.0 Beta 4
=> #644 Icecast Metadata Updater NoClassDefFound Error

src/main/java/io/github/dsheirer/controller/channel/ChannelProcessingManager.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelManager.java, src/main/java/io/github/dsheirer/gui/SDRTrunk.java, src/main/java/io/github/dsheirer/module/ProcessingChain.java, src/main/java/io/github/dsheirer/source/SourceEvent.java, src/main/java/io/github/dsheirer/source/tuner/ITunerErrorListener.java, src/main/java/io/github/dsheirer/source/tuner/Tuner.java, src/main/java/io/github/dsheirer/source/tuner/TunerController.java, src/main/java/io/github/dsheirer/source/tuner/TunerModel.java, src/main/java/io/github/dsheirer/source/tuner/TunerViewPanel.java, src/main/java/io/github/dsheirer/source/tuner/airspy/AirspyTunerController.java, src/main/java/io/github/dsheirer/source/tuner/channel/TunerChannelSource.java, src/main/java/io/github/dsheirer/source/tuner/hackrf/HackRFTunerController.java, src/main/java/io/github/dsheirer/source/tuner/manager/ChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/HeterodyneChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/PassThroughSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/PolyphaseChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/rtl/RTL2832TunerController.java, src/main/java/io/github/dsheirer/source/tuner/rtl/e4k/E4KTunerController.java, src/main/java/io/github/dsheirer/source/tuner/usb/USBMasterProcessor.java, src/main/java/io/github/dsheirer/source/tuner/usb/USBTransferProcessor.java
-Separates USB timeout event processing to a dedicated thread
-Updates USB transfer buffer processor to better detect errors and auto-restart on error (max 3 times)
-Updates Tuner to add an error state and SourceManager to not select tuners with an error state
-Updates ChannelProcessingManager to auto-shutdown channels sourced from tuners set with error state
-Improves logging of USB related errors.
=> #652 USB Tuner Error Handling Enhancements

src/main/java/io/github/dsheirer/source/tuner/Tuner.java, src/main/java/io/github/dsheirer/source/tuner/TunerManager.java, src/main/java/io/github/dsheirer/source/tuner/airspy/AirspyTuner.java, src/main/java/io/github/dsheirer/source/tuner/fcd/FCDTuner.java, src/main/java/io/github/dsheirer/source/tuner/hackrf/HackRFTuner.java, src/main/java/io/github/dsheirer/source/tuner/recording/RecordingTuner.java, src/main/java/io/github/dsheirer/source/tuner/rtl/RTL2832Tuner.java, src/main/java/io/github/dsheirer/source/tuner/test/TestTuner.java
Updates logging to track max usb speeds per bus and warns user when any USB bus combined tuner data rates exceeds 70% of the max bus rate.
=> #654 Warn users when USB bus speeds are exceeded.

src/main/java/io/github/dsheirer/audio/broadcast/AudioBroadcaster.java
#651 Updates audio broadcaster to decrement pending replay count so that pending recordings don't cause a memory leak when the streaming server is not available.
Closes #651
=> #651 Streaming Audio - Potential Memory Leak

build.gradle
Updates gradle build to use version-specific root folder names for OS-specific image products.
=> #649 Update Gradle Build - Image Root Folder Version Naming

src/main/java/io/github/dsheirer/audio/AudioSegment.java, src/main/java/io/github/dsheirer/audio/playback/AudioOutput.java, src/main/java/io/github/dsheirer/audio/playback/AudioPlaybackManager.java, src/main/java/io/github/dsheirer/controller/channel/ChannelProcessingManager.java, src/main/java/io/github/dsheirer/gui/preference/playback/PlaybackPreferenceEditor.java, src/main/java/io/github/dsheirer/preference/playback/PlaybackPreference.java
Resolves #680 Audio Do Not Monitor is not working.  
- Adds audio segment drop tone to indicate that an audio playback is dropped because the do not monitor setting was applied after the audio segment started.
- Resolves issue with audio playback panel gui occasionally showing stale talkgroup information
=> #680 Audio Playback - Do Not Monitor Not Working

src/main/java/io/github/dsheirer/source/tuner/hackrf/HackRFTunerController.java, src/main/java/io/github/dsheirer/source/tuner/hackrf/HackRFTunerEditor.java
Resolves #688.  Updates HackRF Sample Rate options and sets usable bandwidth for the tuner to 75% of the sample rate.
=> #688 HackRF Sample Rates

src/main/java/io/github/dsheirer/module/decode/mpt1327/MPT1327DecoderState.java
Resolves #709 
Updates decoder state to broadcast call start event on channel start for traffic channels to unsquelch channel audio.
=> #709 MPT1327 no audio on traffic channels.

src/main/java/io/github/dsheirer/source/tuner/TunerClass.java, src/main/java/io/github/dsheirer/source/tuner/TunerManager.java, src/main/java/io/github/dsheirer/source/tuner/hackrf/HackRFTunerController.java, src/main/java/io/github/dsheirer/source/tuner/usb/converter/SignedByteSampleConverter.java
- JawBreaker was partially defined but would not initialize
- HackRF samples are signed 8-bit. (If handled as unsigned 8-bit, you will notice a high noise floor and signal reflections around DC)
=> Fix HackRF-JawBreaker and HackRF sample conversion

src/main/java/io/github/dsheirer/record/wave/AudioMetadataUtils.java
Resolves #751
Adds quoted, comma-separated aliases to TRACK_TITLE metadata tag.
=> #751 Audio Recording - TRACK Metadata

src/main/java/io/github/dsheirer/module/decode/p25/phase2/P25P2DecoderHDQPSK.java
Resolves #783 
Corrects NPE error in P25 Phase2 decoder when setting scramble parameters
=> #783 P25 Phase 2 Channel Grants NPE

src/main/java/io/github/dsheirer/audio/playback/AudioOutput.java
Resolves #782 
Adds checks for NPE error in AudioOutput that can occur when computer awakes from sleep.
=> #782 Resolves NPE error in AudioOutput

src/main/java/io/github/dsheirer/module/decode/mpt1327/MPT1327TrafficChannelManager.java
This PR tries to fix something that I have observed for MPT1327 which seems like a bug to me.
Specifically, all calls after the first one to the same talkgroup on the same traffic channel are not decoded - the decoder for the traffic channel is not created nor initialized. Instead, the _past event for the channel_ is updated with new "end" timestamps from subsequent MPT messages. This can be seen here:
I've marked weird call durations which are a consequence of the "end" timestamp being updated for past events.
After short debugging it seems that this is the offending line:
https://github.com/DSheirer/sdrtrunk/blob/8167e9e9f2c07480a45fd417653e419b4ae016a0/src/main/java/io/github/dsheirer/module/decode/mpt1327/MPT1327TrafficChannelManager.java#L100
in case a go-to-channel event is already …
=> MPT1327: Fix decoding of calls to past talkgroups

src/main/java/io/github/dsheirer/gui/playlist/channel/MPT1327ConfigurationEditor.java, src/main/java/io/github/dsheirer/playlist/PlaylistManager.java
Resolves #831 
Resolves issue where channel map changes were not being persisted to the playlist file and the MPT1327 decoder editor was not correctly updating with changes from the channel map editor.
=> #831 Resolves issue with playlist editor and channel map editor.

src/main/java/io/github/dsheirer/source/tuner/usb/USBTransferProcessor.java
Resolves #724 issue with usb transfer buffer(s) memory leak.  Changes shutdown process to allow the completed buffer processor thread to finish, avoiding possible orphaned transfer(s).  Extends the shutdown wait cycle to allow libusb event processor more time to fully cancel transfers.
=> #724 USB Transfer Processor Potential Memory Leaks

src/main/java/io/github/dsheirer/gui/playlist/alias/AliasItemEditor.java
Resolves #837 
There's an ArrayIndexOutOfBoundsException rarely being thrown from within the JavaFX SortedLIst code whenever saving an alias and updating the alias name or alias group values.  
I don't see where the code is doing anything incorrectly.  I updated the save operation to wrap each of the calls to update the alias name and group in try/catch blocks to ensure the save operation completes for all alias attributes.
=> #837 Sorted list ArrayIndexOutOfBoundsException during alias save.

build.gradle, src/main/java/io/github/dsheirer/gui/playlist/radioreference/EnrichedSite.java, src/main/java/io/github/dsheirer/gui/playlist/radioreference/RadioReferenceDecoder.java, src/main/java/io/github/dsheirer/gui/playlist/radioreference/RadioReferenceUnavailableAlert.java, src/main/java/io/github/dsheirer/gui/playlist/radioreference/SiteEditor.java, src/main/java/io/github/dsheirer/gui/playlist/radioreference/SystemEditor.java, src/main/java/io/github/dsheirer/gui/playlist/radioreference/SystemSiteSelectionEditor.java
Resolves #864 
Updates radio reference service library to resolve issue where the library wasn't parsing the system information object correctly and was assuming a singular bandplan object versus an array of bandplans.
Updating the service library prompted some minor changes with the way that county info objects are handled for each site.
=> #864 Radio Reference System Bandplan Error

src/main/java/io/github/dsheirer/controller/channel/ChannelProcessingManager.java
Resolves #839 
Updates logging for tuner unavailable to allocate traffic channel frequencies.  Logs the frequency once and then suppresses further logging.
=> #839 Tuner Unavailable Logging Suppression

src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1MessageFramer.java
From issue #879:
When a BitSetFullException is caught and reset(0) is called, the BinaryMessage is set to null.
This should resolve issue #879.
=> #879 Move BinaryMessage isFull() check into try block to prevent NPE

src/main/java/io/github/dsheirer/gui/playlist/alias/AliasConfigurationEditor.java
Fixes issue #884 (see issue for more info).
AliasItemEditor.save() modifies objects that are observed by the
TableView's underlying SortedList.  Thus, the TableView's selection can
change by calling save(), which means the ListChangeListener can be
fired.
This is a problem for two reasons.
1. The alert dialogue that prompts the user to save a modified alias
will show when the user presses the "save" button, because saving
modifies the selected alias and causes the list to update.
2. setAliases() calls Alert.showAndWait().  From the JavaDoc:
"It must not be called during animation or layout processing."
This statement is likely there because it can cause issues like the one
here: TableView's layout processing (and the list updating) is paused
and the list is further modified (by calling …
=> #884 Wrap setAliases() in Platform.runLater()

src/main/java/io/github/dsheirer/gui/playlist/radioreference/RadioReferenceDecoder.java, src/main/java/io/github/dsheirer/gui/playlist/radioreference/SiteEditor.java
Resovles #890 issue where radio reference channel import only imports 1 of multiple listed control channels and adds improved detection for P25P2 simulcast sites to set the decoder type to LSM.
=> #890 Radio Reference Import - Multiple Control Channels

src/main/java/io/github/dsheirer/module/decode/ip/PacketMessageFactory.java, src/main/java/io/github/dsheirer/module/decode/ip/udp/UDPPacket.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DecoderState.java
Resolves #893 
Updates UDP packet to construct a Cellocator packet payload when the source or destination UDP port is 231 and any time the packet contains the correct start packet identifier.  Updates the decode event type label.
=> #893 Improved Cellocator Packet Detection

src/main/java/io/github/dsheirer/module/decode/mpt1327/MPT1327DecoderState.java, src/main/java/io/github/dsheirer/module/decode/mpt1327/MPT1327TrafficChannelManager.java
Resolves #909 MPT1327 call events don't show talkgroup aliases.
=> #909 MPT1327 Call Event Talkgroup Aliasing

src/main/java/io/github/dsheirer/audio/broadcast/broadcastify/BroadcastifyCallBroadcaster.java
Resolves #960 Adds handling to broadcastify streaming to not log an error when broadcastify tells us to skip an audio upload.  This is not an error because another broadcaster has already uploaded the audio segment.
=> #960 Broadcastify Skip Audio Upload Error Handling

src/main/java/io/github/dsheirer/gui/playlist/channel/AMConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/DMRConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/LTRConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/LTRNetConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/MPT1327ConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/NBFMConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/P25P1ConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/P25P2ConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/PassportConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/source/FrequencyEditor.java, src/main/java/io/github/dsheirer/module/decode/dmr/DecodeConfigDMR.java, src/main/java/io/github/dsheirer/module/decode/mpt1327/DecodeConfigMPT1327.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/DecodeConfigP25Phase1.java
Resolves #954.  Updates channel editors to use custom min/max channel rotation values on a per-protocol basis.
=> #954 Channel Rotation Delay Minimums - P25 and MPT1327

src/main/java/io/github/dsheirer/gui/playlist/channel/P25P2ConfigurationEditor.java
Resolves #969 
Resolves issue where P25P2 NAC value is saved incorrectly by configuration editor.
=> #969 P25P2 Configuration Editor - NAC Value 

src/main/java/io/github/dsheirer/controller/channel/event/ChannelStartProcessingRequest.java
Resolves #956 issue with null pointer in identifier collection on channel start.
=> #956 Identifier Collection NPE On Channel Start

src/main/java/io/github/dsheirer/gui/playlist/channel/DMRConfigurationEditor.java, src/main/java/io/github/dsheirer/module/decode/dmr/DMRDecoderState.java, src/main/java/io/github/dsheirer/module/decode/dmr/DMRNetworkConfigurationMonitor.java, src/main/java/io/github/dsheirer/module/decode/dmr/DecodeConfigDMR.java, src/main/java/io/github/dsheirer/module/decode/dmr/channel/DMRTier3Channel.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/csbk/standard/Clear.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/csbk/standard/MoveTSCC.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/csbk/standard/announcement/AdjacentSiteInformation.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/csbk/standard/announcement/AnnounceWithdrawTSCC.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/csbk/standard/announcement/VoteNowAdvice.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/csbk/standard/grant/ChannelGrant.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/lc/LCMessageFactory.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/lc/shorty/TrafficChannelSystemParameters.java
Resolves #979 
Resolves issue with DMR Tier III logical slot number calculation.
Provides user option to ignore CRC checksums for DMR decoder with RAS-enabled systems.  
Adds support for Tier III traffic channel system parameters SLCO message.
=> #979 DMR Tier 3 LSN and RAS Ignore CRC Option

src/main/java/io/github/dsheirer/source/tuner/TunerController.java, src/main/java/io/github/dsheirer/source/tuner/airspy/AirspyTunerController.java
Percentages based on @DSheirer's percentages given in the bug report.
Tested with the Airspy Mini, and the percentages seem to be good. The usable bandwidth with Airspy Mini at 3MHz is asymmetric, but probably close enough to be fine as it is.
Fixes #815 .
=> #815 - Change usable bandwidth percentage based on Airspy samplerate

src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DecoderState.java
This adds the **Encrypted** state to the Status column for P25 Phase 1 Voice Calls, and fixes issue #740.
I am fairly sure that this is the right way/place to fix this, and it seems to work correctly on a test recording I have.
Fixes #740 .
=> #740 - Adds Encrypted state to the Status column for P25 Phase 1 Voice Calls

src/main/java/io/github/dsheirer/gui/playlist/alias/AliasEditor.java, src/main/java/io/github/dsheirer/gui/playlist/alias/AliasViewByIdentifierEditor.java
Editing many aliases with the AliasBulkEditor becomes very slow when modifying more than just a few aliases.  When applying a change to 1000 aliases, the PlaylistEditor freezes for over a minute.  It turns out most of the processing time came down to running the updateList() method in the ViewByIdentifierEditor class, as it was called multiple times per modified alias.  By changing the editor to only update its list when it is selected updateList() is no longer called in the background unnecessarily.  The same bulk edits take seconds instead of minutes.
I can't help but feel like the way I implemented the change is a bit ugly but it's the best I could come up with without making a lot of changes to AliasViewByIdentifierEditor.  I wanted to change how the list worked so it wouldn't have to …
=> Only update ViewByIdentifierEditor's list when the editor is selected

src/main/java/io/github/dsheirer/controller/channel/Channel.java
Resolves #981 sets channel short title as ignore for serialization.
=> 981 Channel Short Title Serialization

src/main/java/io/github/dsheirer/source/tuner/FrequencyErrorCorrectionManager.java, src/main/java/io/github/dsheirer/source/tuner/airspy/AirspyTunerController.java, src/main/java/io/github/dsheirer/source/tuner/fcd/FCDTunerController.java, src/main/java/io/github/dsheirer/source/tuner/fcd/proV1/FCD1TunerController.java, src/main/java/io/github/dsheirer/source/tuner/fcd/proplusV2/FCD2TunerController.java, src/main/java/io/github/dsheirer/source/tuner/hackrf/HackRFTunerController.java, src/main/java/io/github/dsheirer/source/tuner/rtl/RTL2832TunerController.java, src/main/java/io/github/dsheirer/source/tuner/rtl/e4k/E4KTunerController.java, src/main/java/io/github/dsheirer/source/tuner/rtl/r820t/R820TTunerController.java
Resolves #973.  Adds concurrent locking to primary tuner controller methods to avoid concurrent access to USB methods.
=> 973 Tuner Controller Concurrent Locking - Avoid USB Pipe Errors

build.gradle, src/main/java/io/github/dsheirer/gui/playlist/radioreference/LoginDialog.java, src/main/java/io/github/dsheirer/gui/playlist/radioreference/RadioReferenceEditor.java, src/main/java/io/github/dsheirer/gui/playlist/radioreference/SystemEditor.java, src/main/java/io/github/dsheirer/service/radioreference/RadioReference.java, src/test/java/io/github/dsheirer/service/radioreference/RadioReferenceTest.java
This PR has some improvements around Radio Reference, Premium Accounts, and the Playlist Import system.
- The Login pane now lets you know if you're logging in with a valid RR account, but that is _not_ a Premium account. This should help with issues like #888, where users don't realize that a Premium account is required for import.
- The Radio Reference Playlist Importer locks out the UI elements if the account doesn't have a valid, premium account, or isn't logged in. Additionally, an error message is displayed if the account isn't Premium.
- The UI is enabled with a valid, Premium account.
- I added a new `SimpleBooleanProperty` for the Premium Status, as I think (?) the user can be logged in with a non-Premium account, but should still have access to Broadcastify upload.
- The PR …
=> RR User Interface Improvements, including Premium notices

src/main/java/io/github/dsheirer/gui/playlist/channel/DMRConfigurationEditor.java, src/main/java/io/github/dsheirer/sample/buffer/ReusableComplexBufferAssembler.java
Resolves #1004 sample processing threading issue where the sample listener is nullified while buffer processing is still in progress.
=> 1004 Sample Processing Multi-Threading Issue

.idea/misc.xml, build.gradle
Updates gradle build system to address classes that are now hidden in Java 17 and no longer exported from the base modules.
Updated build system to specifically call out JavaFX OS-specific libraries and target these to each of the OS-specific build products.
Removes jcenter as a maven repo since it's now deprecated.
=> Resolves #1094.

src/main/java/io/github/dsheirer/gui/playlist/alias/AliasBulkEditor.java, src/main/java/io/github/dsheirer/gui/playlist/alias/AliasConfigurationEditor.java
When the user has selected a column to sort by on the TableView in the Alias editor, the table's backing SortedList will resort every time an ObservableProperty of an Alias is modified.  This can cause the UI to lock up for minutes at a time if many Aliases are modified at once using the AliasBulkEditor.
This change works around this issue by simply resetting the SortedList's ComparatorProperty while the AliasBulkEditor is applying changes, and rebinding it back to the TableView's ComparatorProperty once AliasBulkEditor has finished.
This change seems a bit hacky to me but it's the cleanest thing I could come up with.  I couldn't find a way to set a property's value to null via a binding, so unbinding and rebinding had to do.  I hope that I'm missing a simple solution to this problem …
=> Don't sort Alias TableView while bulk changes are applied

build.gradle, src/main/java/io/github/dsheirer/module/log/DecodeEventLogger.java, src/test/java/io/github/dsheirer/module/log/DecodeEventLoggerTest.java
Fixes #1038.
Hand-crafting a serialized format will always be a losing proposition. Brings in Apache's Commons CSV to provide a bulletproof CSV-formatted string to be written into the log. This has an additional benefit of making aliases and details safe to use quotes and commas (as well as other "reserved" CSV characters). 
To preserve the existing behaviour of SDR Trunk's CSV logging, every value/cell is wrapped in quotes, even if it isn't explicitly needed.
Adds tests to ensure the strings are as we expect.
=> Properly format and safely escape to CSV in DecodeEventLogger

src/main/java/io/github/dsheirer/module/decode/mdc1200/identifier/MDC1200Identifier.java, src/main/java/io/github/dsheirer/module/decode/tait/identifier/TaitIdentifier.java
Resolves #1102 
Adds Comparable to identifiers used in TreeSet.
=> #1102 Adds Comparable to identifiers that are used in TreeSets.

src/main/java/io/github/dsheirer/module/decode/ip/lrrp/LRRPHeader.java, src/main/java/io/github/dsheirer/module/decode/ip/lrrp/LRRPPacket.java, src/main/java/io/github/dsheirer/module/decode/ip/lrrp/LRRPPacketType.java, src/main/java/io/github/dsheirer/module/decode/ip/lrrp/token/GeoFencePosition.java, src/main/java/io/github/dsheirer/module/decode/ip/lrrp/token/GeoFencePosition3D.java, src/main/java/io/github/dsheirer/module/decode/ip/lrrp/token/Heading.java, src/main/java/io/github/dsheirer/module/decode/ip/lrrp/token/Position.java, src/main/java/io/github/dsheirer/module/decode/ip/lrrp/token/Response.java, src/main/java/io/github/dsheirer/module/decode/ip/lrrp/token/ResponseCode.java, src/main/java/io/github/dsheirer/module/decode/ip/lrrp/token/TokenFactory.java, src/main/java/io/github/dsheirer/module/decode/ip/lrrp/token/TokenType.java, src/main/java/io/github/dsheirer/module/decode/ip/lrrp/token/Version.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DecoderState.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1MessageFramer.java, src/main/java/io/github/dsheirer/util/PacketUtil.java
Resoves #1113.
Updates LRRP protocol to correctly identify geo-fence positions and to add support for packet type identification.  Corrects issue with N/S and E/W hemisphere calculations.
=> 1113 Update LRRP Protocol With Geo-Fence and Hemisphere Parsing Correction

src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelSource.java, src/main/java/io/github/dsheirer/dsp/filter/decimate/ComplexDecimateX0Filter.java, src/main/java/io/github/dsheirer/dsp/filter/decimate/DecimationFilterFactory.java, src/main/java/io/github/dsheirer/dsp/filter/decimate/RealDecimateX0Filter.java, src/main/java/io/github/dsheirer/dsp/filter/halfband/complex/ComplexHalfBandDecimationFilter.java, src/main/java/io/github/dsheirer/module/decode/nbfm/NBFMDecoder.java, src/main/java/io/github/dsheirer/sample/buffer/AbstractReusableBufferQueue.java, src/main/java/io/github/dsheirer/sample/buffer/ReusableComplexBufferQueue.java
Resolves #1122.  Adds decimation to NBFMDecoder so that channel bandwidth is reduced to min sample rate needed.  This reduces the impact on channel power measurement from adjacent channels.
=> 1122 Adjacent Channel Signal Impacts NBFM Squelch Performance

src/main/java/io/github/dsheirer/audio/broadcast/broadcastify/BroadcastifyCallBroadcaster.java, src/main/java/io/github/dsheirer/identifier/patch/PatchGroupManager.java, src/main/java/io/github/dsheirer/identifier/patch/PatchGroupPreLoadDataContent.java, src/main/java/io/github/dsheirer/module/decode/p25/P25TrafficChannelManager.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DecoderState.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/P25P2DecoderState.java
Closes #1152 
Resolves issue where patch groups were not being properly formatted when uploading to broadcastify calls api.
Identified issue where the patch group manager for the control channel had the correct patch group details, but was not passing the patch group to the traffic channel on startup, so any call audio generated on the traffic channel had a good chance that it was missing the patch group details.
=> #1152 Broadcastify Calls - Patch Groups Not Formatted Correctly

src/main/java/io/github/dsheirer/jmbe/JmbeCreator.java, src/main/java/io/github/dsheirer/util/OSType.java
#1154 updates JMBE creator to work correctly with arm32 and aarch64 architectures.
=> #1154 JMBE Creator ARM32 and AARCH64

build.gradle
Resolves #1160.  
Adds usb4java native library support for Mac/OSX M1 aarch64 processor.
=> Mac/OSX M1 aarch64 Native Library for libusb/usb4java

src/main/java/io/github/dsheirer/vector/calibrate/airspy/AirspyUnpackedCalibration.java, src/main/java/io/github/dsheirer/vector/calibrate/airspy/AirspyUnpackedInterleavedCalibration.java
Resolves #1163 
Resolves issue with airspy unpacked calibrations hanging.  Updates each test to check elapsed timer on a more granular scale on the theory that the SIMD vector implementation is horribly slow on some systems.
=> #1163 Airspy Buffer Iterator Calibrations Hang

src/main/java/io/github/dsheirer/source/tuner/TunerManager.java
Currently, when the R828D Tuner is detected, the only message that gets sent to the log is Unknown Device.  For example:
`14:03:22.625 INFO  i.g.d.s.t.TunerManager - USB Bus [1] Device [0BDA:2838]  Unknown Device - Class 0  [25MB/128MB 19%]`
There is already a well constructed exception message being constructed in TunerManager.java:
```
private TunerInitStatus initRTL2832Tuner(TunerClass tunerClass, Device device, DeviceDescriptor deviceDescriptor)
{
case RAFAELMICRO_R828D:
case UNKNOWN:
default:
reason = "SDRTRunk doesn't currently support RTL2832 Dongle with [" + tunerType.toString() +
"] tuner for tuner class[" + tunerClass.toString() + "]";
break;
}
```
After adding the mlog(reason) before the break; command, the error message is more descriptive:
```
15:00:39.982 INFO …
```
=> Add error message for R828D Tuner

build.gradle
Resolves #1165 
Reverts changes to gradle runtimeZip task behavior.  Enables 3 options for building target OS and CPU images:
1. Build using local JDK 
2. Build all targets using pre-downloaded JDKs
3. Automatically download all JDKs and build all targets.
=> #1165 Revert/Enhance Gradle runtimeZip Task Changes

src/main/java/io/github/dsheirer/alias/action/beep/BeepAction.java, src/main/java/io/github/dsheirer/audio/AudioFormats.java, src/main/java/io/github/dsheirer/audio/broadcast/AudioStreamingBroadcaster.java, src/main/java/io/github/dsheirer/audio/broadcast/BroadcastFactory.java, src/main/java/io/github/dsheirer/audio/broadcast/broadcastify/BroadcastifyCallBroadcaster.java, src/main/java/io/github/dsheirer/audio/broadcast/icecast/IcecastAudioBroadcaster.java, src/main/java/io/github/dsheirer/audio/broadcast/icecast/IcecastHTTPAudioBroadcaster.java, src/main/java/io/github/dsheirer/audio/broadcast/icecast/IcecastTCPAudioBroadcaster.java, src/main/java/io/github/dsheirer/audio/broadcast/shoutcast/v1/ShoutcastV1AudioBroadcaster.java, src/main/java/io/github/dsheirer/audio/broadcast/shoutcast/v2/ShoutcastV2AudioStreamingBroadcaster.java, src/main/java/io/github/dsheirer/audio/convert/InputAudioFormat.java, src/main/java/io/github/dsheirer/audio/convert/LameFactory.java, src/main/java/io/github/dsheirer/audio/convert/MP3AudioConverter.java, src/main/java/io/github/dsheirer/audio/convert/MP3FrameInspector.java, src/main/java/io/github/dsheirer/audio/convert/MP3SilenceGenerator.java, src/main/java/io/github/dsheirer/audio/playback/MonoAudioOutput.java, src/main/java/io/github/dsheirer/audio/playback/StereoAudioOutput.java, src/main/java/io/github/dsheirer/gui/preference/mp3/MP3PreferenceEditor.java, src/main/java/io/github/dsheirer/gui/preference/playback/PlaybackPreferenceEditor.java, src/main/java/io/github/dsheirer/preference/mp3/MP3Preference.java, src/main/java/io/github/dsheirer/record/AudioSegmentRecorder.java, src/main/java/io/github/dsheirer/sample/ConversionUtils.java, src/main/java/io/github/dsheirer/source/mixer/MixerManager.java
Closes #1170
Resolves issue with MP3 encoded audio raspy.  Adds auto-clipping of PCM audio prior to encoding and adds 4x new 32-bit input sample rate selections to choose from, in addition to original 4x 16-bit input formats.
=> #1170 MP3 Audio Raspy and Add 32-Bit Input Audio Options

src/main/java/io/github/dsheirer/dsp/psk/InterpolatingSampleBuffer.java
Closes #1169 
Resolves issue where P25 C4FM decoder can request an interpolated sample value that is less than 0.  Not sure why or what is causing this but this change guards against an ArrayIndexOutOfBounds exception when it does happen.
=> #1169 P25 C4FM Interpolator - ArrayIndexOutOfBounds Exception

src/main/java/io/github/dsheirer/controller/channel/ChannelProcessingManager.java
#1186 removes error logging that indicates that a channel cannot be stopped because it doesn't exist.  This happens when a second successive attempt to stop a channel fails to find the channel because the first attempt has already removed the channel from the list.
=> #1186 Remove Logging That Stop Request Failed To Find Channel

src/main/java/io/github/dsheirer/audio/AudioSegmentBroadcaster.java, src/main/java/io/github/dsheirer/gui/control/JFrequencyControl.java, src/main/java/io/github/dsheirer/sample/Broadcaster.java, src/main/java/io/github/dsheirer/source/tuner/Tuner.java, src/main/java/io/github/dsheirer/source/tuner/TunerController.java, src/main/java/io/github/dsheirer/source/tuner/frequency/FrequencyController.java, src/main/java/io/github/dsheirer/source/tuner/manager/ChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/FrequencyErrorCorrectionManager.java, src/main/java/io/github/dsheirer/source/tuner/rtl/RTL2832TunerController.java, src/main/java/io/github/dsheirer/source/tuner/ui/DiscoveredTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/ui/TunerEditor.java
Resolves #1210 
Tuner instances can't be garbage collected due to retained references.  Updates several of the tuner controller and tuner editor classes to add/invoke dispose() methods to clear retained instance references.
=> #1210 Tuner Instance Memory Leak

src/main/java/io/github/dsheirer/source/tuner/rtl/RTL2832TunerController.java, src/main/java/io/github/dsheirer/source/tuner/ui/TunerEditor.java
Resolves #1219 
Resolves issue with restarting error tuner causing UI thread lockup and an NPE when accessing the embedded tuner type of an error RTL2832 tuner where the embedded tuner was not initialized.
=> #1219 resolves issues with NPE and restarting an error tuner.

src/main/java/io/github/dsheirer/source/tuner/TunerClass.java, src/main/java/io/github/dsheirer/source/tuner/airspy/AirspyTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/manager/DiscoveredTuner.java, src/main/java/io/github/dsheirer/source/tuner/manager/DiscoveredUSBTuner.java, src/main/java/io/github/dsheirer/source/tuner/manager/TunerManager.java, src/main/java/io/github/dsheirer/source/tuner/ui/DiscoveredTunerModel.java, src/main/java/io/github/dsheirer/source/tuner/ui/TunerEditor.java
#1221 resolves null pointer exception in tuner editor when attempting to restart an error tuner.
Closes #1221
=> #1221 Tuner Editor NPE On Restart

src/main/java/io/github/dsheirer/source/tuner/airspy/AirspyTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/hackrf/HackRFTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/manager/TunerManager.java, src/main/java/io/github/dsheirer/source/tuner/usb/USBTunerController.java
Resolves #1223 NPE when Airspy and HackRF tuners are re-enabled after startup.  Slight tweaks to TunerManager to change when discovered USB device startup takes place to potentially address intermittent fail on start for some tuners that users are seeing.  Resolves issue where a started device was not unreferenced in LibUsb on shutdown.
=> #1223 Airspy and HackRF Editor NPE on Enable

src/main/java/io/github/dsheirer/audio/broadcast/broadcastify/BroadcastifyCallBroadcaster.java, src/main/java/io/github/dsheirer/audio/broadcast/broadcastify/BroadcastifyCallConfiguration.java, src/main/java/io/github/dsheirer/gui/playlist/streaming/BroadcastifyCallEditor.java
Adds a configuration toggle for the scheduled connection test, defaulting to off, as well as a configurable interval that defaults to 15 minutes.
=> Make Broadcastify Calls scheduled test configurable

src/main/java/io/github/dsheirer/filter/FilterSet.java, src/main/java/io/github/dsheirer/module/decode/event/DecodeEvent.java, src/main/java/io/github/dsheirer/module/decode/event/DecodeEventModel.java, src/main/java/io/github/dsheirer/module/decode/event/DecodeEventPanel.java, src/main/java/io/github/dsheirer/module/decode/event/IDecodeEvent.java, src/main/java/io/github/dsheirer/module/decode/event/filter/DecodeEventFilterSet.java, src/main/java/io/github/dsheirer/module/decode/event/filter/DecodedCallEncryptedEventFilter.java, src/main/java/io/github/dsheirer/module/decode/event/filter/DecodedCallEventFilter.java, src/main/java/io/github/dsheirer/module/decode/event/filter/DecodedCommandEventFilter.java, src/main/java/io/github/dsheirer/module/decode/event/filter/DecodedDataEventFilter.java, src/main/java/io/github/dsheirer/module/decode/event/filter/DecodedRegistrationEventFilter.java, src/main/java/io/github/dsheirer/module/decode/event/filter/EventClearButton.java, src/main/java/io/github/dsheirer/module/decode/event/filter/EventClearHandler.java, src/main/java/io/github/dsheirer/module/decode/event/filter/EventFilter.java, src/main/java/io/github/dsheirer/module/decode/event/filter/EventFilterButton.java, src/main/java/io/github/dsheirer/module/decode/event/filter/EventFilterProvider.java, src/main/java/io/github/dsheirer/module/decode/p25/P25ChannelGrantEvent.java, src/main/java/io/github/dsheirer/module/decode/p25/P25TrafficChannelManager.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DecoderState.java
These changes add the Filter and Clear buttons to the Events tab in the decode section.
This fixes one bug found in the FilterSet that only checked the first IFilter in the list.
Please note: I grouped the Decoded Events into categories as best as I could. If those don't match I will be happy to modify the branch or feel free to update as necessary.
I will be creating a second PR for additional updates to the other protocols. This is for P25 only.
=> Add filter button to messages

src/main/java/io/github/dsheirer/audio/AudioUtils.java, src/main/java/io/github/dsheirer/audio/convert/MP3AudioConverter.java
Normalize peak audio level in each recording to -0.44dBFS, limited to a maximum boost of ~19.5dB, to help quiet people be less quiet.
=> Normalize audio before recording

src/main/java/io/github/dsheirer/identifier/IdentifierCollection.java, src/main/java/io/github/dsheirer/record/wave/AudioMetadataUtils.java
Modifies getToIdentifier() and getFromIdentifier() to return the most appropriate value, rather than the first, and then use them in AudioMetadataUtils for consistency.
=> Generate audio metadata with correct to/from

src/main/java/io/github/dsheirer/source/tuner/TunerFactory.java, src/main/java/io/github/dsheirer/source/tuner/airspy/AirspyTunerController.java, src/main/java/io/github/dsheirer/source/tuner/fcd/FCDTunerController.java, src/main/java/io/github/dsheirer/source/tuner/fcd/proV1/FCD1TunerController.java, src/main/java/io/github/dsheirer/source/tuner/fcd/proplusV2/FCD2TunerController.java, src/main/java/io/github/dsheirer/source/tuner/hackrf/HackRFTunerController.java, src/main/java/io/github/dsheirer/source/tuner/manager/DiscoveredUSBTuner.java, src/main/java/io/github/dsheirer/source/tuner/manager/TunerManager.java, src/main/java/io/github/dsheirer/source/tuner/rtl/RTL2832TunerController.java, src/main/java/io/github/dsheirer/source/tuner/ui/DiscoveredTunerModel.java, src/main/java/io/github/dsheirer/source/tuner/usb/USBTunerController.java
#1229 Resolves issue with correctly identifying the port number for USB tuners that is causing some tuners not to be recognized and also generating udev errors when sdrtrunk attempts to start an already started device because it was incorrectly identified.
=> #1229 Use Port Address for USB Tuners

src/main/java/io/github/dsheirer/spectrum/ClearTunerMenuItem.java, src/main/java/io/github/dsheirer/spectrum/ShowTunerMenuItem.java, src/main/java/io/github/dsheirer/spectrum/SpectralDisplayPanel.java
Prevent showTuner() from starting spectral display after user has disabled it. Persists disabled state through restarts.
Resolves #1231.
=> Don't show tuner on spectral display while disabled

.idea/misc.xml, src/main/java/io/github/dsheirer/source/tuner/ui/TunerEditor.java
Closes #1239
Resolves issue of view spectrum when the spectral display is disabled.  Tuner editor button overrides the property setting so that the view completes correctly.
=> #1239 Tuner Editor View Spectrum - Override Spectral Disabled State

src/main/java/io/github/dsheirer/audio/broadcast/broadcastify/BroadcastifyCallBroadcaster.java
Updates Calls to take advantage of new getToIdentifier() logic to prefer patch group > talk group > other identifier. 
Corrects issue observed with DMR calls having both identifiers, with a radio ID first, which was causing us to send the wrong identifier.
=> Prefer talkgroup ID over radio ID for BCFY Calls

src/main/java/io/github/dsheirer/source/tuner/ui/TunerSpectralDisplayManager.java, src/main/java/io/github/dsheirer/spectrum/SpectralDisplayPanel.java
Closes #1245 
Updates spectral display show tuner options to allow new display without changing disabled state of primary display.
=> #1245 New Spectral Display Doesn't Override Disabled State

src/main/java/io/github/dsheirer/controller/channel/ChannelProcessingManager.java, src/main/java/io/github/dsheirer/controller/channel/event/ChannelStopProcessingRequest.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelManager.java, src/main/java/io/github/dsheirer/playlist/PlaylistManager.java, src/main/java/io/github/dsheirer/sample/Broadcaster.java, src/main/java/io/github/dsheirer/source/tuner/Tuner.java, src/main/java/io/github/dsheirer/source/tuner/channel/TunerChannelSource.java, src/main/java/io/github/dsheirer/source/tuner/manager/ChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/HeterodyneChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/PassThroughSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/ui/TunerSpectralDisplayManager.java
Closes #1234 
Updates USB tuner error handling to prevent stack overflow when tuner error occurs while streaming.
=> #1234 Airspy Tuner Error Causes Stack Overflow

src/main/java/io/github/dsheirer/source/tuner/TunerFactory.java, src/main/java/io/github/dsheirer/source/tuner/configuration/TunerConfigurationManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/DiscoveredRecordingTuner.java, src/main/java/io/github/dsheirer/source/tuner/manager/TunerManager.java, src/main/java/io/github/dsheirer/source/tuner/recording/AddRecordingTunerDialog.java, src/main/java/io/github/dsheirer/source/tuner/recording/RecordingTuner.java, src/main/java/io/github/dsheirer/source/tuner/recording/RecordingTunerConfiguration.java, src/main/java/io/github/dsheirer/source/tuner/recording/RecordingTunerController.java, src/main/java/io/github/dsheirer/source/tuner/recording/RecordingTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/ui/TunerViewPanel.java
Closes #1257 
Restores recording tuner feature.  sdrtrunk now supports multiple recording tuners.  Recordings are automatically loaded/restored on application start and each recording tuner has to be manually enabled for use.
=> #1257 Restore Baseband Recording Tuner Support

src/main/java/io/github/dsheirer/buffer/ByteNativeBuffer.java, src/main/java/io/github/dsheirer/buffer/ByteNativeBufferFactory.java, src/main/java/io/github/dsheirer/buffer/SignedByteNativeBufferFactory.java
#1284 Resolves issue with inherent DC bias (-0.5) in RTL2832 sample conversion code.
=> #1284 RTL2832 Samples Exhibit Inherent DC Bias 

build.gradle, src/main/java/io/github/dsheirer/buffer/ByteNativeBufferFactory.java, src/main/java/io/github/dsheirer/buffer/DcCorrectionManager.java, src/main/java/io/github/dsheirer/buffer/airspy/ScalarPackedSampleConverter.java, src/main/java/io/github/dsheirer/buffer/airspy/ScalarUnpackedSampleConverter.java, src/main/java/io/github/dsheirer/buffer/airspy/VectorUnpackedSampleConverter.java
Closes #1291 
Updates tuner sample stream processing for DC removal to run on a periodic timer to reduce overall processing requirements.
=> #1291 Make Tuner DC Processing Run On Interval

src/main/java/io/github/dsheirer/settings/ColorSetting.java
#1336 Resolves issue with color setting changes not inheriting the correct translucency which causes the channel overlays in the spectral display to be solid color instead of semi-transparent.
=> #1336 Channel Overlay - Color Setting Translucency

.idea/misc.xml, src/main/java/io/github/dsheirer/source/SourceEvent.java, src/main/java/io/github/dsheirer/source/tuner/TunerController.java, src/main/java/io/github/dsheirer/source/tuner/airspy/AirspyTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/frequency/FrequencyController.java, src/main/java/io/github/dsheirer/source/tuner/hackrf/HackRFTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/manager/HeterodyneChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/PassThroughSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/PolyphaseChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/rtl/e4k/E4KTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/rtl/r820t/R820TTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/ui/DiscoveredTunerModel.java, src/main/java/io/github/dsheirer/source/tuner/ui/TunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/ui/TunerViewPanel.java
#1340 Updates tuner and frequency controllers to apply locking to ensure multi-threaded access to frequency control plane doesn't allow center tuned frequency to become indeterminant which can result in channels being mistuned and stop decoding.  This resolves a likely issue that was causing users to report that their channels stopped decoding after a while.  Decoding multiple control channels, user changing the PPM settings on the tuner, and tuner auto-PPM correction were each allowed unprotected access to the frequency control plane and could potentially step on each other.  New locking behavior ensures that channel source allocations and PPM corrections complete atomically through the use of a reentrant lock.
=> #1340 Tuner Frequency Controller - Threading Issue

.idea/misc.xml, src/main/java/io/github/dsheirer/spectrum/WaterfallPanel.java
#1343 Resolves issue where user-initiated FFT size change causes waterfall panel pixel array to be updated/resized while a memory image source repaint has been requested and the parameters become incongruent, causing an array index out of bounds error.  Pushes the pixel array update operation onto the swing thread to ensure only a single thread is modifying the pixel map for rendering.
=> #1343 Waterfall Repaint Causes ArrayIndexOutOfBounds Exception

src/main/java/io/github/dsheirer/identifier/tone/ToneIdentifierMessage.java, src/main/java/io/github/dsheirer/module/decode/dmr/audio/DMRAudioModule.java, src/main/java/io/github/dsheirer/module/decode/p25/audio/P25P2AudioModule.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1MessageFramer.java
#1358 Resolves issue where decoded AMBE (DMR & P25-2) tone identifiers are not sent to the alias action manager.
=> #1358 AMBE Tone Identifiers Should Trigger Alias Actions

src/main/java/io/github/dsheirer/source/tuner/manager/CenterFrequencyCalculator.java
Resolves #1362 
Updates heterodyne channelizer with alternate sorted set implementation to resolve issue when determining if the tuner can tune a requested channel.
=> #1362 Heterodyne Channel Calculator Should Use Alternate Sorted Set Implementation

src/main/java/io/github/dsheirer/audio/broadcast/AudioStreamingBroadcaster.java, src/main/java/io/github/dsheirer/audio/convert/AudioFrames.java, src/main/java/io/github/dsheirer/audio/convert/MP3AudioFrames.java, src/main/java/io/github/dsheirer/audio/convert/MP3FrameInspector.java, src/main/java/io/github/dsheirer/audio/convert/MP3FrameTools.java, src/main/java/io/github/dsheirer/audio/convert/MP3Header.java, src/main/java/io/github/dsheirer/audio/convert/MP3SilenceGenerator.java
LAME is generating too much silence for the duration of audio we provide. This looks at each individual frame we get back and only includes the minimum number necessary to fulfill our silence needs.
=> Handle streaming audio as frames

src/main/java/io/github/dsheirer/audio/convert/MP3AudioConverter.java
If the MP3 encoder is unable to support the configured sample rate, disable resampling and warn, rather than resampling twice to the incorrect sample rate.
Warning should help users identify #1237 and self-resolve configuration, since it's not possible to disable resampling in ```LameEncoder```.
The defaults should be adjusted to 16kbps/16kHz or 32kbps/22.05kHz to have a valid combination. Let me know if you'd like me to include that in this PR or submit another, and your preference, if so. Pros and cons, both ways.
=> Disable resampling if requested sample rate not supported

src/main/java/io/github/dsheirer/audio/convert/InputAudioFormat.java, src/main/java/io/github/dsheirer/audio/convert/MP3AudioConverter.java, src/main/java/io/github/dsheirer/audio/convert/MP3Setting.java, src/main/java/io/github/dsheirer/gui/preference/mp3/MP3PreferenceEditor.java, src/main/java/io/github/dsheirer/preference/mp3/MP3Preference.java
Closes #1237 
Ensure MP3 input sample rate is supported by LAME encoder settings.
Through testing discovered that the following MP3 settings and input sample rates are not supported by LAME:
* CBR_16 > SR22050, SR_32_22050, SR_44100, SR_32_44100
* CBR_32 > SR_44100, SR_32_44100
* VBR_7 > SR_44100, SR_32_44100
* Updated default audio input sample rate to 16-bit 16 kHz (from 22.05 kHz) which is supported across all MP3 encoder settings
* Updated User Preferences dialog and settings to prevent user selecting an unsupported combination -- input sample rate is corrected to default in cases where user previously selected a sample rate
* Updated MP3 Setting to auto-correct any previously selected unsupported combination
* Updated MP3AudioConverter to auto-correct any unsupported combination, …
=> #1237 Ensure LAME supports MP3 encoder setting and input sample rate

src/main/java/io/github/dsheirer/gui/playlist/radioreference/SystemEditor.java
Closes #1312 
Resolves issue with radio reference editor attempting to access county info for a site that has county ID set to 0 (ie no county specified).
This system, site '1.9':
https://www.radioreference.com/db/sid/6694
=> #1312 Radio Reference Editor Fails on Site With No County

src/main/java/io/github/dsheirer/audio/broadcast/icecast/IcecastTCPAudioBroadcaster.java, src/main/java/io/github/dsheirer/source/tuner/usb/USBTunerController.java
Closes #1378 
Resolves potential error where tuner shutdown (because of USB I/O error) hangs and causes application to run out of memory.  USB tuner controller shutdown is not spun off on a thread and the calling shutdown process waits up to 500ms for a shutdown, otherwise it interrupts the shutdown thread and presses on.
Updates transfer buffer submit process to detect when there is a USB/IO error and stores failed transfer submissions in a temporary queue for later retry.  Attempts resubmit failed transfers after a successful transfer submit to increase odds of success.  Once all available transfers are in the error retry queue, shuts down the tuner.
=> #1378 USB I/O Error & Tuner Shutdown - Potential Application Lockup

src/main/java/io/github/dsheirer/source/tuner/manager/DiscoveredTuner.java
Closes #1383 
Updates tuner editor to resolve sequencing issue where a recently enabled tuner was having its enabled state set to true and then enabling the tuner, which caused the tuner editor to mis-configure the tuner editor panel.
=> #1383 Tuner Editor Inconsistent State On Tuner Enable

src/main/java/io/github/dsheirer/dsp/filter/channelizer/ChannelCalculator.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelManager.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelSource.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/TwoChannelSynthesizerM2.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/output/IPolyphaseChannelOutputProcessor.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/output/OneChannelOutputProcessor.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/output/TwoChannelMixerAssembler.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/output/TwoChannelOutputProcessor.java, src/main/java/io/github/dsheirer/dsp/gain/complex/ComplexGain.java, src/main/java/io/github/dsheirer/gui/power/ChannelPowerPanel.java, src/main/java/io/github/dsheirer/module/ProcessingChain.java, src/main/java/io/github/dsheirer/source/tuner/manager/ChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/DiscoveredTuner.java, src/main/java/io/github/dsheirer/source/tuner/manager/HeterodyneChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/PassThroughSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/PolyphaseChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/ui/DiscoveredTunerModel.java, src/main/java/io/github/dsheirer/source/tuner/ui/TunerViewPanel.java
Closes #1397 
Resolves issue where decoding channels go IDLE after period of time.  Isolated cause to a multi-threading issue where the polyphase channel manager receives notification that the tuner center frequency has changed and sets a flag to update each of the channels.  This happens concurrent with a previous tuner center frequency change where the flag gets set and the second thread is updating the channel output processors with the previous frequency change and then unsets the frequency change flag, completely missing the second/latest frequency change update and causing the channels to all tune-out their desired signals as the tuner center frequency changes and the output channels continue mixing to the previous frequency.
Identified and resolved issue where a 2-stream polyphase …
=> #1397 Decoding Channels Go IDLE After Period of Time

src/main/java/io/github/dsheirer/source/tuner/usb/USBTunerController.java
Closes #1408 
Updates USB tuners to enhance transfer buffer error handling and logging.  When an error occurs while (re)submitting a transfer buffer to LibUsb to fill with sample data, the buffer is temporarily placed in an error queue.  Upon successfully submitting the next transfer buffer, we attempt to resubmit a buffer from the error queue, so that we wait until the device can accept buffers before trying to resubmit.  If all transfer buffers are exhausted because they are in the error queue, then the tuner gets shutdown with an error state ... there's really no way to recover at this point.
=> #1408 Enhance USB Transfer Buffer Error Handling in USB Tuners

src/main/java/io/github/dsheirer/module/decode/event/DecodeEventType.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DecoderState.java
#1416 Updates P25-P1 To Expose ICMP & Unknown Packet Events in Event History View
=> #1416 P25-P1 ICMP & Unknown Packet Handling

src/main/java/io/github/dsheirer/audio/broadcast/BroadcastState.java
Closes #1423 
Updates Icecast/Broadcastify feed to attempt reconnect following a mountpoint in use error response.
=> #1423 Icecast Should Attempt Reconnect On Mountpoint In Use Response

src/main/java/io/github/dsheirer/gui/playlist/alias/identifier/RadioIdEditor.java, src/main/java/io/github/dsheirer/gui/playlist/alias/identifier/RadioIdRangeEditor.java, src/main/java/io/github/dsheirer/gui/playlist/alias/identifier/TalkgroupEditor.java, src/main/java/io/github/dsheirer/gui/playlist/alias/identifier/TalkgroupRangeEditor.java
Closes #1393 
Updates Playlist editor's DMR Talkgroup and Radio ID editors to use correct (decimal vs hex) formatting.  
Patch submitted by @hockeyref2
=> #1393 DMR Talkgroup & Radio ID Editors Should Use Correct Formats

build.gradle, src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/SDRplay.java
Closes #1456.
Resolves issue with shutdown when sdrplay api is not installed.
=> #1456 Shutdown Error When SDRPlay API Not Installed

src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/SDRplay.java
Closes #1461 
Updates expected library path/name for OSX.
=> #1461 SDRPlay Library Path on OSX

src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/SDRplay.java
Closes #1464 Reduces logging when SDRplay API is not installed on local machine.
=> #1464 Reducing Logging When SDRPlay API Not Installed On Local Machine

build.gradle, src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelSource.java
Closes #1405 
Resolves issue with some polyphase channel threads not shutting down correctly after the tuner's center frequency changes and the polyphase channel changes from 1 > 2 channel slots, or vice-versa.  
Resolves issue with building distro releases using non-local JDKs.
Increases build to version 0.6.0 alpha 4
=> #1405 Thread Leak in Polyphase Channelizer

src/main/java/io/github/dsheirer/source/tuner/sdrplay/ControlRsp.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/IControlRsp.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/IGainOverloadListener.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/RspSampleRate.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/RspTunerConfiguration.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/RspTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/SDRplay.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rsp1/Rsp1TunerController.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rsp1/Rsp1TunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rsp1a/Rsp1aTunerController.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rsp1a/Rsp1aTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rsp2/Rsp2TunerController.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rsp2/Rsp2TunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rspDuo/ControlRspDuo.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rspDuo/ControlRspDuoTuner2.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rspDuo/RspDuoTuner1Controller.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rspDuo/RspDuoTuner1Editor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rspDuo/RspDuoTuner2Controller.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rspDuo/RspDuoTuner2Editor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rspDx/RspDxTunerController.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rspDx/RspDxTunerEditor.java
Closes #1473 
Adds IF AGC Control for RSP tuners and Power Overload indication.  
Reverts change to default MacOS library location in API.
=> #1473 RSP Tuners - Provide IF AGC Control & Power Overload Indicators

src/main/java/io/github/dsheirer/source/tuner/airspy/AirspyTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/fcd/proV1/FCD1TunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/fcd/proplusV2/FCD2TunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/hackrf/HackRFTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/recording/RecordingTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/rtl/RTL2832UnknownTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/rtl/e4k/E4KTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/rtl/r820t/R820TTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rsp1/Rsp1TunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rsp1a/Rsp1aTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rsp2/Rsp2TunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rspDuo/RspDuoTuner1Editor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rspDuo/RspDuoTuner2Editor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rspDx/RspDxTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/ui/TunerEditor.java
#1489 SDRPlay RSP tuner editors now lock/unlock sample rate combo when sourcing channels.
=> #1489 SDRPlay RSP Tuners - Sample Rate Control Lock/Unlocking on Channel Sourcing

src/main/java/io/github/dsheirer/util/Dispatcher.java
Closes #1491 
Adds diagnostic logging to dispatcher to support troubleshooting polyphase channel manager's dispatch thread being blocked.
=> #1491 Polyphase Channellizer - Add Diagnostic Logging to Dispatcher Thread

src/main/java/io/github/dsheirer/audio/codec/mbe/JmbeAudioModule.java
#1498 Updates JMBE audio module to retain class reference instead of reflectively loading the class each time for a new instance.  Reduces pressure on both the class loader and the garbage collector.
=> #1498 JMBE Audio Class Loading - Memory Leak

build.gradle, src/main/java/io/github/dsheirer/buffer/DcCorrectionManager.java, src/main/java/io/github/dsheirer/buffer/airspy/hf/AirspyHfNativeBuffer.java, src/main/java/io/github/dsheirer/buffer/airspy/hf/AirspyHfNativeBufferFactory.java, src/main/java/io/github/dsheirer/source/tuner/TunerClass.java, src/main/java/io/github/dsheirer/source/tuner/TunerFactory.java, src/main/java/io/github/dsheirer/source/tuner/TunerType.java, src/main/java/io/github/dsheirer/source/tuner/airspy/hf/AirspyHfSampleRate.java, src/main/java/io/github/dsheirer/source/tuner/airspy/hf/AirspyHfTuner.java, src/main/java/io/github/dsheirer/source/tuner/airspy/hf/AirspyHfTunerConfiguration.java, src/main/java/io/github/dsheirer/source/tuner/airspy/hf/AirspyHfTunerController.java, src/main/java/io/github/dsheirer/source/tuner/airspy/hf/AirspyHfTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/airspy/hf/Attenuation.java, src/main/java/io/github/dsheirer/source/tuner/airspy/hf/BoardId.java, src/main/java/io/github/dsheirer/source/tuner/airspy/hf/Request.java, src/main/java/io/github/dsheirer/source/tuner/airspy/hf/Response.java, src/main/java/io/github/dsheirer/source/tuner/configuration/TunerConfiguration.java, src/main/java/io/github/dsheirer/source/tuner/manager/TunerManager.java, src/main/java/io/github/dsheirer/source/tuner/ui/DiscoveredTunerModel.java, src/main/java/io/github/dsheirer/source/tuner/usb/USBTunerController.java, src/main/java/io/github/dsheirer/util/ByteUtil.java
Adds support for airspy hf+/discovery tuners.
Notes: 
* Only the 912kHz sample rate is supported.  Unable to use other rates advertised by the device during development tesing.
* AGC/LNA/Attenuation controls are exposed but they don't seem to change any behavior on the tuner. 
Closes #1455
=> #1455 Add Airspy HF+/Discovery Tuner Support

src/main/java/io/github/dsheirer/audio/playback/AudioOutput.java, src/main/java/io/github/dsheirer/gui/playlist/alias/identifier/TalkgroupRangeEditor.java
#648 Resolves issue with audio panel sometimes displaying stale metadata that doesn't clear until the next audio segment is loaded.
=> #648 Audio Panel Stuck Metadata

src/main/java/io/github/dsheirer/gui/dmr/DMRRecordingViewer.java, src/main/java/io/github/dsheirer/module/decode/dmr/DMRDecoderState.java, src/main/java/io/github/dsheirer/module/decode/dmr/DMRMessageFramer.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/DataMessageWithLinkControl.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/csbk/motorola/CapacityPlusSiteStatus.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/lc/LCMessageFactory.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/lc/LCOpcode.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/lc/full/motorola/CapacityPlusEncryptedVoiceChannelUser.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/lc/full/motorola/CapacityPlusGroupVoiceChannelUser.java
Updates DMR Cap+ site status and other messages with corrections and enhancements.
=> #1556 DMR Capacity Plus parsing enhancements.

src/main/java/io/github/dsheirer/source/tuner/sdrplay/RspTunerConfiguration.java
Possible fix for RSP1 tuners resetting configuration on strartup
Multiple users reported that RSP tuner configurations are not saving, or resetting to default on startup. 
Andrew provided a java error:
```
TunerConfigurationManager - Error loading tuner configuration file  [22MB/80MB 28%]
com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'Rsp1TunerConfiguration' as a subtype of `io.github.dsheirer.source.tuner.configuration.TunerConfiguration`: known type ids = [airspyTunerConfiguration, e4KTunerConfiguration, fcd1TunerConfiguration, fcd2TunerConfiguration, hackRFTunerConfiguration, r820TTunerConfiguration, recordingTunerConfiguration, rsp1aTunerConfiguration, rsp2TunerConfiguration, rspDuoTuner1Configuration, rspDuoTuner2Configuration, …
```
=> Possible fix for RSP config not saving

src/main/java/io/github/dsheirer/module/decode/am/AMDecoder.java
Closes #1548 
Reduces default decoder AF gain by 40% to resolve issue with distorted audio from local strong aircraft transmissions.
=> #1548 Reduce AM Decoder AF Gain

src/main/java/io/github/dsheirer/alias/AliasModel.java, src/main/java/io/github/dsheirer/gui/playlist/alias/AliasConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/radioreference/SystemTalkgroupSelectionEditor.java
Closes #1547 
Updates playlist alias editor to make add/delete operations more efficient to possibly resolve issue where playlist may not be saving when adding or removing large chunks of aliases.
=> #1547 Playlist Fails To Save When Add/Delete Large Quantity of Aliases

src/main/java/io/github/dsheirer/source/tuner/manager/CenterFrequencyCalculator.java
Closes #1558 
Resolves issue where heterodyne channelizer allows tuning a set of channels that exceed the tuner's bandwidth.
=> #1558 Heterodyne Channelizer Allows Channels Exceeding Tuner Bandwidth

src/main/java/io/github/dsheirer/audio/AudioModule.java, src/main/java/io/github/dsheirer/gui/playlist/channel/NBFMConfigurationEditor.java, src/main/java/io/github/dsheirer/module/decode/DecoderFactory.java, src/main/java/io/github/dsheirer/module/decode/nbfm/DecodeConfigNBFM.java
Closes #1568 
Updates NBFM decoder configuration so user can enable/disable high-pass filter option in the audio module to effect audio playback and audio recording of the demodulated audio.  Disabling the filter allows recording of DC and sub-audible signalling that may be present in the demodulated audio (e.g. LTR or squelching signalling).
=> #1568 NBFM Decoder Allows User To Enable/Disable Audio High-Pass Filter

src/main/java/io/github/dsheirer/identifier/dcs/DCSIdentifier.java, src/main/java/io/github/dsheirer/module/decode/DecoderFactory.java, src/main/java/io/github/dsheirer/module/decode/DecoderType.java, src/main/java/io/github/dsheirer/module/decode/analog/AnalogDecoderState.java, src/main/java/io/github/dsheirer/module/decode/dcs/DCSCode.java, src/main/java/io/github/dsheirer/module/decode/dcs/DCSDecoder.java, src/main/java/io/github/dsheirer/module/decode/dcs/DCSDecoderState.java, src/main/java/io/github/dsheirer/module/decode/dcs/DCSMessage.java, src/main/java/io/github/dsheirer/module/decode/dcs/DCSMessageFilter.java, src/main/java/io/github/dsheirer/module/decode/fleetsync2/Fleetsync2DecoderState.java, src/main/java/io/github/dsheirer/protocol/Protocol.java
Closes #1573 
Adds Digital Coded Squelch (DCS) auxiliary decoder support.
=> #1573 Digital Coded Squelch (DCS) Auxiliary Decoder

src/main/java/io/github/dsheirer/module/decode/dmr/DMRTrafficChannelManager.java, src/main/java/io/github/dsheirer/module/decode/mpt1327/MPT1327TrafficChannelManager.java, src/main/java/io/github/dsheirer/module/decode/p25/P25TrafficChannelManager.java
Closes #1575 
Updates traffic channel names to be 'T-' concatenated with the parent control channel name from the channel configuration.
=> #1575 Traffic Channel Naming

src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DataUnitDetector.java
Closes #1579 
Resolves issue with array index out of bounds error generated in P25 Phase 1 decoders where the Dibit circular buffer attempts to write a dibit past the length of the array.  Issue likely occurs when a partial/incomplete put operation adds a dibit and increments the buffer pointer but the thread is interrupted prior to wrapping the buffer pointer.  When the next runnable iteration executes, the pointer is pointing past the end of the buffer.  Updates the code to check the pointer both before and after the put operation.
=> #1579 P25 Phase 1 Decoder - 

src/main/java/io/github/dsheirer/audio/broadcast/rdioscanner/RdioScannerConfiguration.java, src/main/java/io/github/dsheirer/gui/playlist/streaming/RdioScannerEditor.java
Closes #1581 
Updates Rdio Scanner configuration editor to automatically append the 'api/call-upload' path to the end of the protocol and host value provided by the user.  Sets the host default value to 'http://localhost' but allows the user to overwrite.
=> #1581 Rdio Scanner Streaming Configuration Editor - Host URL Path

src/main/java/io/github/dsheirer/source/tuner/manager/HeterodyneChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/RspNativeBuffer.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/RspNativeBufferFactory.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/RspSampleRate.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/RspTunerController.java
Closes #1563 
Updates RSP tuner to produce sample buffers with optimal power-of-2 length to enable downstream vectorized operations.
=> #1563 RSP Tuners Don't Work With Heterodyne Channelizer

src/main/java/io/github/dsheirer/dsp/psk/PSKDemodulator.java, src/main/java/io/github/dsheirer/module/decode/Decoder.java, src/main/java/io/github/dsheirer/module/decode/dmr/DMRDecoder.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1Decoder.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DecoderC4FM.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DecoderLSM.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/P25P2Decoder.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/P25P2DecoderHDQPSK.java
Closes #1584 
Updates DMR & P25 decoders to stop processing residual samples from the current buffer after a traffic channel shutdown has been signalled.
=> #1584 Traffic Channel Shutdown - Residual Buffer Samples Processing Related Errors

.idea/misc.xml, src/main/java/io/github/dsheirer/source/tuner/sdrplay/RspNativeBufferFactory.java
Closes #1590 
Resolves issue with RSP tuners generating too many native buffers causing excessive memory consumption
=> #1590 RSP Tuners - Excessive Buffer Generation - Out of Memory

src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1MessageFramer.java
Close #1586 
Resolves issue in P25 message framer where after transmitting the current message the mDataUnitId is set to null and this causes an NPE when subsequent code is executed prior to shutdown of the channel.
=> #1586 P25P1 Message Framer NPE

src/main/java/io/github/dsheirer/module/decode/event/ClearableHistoryModel.java
Closes #1603 
Resolves issue with de-duplicating events to allow call duration values to display correctly and minimize the quantity of duplicate events.
=> #1603 De-Duplicate Call Events

src/main/java/io/github/dsheirer/module/decode/event/DecodeEventPanel.java
#1604 Resolves issue with event panel UI layout creating excess space between history management panel and events table.
=> #1604 Event Panel UI Layout Creates Excess Space On Resizing

src/main/java/io/github/dsheirer/alias/AliasFactory.java, src/main/java/io/github/dsheirer/alias/AliasList.java, src/main/java/io/github/dsheirer/alias/id/AliasID.java, src/main/java/io/github/dsheirer/alias/id/AliasIDType.java, src/main/java/io/github/dsheirer/alias/id/dcs/Dcs.java, src/main/java/io/github/dsheirer/gui/playlist/alias/AliasItemEditor.java, src/main/java/io/github/dsheirer/gui/playlist/alias/identifier/DcsEditor.java, src/main/java/io/github/dsheirer/gui/playlist/alias/identifier/IdentifierEditorFactory.java, src/main/java/io/github/dsheirer/identifier/Form.java, src/main/java/io/github/dsheirer/module/decode/dcs/DCSCode.java, src/main/java/io/github/dsheirer/module/decode/dcs/DCSMessage.java
Closes #1612 
Enhance aliasing to support Digital Coded Squelch (DCS) tones to enable listen, record and streaming based on the decoded DCS value.
=> #1612 Enhance aliasing to support DCS tones

src/main/java/io/github/dsheirer/source/tuner/manager/TunerManager.java
Coses #1628 
Handle libusb errors during get device list operation and retry with increased logging during error code -99 to determine what causes this error condition, primarily on some Linux systems.
=> #1628 LibUsb Error -99 During Device Discovery

src/main/java/io/github/dsheirer/module/decode/dmr/message/data/lc/LCMessageFactory.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/lc/LCOpcode.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/lc/full/hytera/HyteraArc4EncryptionParameters.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/lc/full/motorola/MotorolaArc4EncryptionParameters.java
#1630 Updates ARC4 FLC encryption parameters message to detect and parse both Hytera & Motorola message formats.
=> #1630 DMR FLC ARC4/EP Encryption Parameters

src/main/java/io/github/dsheirer/module/decode/dmr/DMRDecoderState.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/packet/PacketSequenceMessageFactory.java, src/main/java/io/github/dsheirer/module/decode/ip/hytera/rrs/HyteraRrsPacket.java, src/main/java/io/github/dsheirer/module/decode/ip/hytera/sds/DestinationId.java, src/main/java/io/github/dsheirer/module/decode/ip/hytera/sds/HyteraTokenHeader.java, src/main/java/io/github/dsheirer/module/decode/ip/hytera/sds/HyteraTokenType.java, src/main/java/io/github/dsheirer/module/decode/ip/hytera/sds/RrsMessageHeader.java, src/main/java/io/github/dsheirer/module/decode/ip/hytera/sds/RrsUnknown.java, src/main/java/io/github/dsheirer/module/decode/ip/hytera/sds/TmsMessageHeader.java, src/main/java/io/github/dsheirer/module/decode/p25/identifier/ipv4/DMRIpAddress.java
Closes #1641 
Adds support for Hytera Radio Registration Service (RRS) defined short data packet parsing.
=> #1641 DMR Hytera RRS packet support.

src/main/java/io/github/dsheirer/bits/BinaryMessage.java
Closes #1661 
Resolves issue with parsing of DMR embedded GPS latitude and longitude values.
=> #1661 DMR Talker GPS Lat/Long Values Incorrect

src/main/java/io/github/dsheirer/module/decode/dmr/DMRDecoderState.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/lc/full/GPSInformation.java
Closes #1648 
Resolves issue with plotting DMR embedded GPS and LRRP positions.
=> #1648 DMR Embedded GPS & LRRP Plotting

src/main/java/io/github/dsheirer/gui/JavaFxWindowManager.java, src/main/java/io/github/dsheirer/gui/SDRTrunk.java, src/main/java/io/github/dsheirer/gui/viewer/DmrViewer.java, src/main/java/io/github/dsheirer/gui/viewer/P25P1Viewer.java, src/main/java/io/github/dsheirer/gui/viewer/RecordingViewer.java, src/main/java/io/github/dsheirer/gui/viewer/ViewRecordingViewerRequest.java
Closes #1668 
Updates message recording (.bits) viewer to support both DMR and P25 Phase 1.
=> #1668 Message Recording Viewer - P25P1 Support

src/main/java/io/github/dsheirer/module/decode/dmr/audio/DMRAudioModule.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/lc/full/motorola/CapacityPlusVoiceChannelUser.java
#1670 Resolves issue with missing audio segments for some DMR Cap+ call events.
Moto Group Voice Channel User message was changed to no longer extend from AbstractVoiceChannelUser message which caused the DMR audio module to no longer recognized these as call-indicator events.
=> #1670 Missing Audio Segments - DMR Cap+

src/main/java/io/github/dsheirer/module/decode/analog/DecodeConfigAnalog.java, src/main/java/io/github/dsheirer/module/decode/nbfm/DecodeConfigNBFM.java
Closes #1650 
Adds 7.5 kHz channel bandwidth option for FM channels to support narrow band railroad channels.
=> #1650 Adds 7.5 kHz channel bandwidth option for FM channels.

src/main/java/io/github/dsheirer/source/tuner/TunerFactory.java, src/main/java/io/github/dsheirer/source/tuner/configuration/TunerConfiguration.java, src/main/java/io/github/dsheirer/source/tuner/rtl/RTL2832TunerConfiguration.java, src/main/java/io/github/dsheirer/source/tuner/rtl/RTL2832TunerController.java, src/main/java/io/github/dsheirer/source/tuner/rtl/e4k/E4KTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/rtl/r8x/R8xEmbeddedTuner.java, src/main/java/io/github/dsheirer/source/tuner/rtl/r8x/R8xTunerConfiguration.java, src/main/java/io/github/dsheirer/source/tuner/rtl/r8x/R8xTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/rtl/r8x/r820t/R820TEmbeddedTuner.java, src/main/java/io/github/dsheirer/source/tuner/rtl/r8x/r820t/R820TTunerConfiguration.java, src/main/java/io/github/dsheirer/source/tuner/rtl/r8x/r828d/R828DEmbeddedTuner.java, src/main/java/io/github/dsheirer/source/tuner/rtl/r8x/r828d/R828DTunerConfiguration.java
Closes #1643 
* Adds support for RTL2832 with embedded R828D tuner and RTL-SDR.com V4 dongles.
* Introduces Bias-T support for all RTL2832 dongles.
=> #1643 RTL2832/R828D aka RTL-SDR V4 Dongle & Bias-T Support

src/main/java/io/github/dsheirer/source/tuner/TunerFactory.java, src/main/java/io/github/dsheirer/source/tuner/configuration/TunerConfiguration.java, src/main/java/io/github/dsheirer/source/tuner/rtl/RTL2832TunerConfiguration.java, src/main/java/io/github/dsheirer/source/tuner/rtl/RTL2832TunerController.java, src/main/java/io/github/dsheirer/source/tuner/rtl/fc0013/FC0013EmbeddedTuner.java, src/main/java/io/github/dsheirer/source/tuner/rtl/fc0013/FC0013TunerConfiguration.java, src/main/java/io/github/dsheirer/source/tuner/rtl/fc0013/FC0013TunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/rtl/r8x/R8xEmbeddedTuner.java, src/main/java/io/github/dsheirer/source/tuner/rtl/r8x/r820t/R820TEmbeddedTuner.java, src/main/java/io/github/dsheirer/source/tuner/rtl/r8x/r828d/R828DEmbeddedTuner.java, src/main/java/io/github/dsheirer/source/tuner/usb/USBTunerController.java
Closes #1687 
Adds support for RTL2832 with embedded FC0013 tuner.
=> Support For RTL2832 With Embedded FC0013 Tuner

src/main/java/io/github/dsheirer/dsp/filter/channelizer/ComplexPolyphaseChannelizerM2.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelManager.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/output/ChannelOutputProcessor.java, src/main/java/io/github/dsheirer/record/binary/BinaryRecorder.java, src/main/java/io/github/dsheirer/record/wave/ComplexSamplesWaveRecorder.java, src/main/java/io/github/dsheirer/record/wave/NativeBufferWaveRecorder.java, src/main/java/io/github/dsheirer/source/tuner/channel/HalfBandTunerChannelSource.java, src/main/java/io/github/dsheirer/source/tuner/channel/PassThroughChannelSource.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/SDRplay.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/callback/CallbackFunctions.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/callback/DeviceEventAdapter.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/callback/StreamCallbackAdapter.java, src/main/java/io/github/dsheirer/util/Dispatcher.java
Closes #1694 
Resolves memory leak in SDRPlay RSP tuner implementation.  Sample stream and event callback functions were using a global arena for memory allocation where memory was not being de-allocated.  Changed to on-demand arena creation and deterministic memory de-allocation.  
Also, when using a reduced sample rate from the RSP tuner, the dispatcher was not keeping up with the inbound sample buffer rate, resulting in a buildup of RSP native sample buffers over time and causing growing audio delays with broken/stilted audio during playback.
=> #1694 SDRPlay RSP Memory Leak & Audio Playback Delays

src/main/java/io/github/dsheirer/gui/control/IntegerTextField.java
Closes #1673 
Updates broadcastify call streaming config editor's where the original default value of 0 causes field to be uneditable depending on where in the field you click, either to the left or the right of the default zero value.  When the caret/cursor is to the right of the zero, it blocks any further typing because any system ID is not allowed to start with a zero or zero-prefixed value.
Removed the zero default value and set the field to empty/null.
=> #1673 Broadcastify Call Streaming Config Editor - Can't Edit System ID

src/main/java/io/github/dsheirer/gui/control/IntegerTextField.java, src/main/java/io/github/dsheirer/gui/playlist/streaming/StreamingEditor.java
Closes #1665 
Add option to refresh available streams from broadcastify in playlist editor's streaming tab.
=> #1665 Refresh Broadcastify Streams In Playlist Editor

src/main/java/io/github/dsheirer/gui/playlist/channel/AMConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/ChannelConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/ChannelConfigurationEditorFactory.java, src/main/java/io/github/dsheirer/gui/playlist/channel/ChannelEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/DMRConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/IFilterProcessor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/LTRConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/LTRNetConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/MPT1327ConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/NBFMConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/P25P1ConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/P25P2ConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/PassportConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/UnknownConfigurationEditor.java
Closes #1653 
Playlist channel edits with applied filter no longer produces ArrayIndexOutOfBounds error
=> #1653 Playlist Channel Edits With Applied Filter Produces Error

build.gradle
Closes #1651 
Increment version to 0.6.0 Beta 4
Add instructions to build.gradle for version naming conventions.
=> #1651 Version 0.6.0 Beta 4 and Version Naming Conventions

src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/Version.java
Partially addresses #1644 by updating sdrtrunk to consider API version 3.12 as a supported version.
=> #1644 SDRPlay API Version 3.12 For Mac OSX

.github/workflows/nightly.yml, build.gradle, gradle.properties
Closes #1706 
Creates a Github action to build sdrtrunk application for each target OS and upload the artifacts to the 'nightly' release tag.
=> #1706 Github Action For Nightly Releases

.github/workflows/gradle.yml, .github/workflows/nightly.yml, src/main/java/io/github/dsheirer/properties/SystemProperties.java
Closes #1709 
Adds build timestamp info to 
* build information file that is added as a release asset/artifact
* main application title bar
=> #1709 Nightly Release Build Timestamp Info

src/main/java/io/github/dsheirer/audio/broadcast/rdioscanner/RdioScannerBroadcaster.java, src/main/java/io/github/dsheirer/audio/broadcast/rdioscanner/RdioScannerBuilder.java
This addresses the issue in the recently closed #1620 where Rdio-Scanner is expecting an explicit filename to be set in the upload.
=> Explicitly send filename to Rdio-Scanner.

src/main/java/io/github/dsheirer/gui/playlist/alias/AliasConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/alias/AliasItemEditor.java, src/main/java/io/github/dsheirer/source/tuner/rtl/r8x/r828d/R828DEmbeddedTuner.java
Closes #968 
Resolves issue with clearing alias ID overlap state when the user edits the alias to correct the overlap.
=> #968 Playlist Alias Editor - Clear Overlap Error Warning Once Resolved

src/main/java/io/github/dsheirer/module/decode/p25/phase2/P25P2DecoderState.java
Closes #732 
Resolves P25P2 call events sometimes missing FROM radio ID even though the ID was decoded.
=> #732 P25 Phase 2 - FROM ID Updated For Call Event Logging

src/main/java/io/github/dsheirer/source/tuner/rtl/r8x/R8xEmbeddedTuner.java
Closes #1715 
Resolves issue of using both legacy and new V4 RTL2832 dongles at same time causes errant tuning behavior on the first tuner that gets initialized.  
Removed static qualifier from VCO reference value so that each tuner is allowed to initialize independently/correctly.
=> #1715 RTL2832 Tuner Issue When Using V4 Dongle With Other R820T Tuners

src/main/java/io/github/dsheirer/controller/channel/ChannelProcessingManager.java, src/main/java/io/github/dsheirer/source/tuner/rtl/r8x/R8xEmbeddedTuner.java
Closes #1681 
Resolves issue where audio recordings have incorrect system and site labels in metadata.  Adds synchronized to channel processing manager's start channel request method to ensure that each channel is configured and started sequentially to avoid chance that simultaneous traffic channel grants occurring across two separate systems get inter-mingled on configuration and startup.
=> #1681 Audio Recorder Mixing Up System and Site When Decoding Multiple Systems 

src/main/java/io/github/dsheirer/gui/JavaFxWindowManager.java, src/main/java/io/github/dsheirer/preference/javafx/JavaFxPreferences.java
Closes #1619 
Resolves issue where JavaFX window size and placement might show minimized after application is started and an initial JavaFX window is opened and then closed, where it impacted subsequent JavaFX window openings.  Corrects issue where JavaFX stage monitors were not being registered correctly, so that they could be deregistered prior to application shutdown.
=> #1619 JavaFX Windows Show Minimized

src/main/java/io/github/dsheirer/gui/playlist/radioreference/AgencyEditor.java, src/main/java/io/github/dsheirer/gui/playlist/radioreference/AgencyFrequencyEditor.java, src/main/java/io/github/dsheirer/gui/playlist/radioreference/CountyAgency.java, src/main/java/io/github/dsheirer/gui/playlist/radioreference/RadioReferenceEditor.java
Closes #1635 
This solves the problem of frequencies tied to the main county page in RadioReference not showing up in the list of frequencies available to import. I'm doing this via a new subclass called `CountyAgency` which acts like an agency, but gets the frequency categories from the county instead of an agency. It will always show up first in the UI, like so:
For counties with a very large number of categories (and likely subcategories), it will default to showing the first category in the list, instead of trying to show all the frequencies at once (which I've found to be extremely slow):
On other smaller counties though, it will have the normal `(All)` selection.
=> #1635 Add a special county agency to show all county freqs without an agency

.idea/misc.xml, src/main/java/io/github/dsheirer/gui/SDRTrunk.java, src/main/java/io/github/dsheirer/properties/SystemProperties.java
#1726 On startup, application no longer auto-creates SDRTrunk folder and system properties in user's home directory when user has changed the application root in the user preferences.
=> #1726 Don't Auto-Create App Root In User Home Directory Once Changed

src/main/java/io/github/dsheirer/gui/JavaFxWindowManager.java
#1619 JavaFX windows restore to previous size on view.
=> #1619 JavaFX Windows Restore to Previous Size/Location On View Request

src/main/java/io/github/dsheirer/gui/JavaFxWindowManager.java, src/main/java/io/github/dsheirer/gui/SDRTrunk.java, src/main/java/io/github/dsheirer/gui/preference/directory/DirectoryPreferenceEditor.java, src/main/java/io/github/dsheirer/monitor/ResourceMonitor.java, src/main/java/io/github/dsheirer/monitor/StatusBox.java, src/main/java/io/github/dsheirer/monitor/StatusPanel.java, src/main/java/io/github/dsheirer/preference/directory/DirectoryPreference.java
Closes #1731 
Adds application status bar with progress indicators for CPU, memory and disk space (event logs / recordings) usage.  Updates user preferences to include threshold settings in the directories editor for max size for event logs and recordings.
=> #1731 Application Status Bar (cpu/memory/disk space).

src/main/java/io/github/dsheirer/audio/broadcast/rdioscanner/RdioScannerBroadcaster.java, src/main/java/io/github/dsheirer/audio/broadcast/rdioscanner/RdioScannerBuilder.java
I was running into some weird issues with my proxy that was processing Rdio scanner API calls, it turns out that SDRTrunk doesn't send a valid HTTP request, so not all servers can process it correctly. There cannot be two content type headers, so I'm removing the `audio/mpeg` one as it's able to be derived from the `.mp3` filename in Rdio scanner itself. Additionally, there was an extra space in the multipart form filename syntax, which may also cause some issues.
I've verified that the changes work fine with Rdio scanner.
=> Fix Rdio Scanner API call to comply with HTTP standards

build.gradle
#1733 Updates gradle build script to explicitly include the java.management module.  This was causing a NoClassDefFoundException for the ManagementFactory class.
=> #1733 Java Module Missing (java.management)

src/main/java/io/github/dsheirer/gui/playlist/radioreference/SystemEditor.java
Closes #1735 
Adds support for county ID with sentinel value of 99999 to indicate county unknown for sites of a system.
=> #1735 Radio Reference API - Temporary Site With County ID 99999 - Unknown Location

src/main/java/io/github/dsheirer/alias/AliasFactory.java, src/main/java/io/github/dsheirer/alias/AliasList.java, src/main/java/io/github/dsheirer/alias/id/AliasID.java, src/main/java/io/github/dsheirer/alias/id/AliasIDType.java, src/main/java/io/github/dsheirer/alias/id/radio/P25FullyQualifiedRadio.java, src/main/java/io/github/dsheirer/alias/id/talkgroup/P25FullyQualifiedTalkgroup.java, src/main/java/io/github/dsheirer/gui/playlist/alias/AliasItemEditor.java, src/main/java/io/github/dsheirer/gui/playlist/alias/identifier/IdentifierEditorFactory.java, src/main/java/io/github/dsheirer/gui/playlist/alias/identifier/P25FullyQualifiedRadioIdEditor.java, src/main/java/io/github/dsheirer/gui/playlist/alias/identifier/P25FullyQualifiedTalkgroupEditor.java, src/main/java/io/github/dsheirer/identifier/Form.java, src/main/java/io/github/dsheirer/record/wave/AudioMetadataUtils.java
Closes #1188 
Adds support for aliasing of P25 fully qualified (wacn + system + id) radio and talkgroup identifiers.
Two new menu options are added in the playlist editor for adding fully qualified radio and talkgroup alias identifiers to an alias.
This should enable correct aliasing of these values in recording, streaming, and playback/display.
=> #1188 APCO25 (ISSI) Fully Qualified Radio & Fully Qualified Talkgroup Aliasing

src/main/java/io/github/dsheirer/source/tuner/sdrplay/RspTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/parameter/control/AgcMode.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rsp1/Rsp1TunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rsp1a/Rsp1aTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rsp2/Rsp2TunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rspDuo/RspDuoTuner1Editor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rspDuo/RspDuoTuner2Editor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rspDx/RspDxTunerEditor.java
Closes #1753 
Changes tuner editors to use toggle button for IF AGC mode and updates enum lookup to always return either ENABLE or DISABLE.  Deprecates 3x enum values as no longer supported.
=> #1753 SDRPlay - Remove Deprecated AGC Modes

src/main/java/io/github/dsheirer/module/decode/dmr/message/type/Vendor.java
=> #1760 Update DMR vendor enumeration.

src/main/java/io/github/dsheirer/audio/DuplicateCallDetector.java, src/main/java/io/github/dsheirer/audio/broadcast/AudioStreamingManager.java, src/main/java/io/github/dsheirer/audio/broadcast/PatchGroupStreamingOption.java, src/main/java/io/github/dsheirer/audio/codec/mbe/MBECallSequenceConverter.java, src/main/java/io/github/dsheirer/gui/preference/PreferenceEditorFactory.java, src/main/java/io/github/dsheirer/gui/preference/UserPreferencesEditor.java, src/main/java/io/github/dsheirer/gui/preference/call/CallManagementPreferenceEditor.java, src/main/java/io/github/dsheirer/preference/UserPreferences.java, src/main/java/io/github/dsheirer/preference/duplicate/CallManagementPreference.java, src/main/java/io/github/dsheirer/record/AudioSegmentRecorder.java
Closes #1772 
Adds preference for patch group streaming to stream patch group calls as either:
1. Patch group, or 
2. Each individual talkgroup or radio that forms the patch group.
=> 1772 Patch Group Streaming Preference (Patch Group vs Individual Talkgroups)

gradle.properties, src/main/java/io/github/dsheirer/module/decode/p25/phase2/message/mac/structure/l3harris/L3HarrisTalkerAlias.java
=> #1783 L3H P25P2 Talker Alias Guard Against Negative Length Aliases

src/main/java/io/github/dsheirer/audio/broadcast/openmhz/OpenMHzBroadcaster.java
=> #1791 Resolves OpenMHz Broadcaster Auto-Reconnection Issue

src/main/java/io/github/dsheirer/module/decode/p25/audio/P25P1CallSequenceRecorder.java, src/main/java/io/github/dsheirer/module/decode/p25/audio/P25P2CallSequenceRecorder.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/P25P2MessageProcessor.java
- Enhanced resync of ESS processor
- Re-Order of AbstractVoiceTimeslot processing
- Updated P25 MBE recorders to include synchronized encryption information (mainly to verify this fix worked)
Resync:
When a channel goes from "Call->Hangtime->PTT->Call", the first call is not guaranteed to end on a Voice-2 (See TIA-102.BBAC, Figure D-5). When the second call initiates, the ESS processor does not always start on the first Voice-4. Updated to reset ESS processor on PTT, END_PTT, HANGTIME, and IDLE.
Re-Order:
On a Voice-2 slice, the computed ESS applies to the following Voice slices. Re-ordered so that the current Voice-2 is processed before the computed ESS is processed.
=> P25-P2 Encryption Synchronization ReSync

src/main/java/io/github/dsheirer/module/decode/dmr/DMRDecoderState.java, src/main/java/io/github/dsheirer/module/decode/dmr/DMRMessageProcessor.java, src/main/java/io/github/dsheirer/module/decode/dmr/DMRTrafficChannelManager.java
Closes #1787 
Resolves issue with channel rotation and rest channel reallocation for DMR Capacity Plus systems.
=> #1787 DMR Cap+ Rest Allocation & Channel Rotation Issue

src/main/java/io/github/dsheirer/module/decode/p25/P25TrafficChannelManager.java
While monitoring a P25 Trunked system, the control channel will follow the preferred tuner conguration, however all of its traffic channels will not. They may use any Tuner.
The preferred tuner value is null for all the traffic channels, as they are not inherited from the parent.
TunerManaer received a null preferred tuner string value.
I manually set the preferred tuner from the parent in all references on the P25TrafficChannelManager class
This allows all voice channels associated with the P25 site to attempt to first use the preferred tuner.
Please test if this works
#1763
=> Inherit P25 Trunked Preferred Tuner To Traffic Channels

src/main/java/org/jdesktop/swingx/mapviewer/AbstractTileFactory.java
OSM Tileserver now supports TLSv1.3, so we can use this and get the benefits of the later version of the protocol
=> Use TLSv1.3 when connecting to OSM Tileserver

src/main/java/io/github/dsheirer/gui/control/DbPowerMeter.java
The power meter on the Channel tab is not wide enough to show the full 'Power (dB)' heading without truncation.
This PR increases the width of the power meter by 10 pixels
=> Fix dB power meter heading

src/main/java/io/github/dsheirer/source/tuner/sdrplay/RspTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rsp1/Rsp1TunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rsp1a/Rsp1aTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rsp1b/Rsp1bTunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rsp2/Rsp2TunerEditor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rspDuo/RspDuoTuner1Editor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rspDuo/RspDuoTuner2Editor.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/rspDx/RspDxTunerEditor.java
Closes #1821
Updates SDRPlay tuner editors to disable IF Gain slider when in auto mode.
=> #1821 SDRPlay IF Gain Adjustment

src/main/java/io/github/dsheirer/source/tuner/ui/DiscoveredTunerModel.java
Closes #1827
Resolves issue causing blank white screen when UI thread becomes dead-locked as the system tries to auto-remove a tuner that is in error state, while multiple channels are decoding and accessing the lock in the DiscoveredTunerModel.
=> #1827 UI Thread Deadlock From USB Hotplug Support Callback

src/main/java/io/github/dsheirer/gui/SDRTrunk.java, src/main/java/io/github/dsheirer/gui/preference/application/ApplicationPreferenceEditor.java, src/main/java/io/github/dsheirer/monitor/DiagnosticMonitor.java, src/main/java/io/github/dsheirer/preference/application/ApplicationPreference.java
Implents new health and diagnostic monitoring feature that will detect and log when deadlock thread error condition exists and notify the user to report the error and restart their application.
Added User Preference to the Application tab to enable/disable the feature.
Closes #1830
=> #1830 Health and Diagnostic Monitoring

src/main/java/io/github/dsheirer/dsp/oscillator/VectorRealOscillator.java
Resolves issue in MPT1327 decoder for users with vector SIMD enabled on a SIMD-512 machine.
The Correlator was unable to generate the reference samples for the specified sample period.  Updated code to generate a sampe array aligned to the architecture and then simply trucate the returned array size.
Closes #1826
=> #1826 SIMD-512 Systems Fail When Decoding MPT1327

src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/ldu/LDUMessage.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/timeslot/Voice2Timeslot.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/timeslot/Voice4Timeslot.java
P25 Voice Frame List concurrent modification error.  Added synchronized to method to deconflict when the audio module or the binary frame recorder can access the message list and not step on each other.  Issue was noted in the phase 2 module, but updated the phase 1 module as well to protect against the issue.
Closes #1810
=> #1810 P25 Voice Frame List Concurrent Modification Error

src/main/java/io/github/dsheirer/module/decode/dmr/DMRDecoderState.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/csbk/motorola/CapacityMaxAdvantageModeVoiceChannelUpdate.java
Resolved issue with CapMax Advantage mode producing call events with NO FREQUENY.  Updated the message to ensure all 4x timeslot channels get enriched wth frequency information.
Updated DMR decoder state to not log when an Unknown CSBK message containing a channel grant opcode gets processed.
=> #1834 CapMax Adv Mode Call Events With NO FREQUENCY

src/main/java/io/github/dsheirer/controller/channel/ChannelProcessingManager.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelManager.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelSource.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/output/ChannelOutputProcessor.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/output/OneChannelOutputProcessor.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/output/TwoChannelOutputProcessor.java, src/main/java/io/github/dsheirer/gui/channelizer/ChannelizerViewer.java, src/main/java/io/github/dsheirer/gui/channelizer/ChannelizerViewer2.java, src/main/java/io/github/dsheirer/gui/channelizer/HeterodyneChannelizerViewer.java, src/main/java/io/github/dsheirer/source/tuner/channel/HalfBandTunerChannelSource.java, src/main/java/io/github/dsheirer/source/tuner/channel/MultiFrequencyTunerChannelSource.java, src/main/java/io/github/dsheirer/source/tuner/channel/PassThroughChannelSource.java, src/main/java/io/github/dsheirer/source/tuner/channel/TunerChannelSource.java, src/main/java/io/github/dsheirer/source/tuner/manager/ChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/HeterodyneChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/PassThroughSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/PolyphaseChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/TunerManager.java, src/main/java/io/github/dsheirer/util/Dispatcher.java
Sets thread name for each channel stream dispatcher to include the channel configuration number, protocol, and frequency.
Closes #1837
=> #1837 Channel Stream Thread Naming

src/main/java/io/github/dsheirer/module/decode/dmr/DMRDecoderState.java
Clears DMR tone identifiers from call metadata when the decoder state is reset at the end of the call.
Closes #1839
=> #1839 DMR Tone Identifiers Don't Clear At Call End

src/main/java/io/github/dsheirer/module/decode/dmr/DMRDecoderState.java, src/main/java/io/github/dsheirer/module/decode/dmr/channel/DMRAbsoluteChannel.java
Updates decoder state to include channel and frequency in call events when it is missing.
Closes #1841
=> #1841 DMR Call Events Include Channel & Frequency

src/main/java/io/github/dsheirer/controller/channel/Channel.java, src/main/java/io/github/dsheirer/gui/power/ChannelPowerPanel.java, src/main/java/io/github/dsheirer/spectrum/OverlayPanel.java
Updates spectral display to correctly show all frequencies for a multi-frequency channel configuration.
Closes #1847
=> #1847 Spectral Display of Multi-Frequency Channel Configurations

src/main/java/io/github/dsheirer/spectrum/OverlayPanel.java
Resolves issue with coloration in rendering channel banners for multi-frequency channel configurations.
Closes #1852
=> #1852 Spectral Display Channel Banner Coloration

src/main/java/io/github/dsheirer/module/decode/dmr/DMRTrafficChannelManager.java
Resolves issue in DMR traffic channel manager that allowed a threading dead-lock to occur.  Removes synchronized method access since this method is already protected by the reentrant lock.
=> #1856 DMR Channel - Threading Deadlock

build.gradle, src/main/java/io/github/dsheirer/gui/playlist/radioreference/EnrichedSite.java, src/main/java/io/github/dsheirer/gui/playlist/radioreference/SiteEditor.java
Closes #1899 
Uses radio reference API version 18 and updates site editor to use new 'tdma_cc' flag to distinguish P25 Phase 2 FDMA vs TDMA control channel sites.
=> #1899 Radio Reference API V18 & Update Site Editor To Show TDMA CC Sites

src/main/java/io/github/dsheirer/module/decode/p25/P25TrafficChannelManager.java, src/main/java/io/github/dsheirer/source/tuner/TunerController.java, src/main/java/io/github/dsheirer/source/tuner/fcd/FCDTunerController.java, src/main/java/io/github/dsheirer/source/tuner/frequency/FrequencyController.java, src/main/java/io/github/dsheirer/source/tuner/manager/HeterodyneChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/PassThroughSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/PolyphaseChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/rtl/RTL2832TunerController.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/RspTunerController.java, src/main/java/io/github/dsheirer/source/tuner/usb/USBTunerController.java
=> #1876 Unifies Reentrant Lock Between Tuners and Frequency Controller.

src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/tsbk/harris/isp/UnknownHarrisISPMessage.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/tsbk/harris/osp/UnknownHarrisOSPMessage.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/tsbk/motorola/isp/UnknownMotorolaISPMessage.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/tsbk/motorola/osp/UnknownMotorolaOSPMessage.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/tsbk/standard/isp/UnknownISPMessage.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/tsbk/standard/osp/UnknownOSPMessage.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/P25P2DecoderState.java
Closes #1903 P25 Phase 2 audio - resolves 2-second chopped audio segments
=> #1903 P25 Phase 2 Audio Segment Chopping

src/main/java/io/github/dsheirer/map/MapPanel.java, src/main/java/io/github/dsheirer/map/PlottableEntityHistory.java, src/main/java/io/github/dsheirer/map/PlottableEntityModel.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/P25P2DecoderState.java
Closes #1924 
Resolves issue with talker GPS positions showing up in map panel as user identifiers.
Adds talker GPS location filtering to suppress redundant GPS position reports when it's the same location transmitted within 30 seconds of each other.
=> #1924 GPS Positions Listed as User Identifiers In Map Panel

src/main/java/io/github/dsheirer/source/tuner/TunerFactory.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/Version.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/device/DeviceFactory.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/device/DeviceType.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/parameter/composite/CompositeParametersFactory.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/parameter/device/DeviceParametersFactory.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/parameter/tuner/TunerParametersFactory.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/v3_14/sdrplay_api_h.java
Updates SDRPlay to support API version 3.15 and the new RSPdxR2 tuner.
Note: R2 tuner support (re)uses the existing RSPdx base classes.
=> #1916 SDRPlay API 3.15 and RSPdxR2 support.

src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/standard/LCConventionalFallback.java
Closes #1934 P25P1 conventional fallback message toString() output fixed.
=> #1934 P25P1 Conventional Fallback LC Message

src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DecoderState.java, src/main/java/io/github/dsheirer/source/tuner/usb/USBTunerController.java
Closes #1860 
Resolves USB transfer buffer (re)submit error tracking. Synchronizes the submit transfers method so that multi-threaded access doesn't cause accounting errors. Ignores LIBUSB_ERROR_BUSY when (re)submitting due to accounting errors. 
Removes several P25P1 unrecognized messaging loggers.
=> 1860 LibUsb Transfer Buffer Error Handling Enhancements

src/main/java/io/github/dsheirer/module/decode/p25/P25TrafficChannelManager.java
Closes #1952 
P25 Traffic Channel Manager now clears stale call events from the traffic channel event map so that multiple calls don't get aggregated.
=> #1952 P25 Traffic Channel Manager Aggregating Multiple Call Events Into One

src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DecoderState.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/P25P2DecoderState.java
Closes #1912 
P25 Patch Group details (ie the patched talkgroups or patched radios) no longer missing from Now Playing and recording and streaming metadata.
=> #1912 P25 Patch Group Details Missing In Now Playing and Streaming/Recording Metadata

src/main/java/io/github/dsheirer/properties/SystemProperties.java
Closes #1960.
Creates the application root folder (SDRTrunk) when it doesn't exist or on a fresh install.
=> #1960 Application Root Directory  Not Found On Fresh Install

src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/README, src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/SDRPlayLibraryHelper.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/v3_07/sdrplay_api_h.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/v3_08/sdrplay_api_h.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/v3_15/sdrplay_api_h.java
Closes #1964 
Mac OS issue when loading SDRPlay API native library from fully qualified path.
=> #1964 SDRPlay API Native Library on MacOS

build.gradle, src/main/java/io/github/dsheirer/alias/AliasList.java, src/test/java/io/github/dsheirer/alias/P25AliasTest.java, src/test/java/io/github/dsheirer/service/radioreference/RadioReferenceTest.java
Closes #1966 
Resolves issue where P25 aliases were not correctly matching when radio system is using fully qualified (FQ) talkgroup/radio values.
The matching behavior was supposed to match:
1) FQ identifier matches to FQ alias 
2) FQ identifier matches to Simple identifier alias using the locally assigned ID from the FQ identifier
3) FQ identifier locally assigned ID matches against radio or talkgroup range.
However, a code logic error was stopping at step 1.  Therefore any calls involving fully qualified users roaming onto the local system were not aliasing correctly. 
This issue likely impacted users that had simple aliases setup for the locally assigned radio or talkgroup values and those aliases were no longer matching once the fully qualified radio and talkgroup values were being …
=> #1966 P25 Aliases Not Correctly Matching Against Fully Qualified Radio & Talkgroup Values

src/main/java/io/github/dsheirer/audio/broadcast/BroadcastModel.java
Closes #1948 
Audio Stream starts are now spun off to a cached thread pool to prevent any initial stream connections from delaying the overall application startup.
=> #1948 Audio Streaming Startups On Separate Thread

src/main/java/io/github/dsheirer/gui/viewer/IdentifierCollectionViewer.java, src/main/java/io/github/dsheirer/identifier/radio/FullyQualifiedRadioIdentifier.java, src/main/java/io/github/dsheirer/identifier/talkgroup/FullyQualifiedTalkgroupIdentifier.java, src/main/java/io/github/dsheirer/module/decode/p25/P25TrafficChannelManager.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/P25P2DecoderState.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/message/mac/MacMessageFactory.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/message/mac/structure/motorola/MotorolaGroupRegroupTalkerAlias.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/message/mac/structure/motorola/MotorolaGroupRegroupTalkerAliasContinuation.java, src/main/java/io/github/dsheirer/preference/identifier/talkgroup/APCO25TalkgroupFormatter.java, src/main/java/io/github/dsheirer/source/tuner/frequency/FrequencyController.java
Closes #1977 
P25 FQSUID handling improvements.  
P25 fully qualified radio/talkgroup identifiers we're being flagged as invalid when ISSI patch assigned a local address/ID of zero.  
Changes format of FQSUID and FQTGID to use a value of zero for the local alias when the call type is an ISSI patch and suppress display of the 0 alias value.  If the identifier represents a roaming user, then the local address value is displayed with the FQSUID appended in parenthesis.
=> #1977 P25 FQSUID Improvements

src/main/java/io/github/dsheirer/audio/AudioSegment.java, src/main/java/io/github/dsheirer/audio/DuplicateCallDetector.java, src/main/java/io/github/dsheirer/module/decode/p25/identifier/encryption/APCO25EncryptionKey.java, src/main/java/io/github/dsheirer/module/decode/p25/reference/Encryption.java, src/main/java/io/github/dsheirer/preference/duplicate/CallManagementPreference.java, src/main/java/io/github/dsheirer/preference/duplicate/ICallManagementProvider.java, src/main/java/io/github/dsheirer/preference/duplicate/TestCallManagementProvider.java, src/test/java/io/github/dsheirer/audio/DuplicateCallDetectionTest.java
Closes #1939 
Enhances thread safety in the duplicate call detector.
Adds unit testing to test for common scenarios.
Adds checks for encrypted audio to remove audio segments that initially have decoded audio and then get flagged as encrypted with an encryption key to protect against scenarios where a call is simulcast with one call encrypted and the other call unencrypted, to avoid flagging as duplicate the unencrypted call audio.
=> #1939 Duplicate Call Detector Enhancements & Unit Tests

src/main/java/io/github/dsheirer/audio/broadcast/AbstractAudioBroadcaster.java, src/main/java/io/github/dsheirer/audio/broadcast/AudioStreamingBroadcaster.java, src/main/java/io/github/dsheirer/audio/broadcast/BroadcastState.java, src/main/java/io/github/dsheirer/audio/broadcast/ConfiguredBroadcast.java, src/main/java/io/github/dsheirer/audio/broadcast/icecast/IcecastHTTPAudioBroadcaster.java, src/main/java/io/github/dsheirer/audio/broadcast/icecast/IcecastTCPAudioBroadcaster.java, src/main/java/io/github/dsheirer/gui/playlist/streaming/StreamingEditor.java
- Add mechanism to persist failure reason while continuing to reconnect
- Add 'warning' attribute for failure conditions that may be temporary, but still need to be reported
- Add logging for failures
- Prevent possibly temporary server-side conditions from blocking reconnect attempts (fixes #1398)
- Detect icecast 2.4 auth failures
- Prevent generic errors from overriding existing error state
=> Improvements to icecast failure handling

src/main/java/io/github/dsheirer/alias/AliasList.java, src/test/java/io/github/dsheirer/alias/P25AliasTest.java
#1983 Reverts aliasing of fully qualified identifiers against locally assign ID or address values - must be an exact match to the fully qualified identifier.
=> #1983 Revert Aliasing of Fully Qualified Identifiers Against Local ID

src/main/java/io/github/dsheirer/map/PlottableEntityHistory.java, src/main/java/io/github/dsheirer/map/PlottableEntityModel.java, src/main/java/io/github/dsheirer/module/decode/event/PlottableDecodeEvent.java
Closes #1990 
Ignores GPS tracks with 0/0 location.
=> #1990 Ignores GPS positions with 0/0 latitude and longitude values.

src/main/java/io/github/dsheirer/gui/viewer/MessagePackage.java, src/main/java/io/github/dsheirer/gui/viewer/MessagePackageViewer.java, src/main/java/io/github/dsheirer/gui/viewer/MessagePackager.java, src/main/java/io/github/dsheirer/gui/viewer/MessageRecordingViewer.java, src/main/java/io/github/dsheirer/gui/viewer/P25P1Viewer.java, src/main/java/io/github/dsheirer/module/decode/p25/audio/P25P1AudioModule.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DecoderState.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/hdu/HDUMessage.java
Closes #1994 
P25 Phase1 missing subsequent calls audio when multiple conversations on the same traffic channel.
Fixed issue where sdrtrunk was not checking HDU and LDU2 encryption sequences as valid before assessing the encryption state of a call.  Updated P25P1 audio module to check the valid flag for both the HDU and the LDU2 encryption segment before assigning encryption state.  Now caches all LDU messages until encryption state is determined.
This was happening on at least Harris VHF systems due to what sdrtrunk was interpreting to be a partial/malformed Header Data Unit (HDU) being transmitted at the end of the first call audio, where the decoded HDU indicated an encrypted call.
=> #1994 P25 Phase1 Missing Subsequent Calls Audio When Multiple Conversants On Same Traffic Channel

src/main/java/io/github/dsheirer/audio/playback/AudioOutput.java
Closes #2006 
AudioOutput now requests a new source data line from the mixer when it detects that the line no longer accepts audio byte data.
=> #2006 AudioOutput Recreated Once It Fails To Accept Audio Samples For Playback

src/main/java/io/github/dsheirer/audio/DuplicateCallDetector.java, src/main/java/io/github/dsheirer/audio/broadcast/AudioStreamingManager.java, src/main/java/io/github/dsheirer/audio/playback/AudioOutput.java, src/main/java/io/github/dsheirer/audio/playback/AudioPlaybackManager.java, src/main/java/io/github/dsheirer/gui/preference/call/CallManagementPreferenceEditor.java, src/main/java/io/github/dsheirer/preference/UserPreferences.java, src/main/java/io/github/dsheirer/record/AudioRecordingManager.java, src/test/java/io/github/dsheirer/audio/broadcast/AudioStreamingManagerTest.java
#1973 Does not close the issue - only introduces an automated test.
Introduces JUnit Test for Patched Talkgroup Audio call streaming that tests streaming the audio as the individual patched group or broken up into the constituent patched talkgroups according to the user preferences setting for call management.
=> #1973 JUnit Test for Patched Talkgroup Audio Call Streaming

src/main/java/io/github/dsheirer/preference/UserPreferences.java
Closes #2016 Fixes code regression introduced in #1973 with null playback preferences.
=> #2016 Playback Preferences Null Error

src/main/java/io/github/dsheirer/module/decode/dmr/DMRDecoderState.java, src/main/java/io/github/dsheirer/module/decode/p25/P25TrafficChannelManager.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DecoderState.java
Closes #2018 P25 Phase 1 resolves issue where NowPlaying identifiers were flickering as they are removed and readded with each TDULC terminator message.
=> #2018 P25 Phase 1 Now Playing Flickering Identifiers

src/main/java/io/github/dsheirer/module/decode/p25/identifier/channel/APCO25Channel.java, src/main/java/io/github/dsheirer/module/decode/p25/identifier/channel/P25Channel.java
Closes #2020 
Resolves issue where P25 channel throws NPE when applying a null frequency band.
=> #2020 P25 channel null frequency band error.

src/main/java/io/github/dsheirer/audio/playback/AudioOutput.java
Closes #2022
Resolves issue when the audio output is reacquired it now also refreshes the mute and gain controls so that they work correctly in the UI.
=> #2022 Audio output reset now reacquires gain and mute controls.

src/main/java/io/github/dsheirer/gui/playlist/channel/ChannelConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/ChannelEditor.java
Closes #2030 
Enhances Playlist Editor with double-click on a channel row to auto-start channel.
=> #2030 Playlist Editor Double-Click Channel Start

src/main/java/io/github/dsheirer/audio/playback/AudioOutput.java
Closes #2032 
Audio output suppresses logging after 5 times when app can't get gain or mute controls for current audio output.
Note: this doesn't resolve the underlying issue of why is Java unable to get Gain/Mute controls from the reacquired audio output.  It's possible that those features are not supported on the audio output.
=> #2032 Audio Output Logs Failed Attempt To Update Gain/Mute Controls

src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/tsbk/harris/osp/L3HarrisGroupRegroupExplicitEncryptionCommand.java
Closes #2035 
Resolves issue where L3Harris is setting the MSB (high bit 24) in the regrouping message when the target address contains a talkgroup which should only be 16-bits long and this is causing incorrect talkgroup values to be included in the patch.
Updated the message to parse just 16-bits when the targate address is a talkgroup and the full 24-bit field when the target address is a simulselect radio.
=> #2035 P25P1 Harris Patched Talkgroup Values Incorrect

src/main/java/io/github/dsheirer/module/decode/dmr/message/data/lc/full/motorola/CapacityMaxVoiceChannelUser.java
Closes #2043 
DMR Tier 3 Capacity Max talkgroups were parsing incorrectly.
=> #2043 DMR Tier 3 Capacity Max Incorrect Talkgroup Values

src/main/java/io/github/dsheirer/gui/JavaFxWindowManager.java
Closes #2037 
JavaFX Windows Can't Be Shrunk.  
Reverts changes made under #1619 that was applying a min width and height to the window based on the last time that the user resized the window.  This had the effect of allowing windows to get bigger, but never allowing windows to get smaller than the last width/height values on previous application shutdown.
=> #2037 JavaFX Windows Can't Be Shrunken

src/main/java/io/github/dsheirer/audio/codec/mbe/JmbeAudioModule.java
Closes #2040 
Resets AMBE/IMBE audio codec after each call to prevent carryover of last audio frame from previous call.
=> #2040 Reset AMBE/IMBE Audio Codec After Each Call

src/main/java/io/github/dsheirer/map/TrackHistoryModel.java
Closes #2034 
Map plotted elements now include date in the location timestamp.
=> #2034 Map Plotted Elements Timestamp Includes Date

src/main/java/io/github/dsheirer/audio/playback/AudioOutput.java, src/main/java/io/github/dsheirer/channel/state/AbstractChannelState.java, src/main/java/io/github/dsheirer/channel/state/MultiChannelState.java, src/main/java/io/github/dsheirer/channel/state/SingleChannelState.java, src/main/java/io/github/dsheirer/controller/channel/ChannelProcessingManager.java
Closes #1992 
Resolves issue that was causing channels to be stuck in TEARDOWN state.
Issue appears to be that the Channel's processing flag was not being set during start processing and the request to shutdown the channel was checking the flag was set before proceeding with shutdown.
=> #1992 Traffic channels stuck in teardown.

src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DecoderState.java
Closes #2064 
Updates P25P1 decoder state to ensure TO/FROM identifiers are added to any Moto talker GPS event for correct plotting to the map.
=> #2064 Moto talker GPS event TO/FROM identifiers.

src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1MessageProcessor.java
Closes #2066 
P25 Phase 1 frequency band link control messages are now checked for valid CRC before being used.  This corrects an issue where the now playing channel metadata for simplex channels or manually entered traffic channels were showing wild/bad frequency values.
=> #2066 P25 Phase 1 Frequency Band Link Control Messages Checked For Valid CRC

src/main/java/io/github/dsheirer/module/decode/dmr/DMRDecoderState.java
Closes #2074 
DMR Capacity Max LRRP GPS positions sent to map now contain channel identifiers (alias list and system name).
=> #2074 DMR CapMax LRRP GPS Alias List

src/main/java/io/github/dsheirer/module/decode/dmr/message/type/SystemIdentityCode.java
Closes #2076 
Fixes issue where DMR CapMax Network and Site vales off by one in the System Identity Code parsing.
=> #2076 DMR CapMax Network and Site vales off by one.

src/main/java/io/github/dsheirer/audio/broadcast/icecast/IcecastTCPAudioBroadcaster.java
Closes #2078 
Expands verbose logging feature to include audio and metadata stream attempts for Broadcastify feed streams.
=> #2078 Broadcastify Feed Verbose Logging Includes Audio and Metadata

build.gradle
Closes #2081 
Adds libusb native libraries to support Windows aarch64 platforms.
Note: the new library bundles both the Windows and OSX native libraries for aarch64 where previously the OSX library was bundled in a separate jar.
=> #2081 Windows aarch64 libusb support.

src/main/java/io/github/dsheirer/audio/playback/AudioPlaybackManager.java
Closes #2086 
Audio Playback Manager can leak memory if audio queue processing thread is never started.
Changed the workflow to always start the audio segment queue processing thread and to use reentrant lock to protect access to the audio outputs.
=> #2086 Audio Playback Manager Memory Leak

gradle.properties, src/main/java/io/github/dsheirer/source/tuner/TunerFactory.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/device/DeviceStruct_v3_08.java
Closes #2102.
Logs when SDRPlay API getDevices method returns an unknown or unrecognized tuner type.
=> #2102 Log Unknown Tuners From SDRPlay API

src/main/java/io/github/dsheirer/edac/CRC16.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DecoderState.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/motorola/LCMotorolaTalkerAliasAssembler.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/motorola/MotorolaTalkerAliasComplete.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/P25P2DecoderState.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/message/mac/structure/motorola/MotorolaTalkerAliasAssembler.java
Closes #2105.
Adds CRC check to P25 talker aliases to ignore bad alias decodes.
=> #2105 P25 P1/2 Motorola Talker Alias CRC Check

src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DecoderState.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/LinkControlOpcode.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/LinkControlWordFactory.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/motorola/LCMotorolaFailsoft.java
This is broadcast on channels when a site is in failsoft operation (site controller has failed or too few channels are functional to operate in trunking mode).
=> Add Motorola Failsoft LC opcode $02

src/main/java/io/github/dsheirer/edac/CRC16.java
Closes #2125 
Motorola Talker Alias CRC calculation can throw an IndexOutOfBounds exception.
=> #2125 Motorola Talker Alias CRC index out of bounds error.

src/main/java/io/github/dsheirer/gui/playlist/alias/AliasItemEditor.java
Closes #2150 
Adds new menu item to playlist editor when creating an alias that allows the user to create an alias identifier for DMR AMBE audio tones.   
Note: this AMBE tone aliasing feature was already available for P25 Phase 2, but was not previously added to DMR, despite both DMR and P25 Phase 2 using the same AMBE audio codec.
=> #2150 Adds AMBE audio tone aliasing support to DMR.

src/main/java/io/github/dsheirer/bits/BinaryMessage.java, src/main/java/io/github/dsheirer/edac/bch/BCH.java, src/main/java/io/github/dsheirer/edac/bch/BCH_63.java, src/main/java/io/github/dsheirer/edac/bch/BCH_63_16_23_P25.java, src/main/java/io/github/dsheirer/edac/bch/GaloisFieldPrimitiveFinder.java, src/test/java/io/github/dsheirer/edac/bch/BCH_63_16_23_P25_Test.java
Closes #2162 
Implements a new general BCH decoder and a P25 BCH(63,16,23) decoder.
Note: this new code is not yet integrated into the P25 decoder and will be integrated in a subsequent update as part of the P25 DQPSK decoder redesign.
Current codebase continues to use the reed solomon decoder, even though that implementation is only reliable for detecting correct messages and doesn't correct bit errors.
=> #2162 APCO25 NID BCH Decoder Implementation.

src/main/java/io/github/dsheirer/module/decode/dmr/message/voice/VoiceMessage.java
Fixes an incorrect assignment to `frame_3[4]`, which should have been `frame_2[4]` based on the intended logic of the code.
The extracted byte should be assigned to `frame_2[4]` to correctly reconstruct the middle 72-bit voice frame. The assignment to `frame_3[4]` leaves `frame_2[4]` untouched from the initial `0` value , thus corrupting 8 bits of crucial FEC parity and voice parameters.
This fix should noticeably improve ECC performance and voice quality for DMR voice payloads.
No relevant issues found.
=>  DMR VoiceMessage: Fix incorrect frame assignment in DMR voice frame reconstruction

src/main/java/io/github/dsheirer/module/decode/p25/P25TrafficChannelManager.java
Available channel was added to P1 queue instead of P2 queue. Should close #2132.
=> Fix adding available channel to wrong queue

build.gradle
Closes #2171 Updates OpenJDK to version 23.0.2+9 release for the build system.
=> #2171 OpenJDK Version 23.0.2+9

src/main/java/io/github/dsheirer/audio/broadcast/rdioscanner/FormField.java, src/main/java/io/github/dsheirer/audio/broadcast/rdioscanner/RdioScannerBroadcaster.java
This adds the talker alias field to the rdio-scanner call payload. I know rdio-scanner is unmaintained now, but I have written my own clone of it (https://github.com/amigan/stillbox) that can use its API for call uploads, and now supports the field as it appears in this change. I'm not sure if this is something sdrtrunk is willing to add.
I can also confirm (since I am also using rdio-scanner) that this patch does not break existing functionality.
Thanks for your consideration.
=> Add talker alias field to rdio-scanner upload

src/main/java/io/github/dsheirer/gui/playlist/channel/ChannelEditor.java
Closes #2174 
Column was using a custom comparator for a row type of Channel, however JavaFX wants to compare the string display value.  Removed the custom comparator from the column to allow inherent string comparator to function correctly.
=> #2174 Playlist Editor Channels Tab - Frequency Column Sort Ordering

src/main/java/io/github/dsheirer/source/tuner/rtl/RTL2832TunerController.java
Resolves https://github.com/DSheirer/sdrtrunk/issues/1963
Check the I2CRepeater state before changing it.
=> RTL2832 Tuner USB 9 Pipe Error 

src/main/java/io/github/dsheirer/identifier/alias/DmrTalkerAliasIdentifier.java, src/main/java/io/github/dsheirer/identifier/alias/P25TalkerAliasIdentifier.java, src/main/java/io/github/dsheirer/identifier/alias/TalkerAliasManager.java, src/main/java/io/github/dsheirer/module/decode/dmr/DMRDecoderState.java
Closes #2202 
* DMR talker aliases now show in channel activity summary.  
* Added 'TA-' prefix to talker aliases (DMR & P25) to visually highlight what the value represents.
=> #2202 DMR Talker Aliases Now Show In Activity Summary & Add "TA-" As Talker Alias Prefix

src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/pdu/PDUSequence.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/pdu/ambtc/AMBTCMessage.java
Closes #2195 
Fix P25P1 NPE when accessing AMBTC network status message data blocks.
=> #2195 P25P1 NPE When AMBTC Network Status Message Null Data Block(s)

src/main/java/io/github/dsheirer/gui/power/ChannelPowerPanel.java
Closes #2193 
Removes "Log Settings" button from the channel view.  This is a debug button.
=> #2193 Removes "Log Settings" Button In Channel View

src/main/java/io/github/dsheirer/buffer/FloatAveragingBuffer.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelManager.java, src/main/java/io/github/dsheirer/dsp/psk/pll/FrequencyCorrectionSyncMonitor.java, src/main/java/io/github/dsheirer/dsp/squelch/PowerMonitor.java, src/main/java/io/github/dsheirer/gui/power/ChannelPowerPanel.java, src/main/java/io/github/dsheirer/module/carrier/CarrierOffsetProcessor.java, src/main/java/io/github/dsheirer/module/decode/DecoderFactory.java, src/main/java/io/github/dsheirer/module/decode/dmr/DMRDecoder.java, src/main/java/io/github/dsheirer/module/decode/dmr/DMRDecoderState.java, src/main/java/io/github/dsheirer/record/wave/ComplexSamplesWaveRecorder.java, src/main/java/io/github/dsheirer/sample/complex/ComplexSamples.java, src/main/java/io/github/dsheirer/source/SourceEvent.java, src/main/java/io/github/dsheirer/source/tuner/TunerController.java, src/main/java/io/github/dsheirer/source/tuner/airspy/AirspyTunerController.java, src/main/java/io/github/dsheirer/source/tuner/channel/TunerChannelSource.java, src/main/java/io/github/dsheirer/source/tuner/configuration/TunerConfigurationManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/FrequencyErrorCorrectionManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/TunerManager.java, src/main/java/io/github/dsheirer/source/tuner/rtl/RTL2832TunerController.java, src/main/java/io/github/dsheirer/source/tuner/ui/DiscoveredTunerModel.java, src/main/java/io/github/dsheirer/source/tuner/ui/TunerEditor.java, src/main/java/io/github/dsheirer/source/wave/ComplexWaveSource.java, src/main/java/io/github/dsheirer/spectrum/FrequencyOverlayPanel.java, src/main/java/io/github/dsheirer/spectrum/converter/ComplexDecibelConverter.java, src/main/java/io/github/dsheirer/spectrum/converter/DFTResultsConverter.java, src/main/java/io/github/dsheirer/util/Dispatcher.java
Closes #2212.
Introduces a carrier offset measurement processor to monitor a 12.5 kHz channel and provide estimated carrier offset measurements that allow the tuner's frequency error monitor to correct for the average error reported from each channel.  
The processor uses a coarse 128-point FFT to find the strongest peak within the channel center 12.5 kHz window and then uses a secondary fitting process to optimize the alignment with the signal at the -15 dB point to account for signal peaks resulting from phase/frequency modulation.  With this constrained window, the processor can only provide offset measurements of +/- 6.25 kHz of channel center.
Uses a 15 dB threshold where the signal must be at least 15 dB above the noise floor (SNR) before it will calculate and broadcast the carrier …
=> #2212 Carrier Offset Processor and Tuner PPM Auto-Correction

build.gradle
Fixes #2239 by adding the `jdk.incubator.vector` module, ignoring missing tags and malformed HTML.
=> Fixes #2239 by adding the `jdk.incubator.vector` module, ignoring missing tags and malformed HTML

build.gradle, src/main/resources/logback.xml
Closes #2250 
* Resolves Logback configuration issue
* Suppresses JDK24 warnings for Unsafe Memory access and Native Access related to JavaFX libraries
Note: suppressed JVM warnings will eventually be resolved by the JavaFX team ... I hope
=> #2250 Logback Configuration & Suppress JDK24 Warnings

src/main/java/io/github/dsheirer/dsp/filter/interpolator/LinearInterpolator.java
Closes 2252 
Resolves issue where DMR Decoder logs an error when the LinearInterpolator gets a mu value outside 0 to 1.0 range.
=> 2252 DMR Decoder - LinearInterpolator mu Error Value
