src/controller/channel/ChannelProcessingManager.java, src/module/ProcessingChain.java, src/record/RecorderManager.java
Resolves issue with loggers/recorders not being removed after stopping a channel processing chain.
=> #66 remove loggers and recorders between channel restarts

src/channel/metadata/Metadata.java, src/channel/metadata/MutableMetadata.java, src/controller/channel/ChannelProcessingManager.java, src/module/decode/DecoderFactory.java, src/module/demodulate/audio/DemodulatedAudioFilterModule.java
Resolves #135 issue where all audio was being recorded, regardless of the channel configuration recording setting and/or any 'Do Not Record' settings specified for the individual aliases.
=> 135 audio recording issue

src/channel/details/ChannelDetailPanel.java, src/channel/metadata/ChannelMetadataViewer.java, src/controller/channel/ChannelModel.java, src/controller/channel/ChannelProcessingManager.java
Channel Details Tab now displays: System, Site, Name and Activity Summary pane.
=> Resolves #123 - adds channel details tab 

src/module/decode/mpt1327/MPT1327DecoderEditor.java
Editor now sets modified flag on changes to traffic channel pool size or traffic channel timeout
=> Resolves #151 - mpt1327 decoder configuration persistence

src/channel/traffic/TrafficChannelManager.java, src/module/decode/DecoderFactory.java
=> Resolves #166 - removes traffic channel timeout from traffic channel manager

.idea/dictionaries/denny.xml, src/channel/details/ChannelDetailPanel.java, src/channel/state/DecoderState.java, src/module/decode/mpt1327/MPT1327DecoderState.java, src/module/decode/p25/P25DecoderState.java, src/module/decode/p25/message/tsbk/osp/control/IdentifierUpdateNonVUHF.java, src/module/decode/p25/message/tsbk/osp/control/IdentifierUpdateTDMA.java, src/module/decode/p25/message/tsbk/osp/control/IdentifierUpdateVUHF.java, src/module/decode/p25/message/tsbk/osp/control/SecondaryControlChannelBroadcast.java, src/module/decode/p25/message/tsbk/osp/data/SNDCPDataChannelAnnouncementExplicit.java
=> 188 p25 activity summary cleanup

src/audio/broadcast/icecast/IcecastTCPAudioBroadcaster.java
Resolves #193 - adds handling for MINA WriteTimeoutException error.  Resets connection when this occurs.
=> Resolves #193 - adds handling for MINA WriteTimeoutException

build/build.xml, src/alias/AliasModel.java
=> 206 alias list npe null list name

src/spectrum/OverlayPanel.java
Resolves #153 issue with spectral display rendering artifacts from cursor frequency readout when accessing menu items directly above the spectral display.
=> Resolves issue with spectral display rendering artifacts

src/playlist/PlaylistManager.java
Resolves #210 issue with the playlist saving all of the time due to audio streaming broadcast events.
=> Resolves issue with the playlist saving all of the time

src/audio/AudioManager.java
=> Resolves issue with audio playback allowing higher priority audio to preempt lower priority audio

src/channel/metadata/ChannelMetadataModel.java
Resolves #223 frequency display formatting.
=> Now Playing frequency display formatting

src/module/decode/p25/P25DecoderState.java, src/module/decode/p25/message/tsbk/osp/control/IdentifierUpdateTDMA.java
=> P25 Phase II TDMA frequency bands are now displayed in details summary

src/module/decode/p25/P25DecoderState.java
=> Resolves #229 - duplicate P25 TDMA call events.

src/module/decode/lj1200/LJ1200DecoderState.java
=> Resolves error on constructing a LoJack decoder state.

src/channel/state/ChannelState.java
Updates the StateMonitor runnable to catch Throwables while monitoring to set state to IDLE.
=> StateMonitor - try/catch for Throwables

src/audio/broadcast/icecast/IcecastTCPAudioBroadcaster.java, src/audio/broadcast/shoutcast/v1/ShoutcastV1AudioBroadcaster.java, src/audio/broadcast/shoutcast/v2/ShoutcastV2AudioBroadcaster.java
Resolves issue #260 where audio streaming was not re-connecting after a disconnect.
=> 260 - Icecast and Shoutcast streaming doesn't auto-reconnect

src/bits/BinaryMessage.java, src/bits/CorrectedBinaryMessage.java, src/edac/trellis/DMRNode.java, src/edac/trellis/Node.java, src/edac/trellis/Path.java, src/edac/trellis/ViterbiDecoder.java, src/edac/trellis/ViterbiDecoder_3_4_DMR.java, src/external/radioreference/RadioReferenceService.java
Resolves #269 - creates a generic Viterbi decoder and a Digital Mobile Radio (DMR) 3/4 Rate Viterbi decoder implementation for decoding Trellis Coded Modulation (TCM) encoded DMR Data packets.
=> 269 Viterbi decoder for DMR 3/4-rate packet messages

build/build.xml
Resolves #273 issue with dangling dash in application title version string.
=> 273 Application Title Version String

CHANGELOG, config/logback.xml, src/audio/broadcast/BroadcastState.java, src/audio/broadcast/icecast/IcecastTCPAudioBroadcaster.java, src/gui/SDRTrunk.java, src/util/MemoryUsageLogger.java
#283 Updates icecast tcp streaming to handle multiple error messages received from broadcastify when mount point is in use.
Adds memory usage logging to support memory usage related errors/issues.
=> 283 Broadcastify mount point in use error

src/edac/CRCLJ.java
#241 Resolves issue with error correction routine introducing invalid messages
=> 241 LJ1200 Error Correction

src/edac/CRCLJ.java
#241 Resolves issue with error correction routine introducing invalid messages
(cherry picked from commit 910a08f)
=> 241 LJ1200 Error Correction (v0.3.2 branch)

src/main/java/io/github/dsheirer/icon/Icon.java, src/main/java/io/github/dsheirer/icon/IconManager.java, src/main/java/io/github/dsheirer/icon/IconSelector.java
Resolves issues with NPE handling and loading external icons.
=> 308 IconManager throws NPE when loading external icons

sdr-trunk.ipr, src/main/java/io/github/dsheirer/source/SourceConfigurationEditor.java, src/main/java/io/github/dsheirer/source/SourceManager.java, src/main/java/io/github/dsheirer/source/config/SourceConfigTuner.java, src/main/java/io/github/dsheirer/source/tuner/TunerModel.java, src/main/java/io/github/dsheirer/source/tuner/TunerSourceEditor.java
Resolves #321 - allows user to specify a preferred tuner for each channel configuration to enable better control over how channels are sourced in a multi-tuner environment.
=> 321 channel preferred tuner

src/main/java/io/github/dsheirer/controller/channel/ChannelProcessingManager.java, src/main/java/io/github/dsheirer/gui/SDRTrunk.java, src/main/java/io/github/dsheirer/source/SourceManager.java, src/main/java/io/github/dsheirer/source/tuner/Tuner.java, src/main/java/io/github/dsheirer/source/tuner/TunerController.java, src/main/java/io/github/dsheirer/source/tuner/TunerManager.java, src/main/java/io/github/dsheirer/source/tuner/airspy/AirspyTunerController.java, src/main/java/io/github/dsheirer/source/tuner/hackrf/HackRFTuner.java, src/main/java/io/github/dsheirer/source/tuner/hackrf/HackRFTunerController.java, src/main/java/io/github/dsheirer/source/tuner/rtl/RTL2832Tuner.java, src/main/java/io/github/dsheirer/source/tuner/rtl/e4k/E4KTunerController.java, src/main/java/io/github/dsheirer/source/tuner/rtl/r820t/R820TTunerController.java, src/main/java/io/github/dsheirer/source/tuner/test/TestTunerController.java
Fully implements application shutdown procedure that is invoked when the user closes the the main gui window or invokes exit from the file menu.
=> 366 Application Shutdown Procedure

src/main/java/io/github/dsheirer/source/tuner/rtl/r820t/R820TTunerController.java
Resolves #320
Changes labels for the R820T Mixer gain settings.
=> 360 R820T Mixer Gain Labels

src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelSource.java
Resolves #390 
Adds null checking to output processor.
=> 390 PolyphaseChannelSource NPE

src/main/java/io/github/dsheirer/module/decode/p25/Trellis_3_4_Rate.java, src/main/java/io/github/dsheirer/source/tuner/channel/CICTunerChannelSource.java, src/main/java/io/github/dsheirer/source/tuner/channel/TunerChannelSource.java
Resolves issue with NPE in 3/4 rate decoder.
=> 377 NPE in P25 3/4 Rate Trellis Decoder

src/main/java/io/github/dsheirer/dsp/filter/channelizer/ComplexPolyphaseChannelizerM2.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelManager.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelSource.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/output/TwoChannelOutputProcessor.java, src/main/java/io/github/dsheirer/dsp/psk/pll/PLLGain.java, src/main/java/io/github/dsheirer/gui/channelizer/ChannelizerViewer2.java, src/main/java/io/github/dsheirer/module/decode/p25/DecodeConfigP25Phase1.java, src/main/java/io/github/dsheirer/source/tuner/Tuner.java, src/main/java/io/github/dsheirer/source/tuner/channel/CICTunerChannelSource.java, src/main/java/io/github/dsheirer/source/tuner/channel/TunerChannelSource.java, src/main/java/io/github/dsheirer/source/tuner/manager/PolyphaseChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/test/TestTunerController.java
Closes #429 
Updates all tuners to use the polyphase channelizer.  Updates the channelizer to use 25 kHz channels with 2x oversampling.  Updates PLL gains table.
=> 429 polyphase channelizer 25khz channel rate

src/main/java/io/github/dsheirer/audio/broadcast/BroadcastModel.java, src/main/java/io/github/dsheirer/audio/broadcast/StreamManager.java, src/main/java/io/github/dsheirer/gui/SDRTrunk.java, src/main/java/io/github/dsheirer/gui/preference/PreferenceEditorFactory.java, src/main/java/io/github/dsheirer/gui/preference/PreferenceEditorType.java, src/main/java/io/github/dsheirer/gui/preference/PreferencesEditor.java, src/main/java/io/github/dsheirer/gui/preference/directory/DirectoryPreferenceEditor.java, src/main/java/io/github/dsheirer/gui/preference/tuner/TunerPreferenceEditor.java, src/main/java/io/github/dsheirer/log/ApplicationLog.java, src/main/java/io/github/dsheirer/module/decode/event/DecodeEventPanel.java, src/main/java/io/github/dsheirer/module/decode/p25/P25DecoderState.java, src/main/java/io/github/dsheirer/module/decode/p25/P25MessageFramer2.java, src/main/java/io/github/dsheirer/module/decode/p25/P25TrafficChannelManager.java, src/main/java/io/github/dsheirer/module/decode/p25/message/P25Message.java, src/main/java/io/github/dsheirer/module/decode/p25/message/tsbk/Opcode.java, src/main/java/io/github/dsheirer/module/log/EventLogManager.java, src/main/java/io/github/dsheirer/playlist/PlaylistManager.java, src/main/java/io/github/dsheirer/preference/PreferenceType.java, src/main/java/io/github/dsheirer/preference/UserPreferences.java, src/main/java/io/github/dsheirer/preference/directory/DirectoryPreference.java, src/main/java/io/github/dsheirer/preference/playlist/PlaylistPreference.java, src/main/java/io/github/dsheirer/record/RecorderManager.java, src/main/resources/logback.xml
Resolves #444 
Adds 'Directories' editor to UserPreferences to allow user to change directories for each of the application data products: playlist, recording, screen capture, streaming and application and event logs.
=> 444 Expose Application Directories via User Preferences

src/main/java/io/github/dsheirer/module/decode/p25/P25DecoderState.java, src/main/java/io/github/dsheirer/module/decode/p25/message/pdu/packet/PacketMessage.java, src/main/java/io/github/dsheirer/source/tuner/usb/USBTransferProcessor.java
Resolves #459
Updates PacketMessage to expose to/from identifiers to include the LLID, and the to/from IPV4 addresses.
=> 459 Packet Message Identifiers

src/main/java/io/github/dsheirer/module/decode/p25/P25DecoderState.java, src/main/java/io/github/dsheirer/module/decode/p25/message/tsbk/Opcode.java, src/main/java/io/github/dsheirer/module/decode/p25/message/tsbk/TSBKMessageFactory.java, src/main/java/io/github/dsheirer/module/decode/p25/message/tsbk/motorola/osp/MotorolaDenyResponse.java, src/main/java/io/github/dsheirer/module/decode/p25/reference/DenyReason.java
Resolves #481 
Motorola TSBK Opcode 07 message support added.
=> 481 Motorola Opcode 07 Deny Response

build.gradle, src/main/java/io/github/dsheirer/gui/SDRTrunk.java, src/main/java/io/github/dsheirer/gui/control/MultipleFrequencyEditor.java, src/main/java/io/github/dsheirer/gui/instrument/PlaybackController.java
Resolves #479
Updates codebase to use jIconFont icons.
Removes Ikonli library.
=> 479 Use jIconFont for Icon Packages

src/main/java/io/github/dsheirer/record/wave/WaveMetadata.java
Resolves NPE thrown when audio recording metadata is null.
=> 480 Audio Recoriding Errors

src/main/java/io/github/dsheirer/module/decode/p25/message/pdu/packet/PacketMessage.java
=> 506 Remove Debug Logging - Packet Message

src/main/java/io/github/dsheirer/alias/AliasController.java, src/main/java/io/github/dsheirer/audio/broadcast/BroadcastPanel.java, src/main/java/io/github/dsheirer/audio/broadcast/BroadcastStatusPanel.java, src/main/java/io/github/dsheirer/channel/metadata/ChannelMetadataPanel.java, src/main/java/io/github/dsheirer/channel/metadata/NowPlayingPanel.java, src/main/java/io/github/dsheirer/controller/ControllerPanel.java, src/main/java/io/github/dsheirer/controller/channel/ChannelController.java, src/main/java/io/github/dsheirer/gui/SDRTrunk.java, src/main/java/io/github/dsheirer/module/decode/event/DecodeEventPanel.java, src/main/java/io/github/dsheirer/module/decode/event/MessageActivityPanel.java, src/main/java/io/github/dsheirer/preference/UserPreferences.java, src/main/java/io/github/dsheirer/preference/swing/JTableColumnWidthMonitor.java, src/main/java/io/github/dsheirer/preference/swing/SwingPreference.java, src/main/java/io/github/dsheirer/source/tuner/TunerViewPanel.java
Resolves #49, #107, #513 
Adds application layout persistence to user preferences for swing windows.  Adds main application location and size persistence.  Adds table column width persistence to all internal application tables.
=> 513 persist application layout across restarts

src/main/java/io/github/dsheirer/module/decode/p25/network/P25NetworkConfigurationMonitor.java
Resolves #525 NPE in P25 activity summary report.
=> 525 NPE in P25 Activity Summary Report

src/main/java/io/github/dsheirer/gui/SDRTrunk.java, src/main/java/io/github/dsheirer/spectrum/ShowTunerMenuItem.java, src/main/java/io/github/dsheirer/spectrum/SpectralDisplayPanel.java
Updates application title bar with currently displayed tuner.
Resolves #537
=> 537 Display Tuner Name in Application Title Bar

src/main/java/org/jdesktop/swingx/mapviewer/AbstractTileFactory.java
Java13 uses TLSv1.3 by default and that's not supported by the tile server.  For some reason, the default SSL factory attempts to handshake at TLSv1.3 even though the remote server reports that it doesn't support that version.
=> 570 Update Map Tile Factory to Use TLSv1.2 With OpenStreetMap

src/main/java/io/github/dsheirer/module/decode/p25/P25TrafficChannelManager.java, src/main/java/io/github/dsheirer/module/decode/p25/identifier/channel/P25Channel.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/P25P2DecoderState.java, src/main/java/io/github/dsheirer/source/config/SourceConfigTuner.java
Resolves #609 
P25 Phase 2 call events are not chaining together and are causing streaming events in the event panel.
=> #609 P25 Phase 2 Call Event Chaining

src/main/java/io/github/dsheirer/audio/broadcast/AudioBroadcaster.java, src/main/java/io/github/dsheirer/audio/broadcast/icecast/IcecastBroadcastMetadataUpdater.java, src/main/java/io/github/dsheirer/audio/broadcast/shoutcast/v2/ShoutcastV2AudioBroadcaster.java
Resolves #439 Icecast and Shoutcast metadata updating issue.  
Resolves issue with Icecast HTTP metadata incorrect XML tags.
Resolves issue with intermittent Broadcastify/Icecast Metadata updates.
=> 439 - Streaming Metadata Update Issues

src/main/java/io/github/dsheirer/message/StuffBitsMessage.java, src/main/java/io/github/dsheirer/module/decode/event/MessageActivityModel.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1MessageFramer.java
Creates StuffBitsMessage to account for processing tail bits in P25 control channel stream.
Resolves #608.
=> 608 Tail Bits Message Processing

src/main/java/io/github/dsheirer/audio/broadcast/StreamManager.java, src/main/java/io/github/dsheirer/audio/squelch/SquelchStateEvent.java, src/main/java/io/github/dsheirer/module/decode/p25/audio/P25P2AudioModule.java
Resolves #621 P25 Phase 2 Audio Streaming issue.
=> P25 Phase 2 Audio Streaming Doesn't Work

src/main/java/io/github/dsheirer/module/decode/p25/identifier/channel/P25Channel.java, src/main/java/io/github/dsheirer/module/decode/p25/identifier/channel/P25ExplicitChannel.java
Resolves #623 issue with P25 channels where uplink/downlink use different frequency bands.
=> #623 P25 Channel Frequency Error For Different Uplink/Downlink Band Identifiers

src/main/java/io/github/dsheirer/source/tuner/TunerViewPanel.java, src/main/java/io/github/dsheirer/source/tuner/recording/RecordingTunerConfigurationEditor.java, src/main/java/io/github/dsheirer/source/tuner/recording/RecordingTunerController.java
Resolves #625.  Updates handling of recording tuners.
=> #625 Recording Tuner Handling

src/main/java/io/github/dsheirer/record/RecorderManager.java
Resolves issue with audio recordings and from identifiers stemming from changes to the way radio IDs are handled.
Resolves #632
=> 632 Audio Recording From Identifier Values

src/main/java/io/github/dsheirer/audio/broadcast/icecast/IcecastBroadcastMetadataUpdater.java, src/main/java/io/github/dsheirer/audio/broadcast/shoutcast/v1/ShoutcastV1BroadcastMetadataUpdater.java, src/main/java/io/github/dsheirer/audio/broadcast/shoutcast/v2/ShoutcastV2AudioBroadcaster.java, src/main/java/io/github/dsheirer/channel/metadata/ChannelMetadataModel.java
#639 Updates all streaming metadata to include radio identifier value as the from value.
=> #639 Streaming Metadata FROM Radio Identifier Updates

src/main/java/io/github/dsheirer/alias/id/radio/RadioFormat.java, src/main/java/io/github/dsheirer/alias/id/talkgroup/TalkgroupFormat.java
#641 Updates P25 Talkgroup and Radio Id valid ranges to allow value of 0.
=> #641 P25 Talkgroup and Radio ID Allow Value of 0

src/main/java/io/github/dsheirer/icon/Icon.java
Resolves issue where user added icons were not displaying on windows OS.
Resolves #650
=> #650 Icon Manager User-Added Icons on Windows

src/main/java/io/github/dsheirer/gui/SDRTrunk.java, src/main/java/io/github/dsheirer/module/log/DecodeEventLogger.java, src/main/java/io/github/dsheirer/module/log/EventLogManager.java
puts TO talkgroup alias names in the event logs
=> alias in event log.diff

build.gradle
=> #667 Updates build to version 0.4.0 beta 5

src/main/java/io/github/dsheirer/audio/playback/AudioChannelPanel.java
=> #678 AudioChannelPanel Threading Issue.

src/main/java/io/github/dsheirer/module/log/DecodeEventLogger.java
Resolves #682 NPE when logging channel events with no alias list specified.
=> #682 Decode Event Logger - NPE

src/main/java/io/github/dsheirer/audio/AudioSegment.java
Resolves #676 Do Not Monitor feature not working.
=> #676 Do Not Monitor Not Working

.idea/misc.xml, src/main/java/io/github/dsheirer/module/decode/p25/audio/P25P2AudioModule.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/P25P2DecoderState.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/P25P2MessageFramer.java
Resolves #685.  Resolves several issues with P25 Phase 2 channel state and call handling.
=> #685 P25 Phase 2 Issues

build.gradle
Resolves #692.  Updates Java requirement to version 13 and JavaFX libraries to version 13.
=> #692 Upgrade To Java 13 and JavaFX 13

src/main/java/io/github/dsheirer/audio/playback/AudioPlaybackManager.java, src/main/java/io/github/dsheirer/preference/playback/PlaybackPreference.java, src/main/java/io/github/dsheirer/record/AudioRecordingManager.java
Resolves #694.  Addresses null pointer exception when no system audio devices are available.
=> #694 NPE When No System Audio Devices Available

src/main/java/io/github/dsheirer/preference/source/ChannelMultiFrequencyPreference.java
Resolves #699 Channel Multi-Frequency rotation delay user preference does not persist.
=> Resolves #699 Channel Multi-Frequency Rotation Delay User Preference 

src/main/java/io/github/dsheirer/audio/broadcast/AudioStreamingManager.java
Resolves #677 Streaming Audio Metadata is showing UNKNOWN/UNKNOWN
=> #677 Streaming Audio Metadata UNKNOWN/UNKNOWN

build.gradle
=> #705 Updates release version 0.4.0 beta 7

src/main/java/io/github/dsheirer/module/decode/mpt1327/MPT1327DecoderEditor.java
Resolves #580 
Updates MPT1327 channel editor to resolve issue with selecting and editing MPT1327 channel maps.
=> Resolves #580 channel map selection and editing

src/main/java/io/github/dsheirer/module/decode/p25/audio/P25P2AudioModule.java
Resolves #707 separate DTMF tones of the same value get merged together
=> #707 P25P2 AMBE DTMF Tone Metadata Merging

build.gradle
Resolves #713 Update Version 0.4.0 Beta 8
=> #713 Update Version 0.4.0 Beta 8

src/main/java/io/github/dsheirer/module/decode/p25/identifier/channel/P25Channel.java
Resolves issue with incorrect displayed P25 Phase 2  channel number in event logs.
=> Resolves #719 P25 Phase 2 display channel number

src/main/java/io/github/dsheirer/identifier/radio/RadioIdentifier.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/motorola/LCMotorolaTalkComplete.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/P25P2DecoderState.java
Resolves #721 Suppress RID values of 0.
=> #721 Suppress RID values of 0.

src/main/java/io/github/dsheirer/source/tuner/hackrf/HackRFTunerConfiguration.java, src/main/java/io/github/dsheirer/source/tuner/hackrf/HackRFTunerController.java, src/main/java/io/github/dsheirer/source/tuner/hackrf/HackRFTunerEditor.java
=> Updates HackRF Sample Rates

src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/tsbk/standard/osp/FrequencyBandUpdate.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/tsbk/standard/osp/FrequencyBandUpdateTDMA.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/message/mac/structure/FrequencyBandUpdate.java
Resolves issue with correct display of P25 uplink channel frequency values.
Resolves #770
=> #770 P25 Channel Uplink Frequency

src/main/java/io/github/dsheirer/controller/channel/ChannelProcessingManager.java, src/main/java/io/github/dsheirer/gui/playlist/channel/ChannelConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/ChannelEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/LTRConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/LTRNetConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/NBFMConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/P25P1ConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/P25P2ConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/radioreference/SiteEditor.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/P25P2DecoderHDQPSK.java
Resolves #775 
-Changes segmented button color style
-Removes P25 Phase 2 auto-detect scrambler settings feature
-Adds frequency column to channel editor
=> #775 Playlist Editor Cleanup

src/main/java/io/github/dsheirer/audio/broadcast/BroadcastConfiguration.java, src/main/java/io/github/dsheirer/audio/broadcast/broadcastify/BroadcastifyCallBroadcaster.java, src/main/java/io/github/dsheirer/audio/broadcast/broadcastify/BroadcastifyCallConfiguration.java, src/main/java/io/github/dsheirer/audio/broadcast/broadcastify/FormField.java, src/main/java/io/github/dsheirer/audio/broadcast/icecast/IcecastConfiguration.java, src/main/java/io/github/dsheirer/audio/broadcast/icecast/IcecastHTTPConfiguration.java, src/main/java/io/github/dsheirer/audio/broadcast/icecast/IcecastTCPConfiguration.java, src/main/java/io/github/dsheirer/audio/broadcast/shoutcast/v1/ShoutcastV1Configuration.java, src/main/java/io/github/dsheirer/audio/broadcast/shoutcast/v2/ShoutcastV2Configuration.java, src/main/java/io/github/dsheirer/gui/playlist/streaming/AbstractStreamEditor.java, src/main/java/io/github/dsheirer/gui/playlist/streaming/BroadcastifyCallEditor.java, src/main/java/io/github/dsheirer/gui/playlist/streaming/IcecastStreamEditor.java, src/main/java/io/github/dsheirer/gui/playlist/streaming/StreamingEditor.java
#786 Updates Broadcastify Calls api for new test endpoint and editor changes.  Updates Icecast and Shoutcast configurations to correctly show configuration validation status.
=> #786 Enable Broadcastify Calls Streaming Feature 

src/main/java/io/github/dsheirer/gui/SDRTrunk.java
Resolves #789 menu item is now sized appropriately.
=> #789 Screen Capture Menu Item

src/main/java/io/github/dsheirer/preference/javafx/JavaFxPreferences.java
Resolves #788 
Adds monitoring for maximized state of FX windows.
=> #788 FX Window Maximized State Preference Monitoring

src/main/java/io/github/dsheirer/alias/Alias.java
Resolves #799 NPE in Alias.hasBroadcastChannels() method
=> #799 NPE in Alias Method

src/main/java/io/github/dsheirer/gui/icon/IconManager.java, src/main/java/io/github/dsheirer/gui/playlist/alias/AliasConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/alias/AliasItemEditor.java, src/main/java/io/github/dsheirer/icon/Icon.java
Resolves #800 
Resolves issue with rendering of icons in playlist alias editor and slow loading of icons in dropdown combobox.  
Adds error checking to the icon manager to notify user when there is an issue with loading a custom icon in the ADD method.
=> #800 Alias Icon Editor and Slow Loading Icons

src/main/java/io/github/dsheirer/audio/broadcast/BroadcastConfiguration.java, src/main/java/io/github/dsheirer/audio/broadcast/ConfiguredBroadcast.java, src/main/java/io/github/dsheirer/audio/broadcast/shoutcast/v1/ShoutcastV1Configuration.java, src/main/java/io/github/dsheirer/audio/broadcast/shoutcast/v2/ShoutcastV2Configuration.java, src/main/java/io/github/dsheirer/channel/metadata/ChannelMetadataModel.java, src/main/java/io/github/dsheirer/channel/metadata/ChannelMetadataPanel.java, src/main/java/io/github/dsheirer/gui/playlist/alias/AliasItemEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/ChannelConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/radioreference/LoginDialog.java, src/main/java/io/github/dsheirer/gui/playlist/radioreference/SystemEditor.java, src/main/java/io/github/dsheirer/playlist/PlaylistManager.java
Resolves #797 
Resolves #801 
Code Review and Cleanup.  Resolves issue with Swing JTable column updates causing custom cell renderers to disappear.
=> #797 and #801 Code Review and Cleanup.

src/main/java/io/github/dsheirer/audio/broadcast/broadcastify/BroadcastifyCallBroadcaster.java
Resolves #808
Improves socket reset exceptions with broadcastify calls broadcaster.
=> #808 Improves Broadcastify Calls Socket Reset Exception Handling.

src/main/java/io/github/dsheirer/gui/SDRTrunk.java, src/main/java/io/github/dsheirer/preference/swing/SwingPreference.java
Resolves #804 
Tracks main application gui maximized state on shutdown and restores to maximized on restart.
=> #804 Swing Window Maximized Preference

src/main/java/io/github/dsheirer/gui/playlist/alias/AliasBulkEditor.java, src/main/java/io/github/dsheirer/gui/playlist/alias/AliasConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/alias/AliasItemEditor.java
Resolves #812
Adds new alias bulk edit feature.  When user selects more than one alias in the alias configuration editor, the single item editor is replaced with a new bulk (multi) alias editor.
=> #812 Alias Bulk Editor feature

src/main/java/io/github/dsheirer/audio/AbstractAudioModule.java, src/main/java/io/github/dsheirer/audio/AudioModule.java, src/main/java/io/github/dsheirer/channel/state/SingleChannelState.java, src/main/java/io/github/dsheirer/gui/playlist/channel/MPT1327ConfigurationEditor.java, src/main/java/io/github/dsheirer/module/decode/DecoderFactory.java, src/main/java/io/github/dsheirer/module/decode/config/DecodeConfiguration.java, src/main/java/io/github/dsheirer/module/decode/config/WithCallTimeout.java, src/main/java/io/github/dsheirer/module/decode/mpt1327/DecodeConfigMPT1327.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/DecodeConfigP25Phase1.java
Fixes #820 
Any requests, remarks & pointers highly welcome 🙂
=> MPT1327: Fix for call timeout setting not being honored

src/main/java/io/github/dsheirer/audio/AbstractAudioModule.java, src/main/java/io/github/dsheirer/audio/AudioModule.java, src/main/java/io/github/dsheirer/channel/state/ChangeChannelTimeoutEvent.java, src/main/java/io/github/dsheirer/channel/state/MultiChannelState.java, src/main/java/io/github/dsheirer/channel/state/SingleChannelState.java, src/main/java/io/github/dsheirer/channel/state/StateMachine.java, src/main/java/io/github/dsheirer/gui/playlist/channel/MPT1327ConfigurationEditor.java, src/main/java/io/github/dsheirer/module/decode/DecoderFactory.java, src/main/java/io/github/dsheirer/module/decode/config/WithCallTimeout.java, src/main/java/io/github/dsheirer/module/decode/mpt1327/DecodeConfigMPT1327.java, src/main/java/io/github/dsheirer/module/decode/mpt1327/MPT1327DecoderState.java
Resolves #817
Resovles issue with jittery audio playback and recording for MPT1327 channels.
=> #817 MPT1327 Jittery Audio Playback and Recording

src/main/java/io/github/dsheirer/module/decode/p25/P25TrafficChannelManager.java
Resolves #818 issue where a single P25 control channel was allocated multiple traffic channels for the same frequency.
Updates P25 traffic channel manager to track both Phase 1 and Phase 2 channels by frequency to ensure that a single control channel can't allocate more than 1 traffic channel for the same frequency.  Unifies phase 1 and 2 channel grant event management using shared set of timeslot 1 & 2 maps for channel events where phase 1 events will always be timeslot 0 and phase 2 events will use both the timeslot 0 and timeslot 1 event maps.
Note: this issue is different from the situation where multiple traffic channels are broadcasting the same audio content due to the content being transmitted on multiple sites, or to multiple talkgroups.  That issue is being tracked under #798
=> #818 P25 Duplicate Traffic Channel Allocations

src/main/java/io/github/dsheirer/audio/AbstractAudioModule.java, src/main/java/io/github/dsheirer/audio/AudioSegment.java, src/main/java/io/github/dsheirer/audio/DuplicateCallDetector.java, src/main/java/io/github/dsheirer/audio/broadcast/AudioStreamingManager.java, src/main/java/io/github/dsheirer/audio/playback/AudioOutput.java, src/main/java/io/github/dsheirer/audio/playback/AudioPlaybackManager.java, src/main/java/io/github/dsheirer/controller/channel/ChannelProcessingManager.java, src/main/java/io/github/dsheirer/gui/SDRTrunk.java, src/main/java/io/github/dsheirer/gui/preference/PreferenceEditorFactory.java, src/main/java/io/github/dsheirer/gui/preference/PreferenceEditorType.java, src/main/java/io/github/dsheirer/gui/preference/UserPreferencesEditor.java, src/main/java/io/github/dsheirer/gui/preference/duplicate/DuplicateCallPreferenceEditor.java, src/main/java/io/github/dsheirer/preference/PreferenceType.java, src/main/java/io/github/dsheirer/preference/UserPreferences.java, src/main/java/io/github/dsheirer/preference/duplicate/DuplicateCallDetectionPreference.java, src/main/java/io/github/dsheirer/record/AudioRecordingManager.java
Resolves #438 
Adds feature for duplicate call audio detection and suppression for playback, recording and streaming.
=> #438 Duplicate Call Audio Detection and Suppression

build.gradle, src/main/java/io/github/dsheirer/gui/JavaFxWindowManager.java, src/main/java/io/github/dsheirer/gui/playlist/PlaylistEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/AMConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/ChannelConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/ChannelConfigurationEditorFactory.java, src/main/java/io/github/dsheirer/gui/playlist/channel/ChannelEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/LTRConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/LTRNetConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/MPT1327ConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/NBFMConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/P25P1ConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/P25P2ConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/PassportConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/UnknownConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/preference/decoder/JmbeLibraryPreferenceEditor.java, src/main/java/io/github/dsheirer/gui/preference/directory/DirectoryPreferenceEditor.java, src/main/java/io/github/dsheirer/jmbe/JmbeCreator.java, src/main/java/io/github/dsheirer/jmbe/JmbeEditor.java, src/main/java/io/github/dsheirer/jmbe/JmbeEditorRequest.java, src/main/java/io/github/dsheirer/jmbe/github/Asset.java, src/main/java/io/github/dsheirer/jmbe/github/GitHub.java, src/main/java/io/github/dsheirer/jmbe/github/Release.java, src/main/java/io/github/dsheirer/jmbe/github/Version.java, src/main/java/io/github/dsheirer/preference/decoder/JmbeLibraryPreference.java, src/main/java/io/github/dsheirer/preference/directory/DirectoryPreference.java, src/main/java/io/github/dsheirer/util/FileUtil.java, src/main/java/io/github/dsheirer/util/OSType.java, src/main/java/io/github/dsheirer/util/ZipUtility.java
Resolves #829 
Integrates JMBE Creator with new user preferences editor for auto-downloading and compiling the JMBE library from within sdrtrunk.
=> #829 JMBE Library Creator Integration

src/main/java/io/github/dsheirer/gui/preference/decoder/JmbeLibraryPreferenceEditor.java
#845 File Not Found when setting initial directory on JMBE library select button.
=> #845 FileNotFound JMBE Library Preference Editor

src/main/java/io/github/dsheirer/controller/channel/Channel.java, src/main/java/io/github/dsheirer/gui/playlist/channel/ChannelEditor.java
Resolves #849 - frequency table column not updating after saving new channel configuration.
=> #849 Channel Editor Frequency Column Does Not Update After Save

src/main/java/io/github/dsheirer/alias/AliasModel.java
Resolves #851 issue with residual alias list names after playlist change.
=> #851 Alias List Names Not Cleared After Playlist Change

src/main/java/io/github/dsheirer/gui/playlist/alias/AliasBulkEditor.java
#856 Adds support for resetting alias color selection in the alias bulk editor.
=> #856 Alias Bulk Editor - Reset Color Selection

build.gradle
=> #862 Updates JavaFX libraries to use version 13.0.2

src/main/java/io/github/dsheirer/log/ApplicationLog.java
This should resolve Issue #827.  It outputs the build information generated by Gradle from the manifest file.
If sdtrunk is launched within IntelliJ, the manifest doesn't contain the `sdtrunk project` attribute value.  Building with Gradle _should_ result in the build info getting into the manifest, which will be read out on startup.
I say "should", because this is my first time working with Java since college (10 years ago), and first time working with Gradle.
=> Log build information on startup

src/main/java/io/github/dsheirer/record/AudioRecordingManager.java
#886 Resolves issue with audio recording when duplicate call detection is enabled.
=> 885 Audio Recording With Call Deduplication and Out-of-Memory Issues

src/main/java/io/github/dsheirer/audio/DuplicateCallDetector.java
Resolves #905.  Adds try/catch block to duplicate call detection processing block to ensure that any error generated during duplicate call processing doesn't kill the processing thread and cause a queue-backup memory leak.
=> #905 Enhanced Error Handling for Duplicate Call Detection

src/main/java/io/github/dsheirer/gui/playlist/alias/identifier/TalkgroupRangeEditor.java
Resolves #910 MPT-1327 talkgroup editor tooltip.
=> 910 MPT1327 Talkgroup Editor Tooltip

src/main/java/io/github/dsheirer/record/AudioRecordingManager.java
Resolves #908.
Adds AMBE tone information to audio recording file names.
=> #908 AMBE Tone Info In Audio Recording File Names.

build.gradle
Resolves #903 - updates rrapi library to resolve radio reference web service deserialization issue.
=> #903 Error Retrieving Radio Reference UCA System

.idea/misc.xml, build.gradle
#948 Updates build to 0.5.0 Alpha 4 and updates gradle script to embed JDK15 as the Java runtime.  Includes a new build target for ARM 64-bit LInux OS
=> #948 JDK15 and Update Build to Version 0.5.0 Alpha 4

src/main/java/io/github/dsheirer/module/HistoryModule.java, src/main/java/io/github/dsheirer/module/decode/event/DecodeEventPanel.java, src/main/java/io/github/dsheirer/module/decode/event/MessageActivityPanel.java
Resolves #950 
Resolves issue where message and event panels were aggregating across all selected now playing channels.
=> #950 Event and Message History Aggregations

src/main/java/io/github/dsheirer/controller/channel/ChannelProcessingManager.java
Resolves #952 
Resolves issue with concurrent access to processing chain map.
=> #952 Processing Chain Map - Make Concurrent

src/main/java/io/github/dsheirer/source/tuner/hackrf/HackRFTunerController.java
Resolves #986 issue with HackRF tuner not loading correctly.
=> #986 HackRF Tuner Not Loading 

src/main/java/io/github/dsheirer/dsp/filter/fir/real/RealFIRFilter2.java
Resolves #1021 
Updates FIR filter to use the Java 9 Math.fma() function for dot product oeprations.
=> #1021 Use Math.fma() For Dot Product Operations

src/main/java/io/github/dsheirer/dsp/filter/fir/real/RealFIRFilter2.java
#1021 Corrects previous implementation of dot-product filtering using Math.fma()
Resolves #1021
=> #1021 Filter Dot Product With Math.fma()

src/main/java/io/github/dsheirer/module/decode/dmr/message/data/packet/PacketSequenceAssembler.java
#1104 Resolves issue where all assembled DMR packet sequences are occuring only on timeslot 2
Resolves #1104
=> 1104 DMR Packet Sequences Only Occur on Timeslot 2

src/main/java/io/github/dsheirer/dsp/filter/FilterFactory.java, src/main/java/io/github/dsheirer/dsp/filter/Window.java
Resolves #1106 
Adds half-band filter create to filter factory
=> 1106 Half-Band Filter Create to Filter Factory

src/main/java/io/github/dsheirer/record/RecorderFactory.java
Resovles #1014
Adds AMBE voice frame recording support.
=> 1014 MBE Call Sequence Recorder for DMR AMBE Voice Frames

src/main/java/io/github/dsheirer/module/decode/dmr/DMRMessageFramer.java, src/main/java/io/github/dsheirer/module/decode/dmr/audio/DMRCallSequenceRecorder.java
Resolves #1110 
Updates DMR MBE frame recorder to correctly handle calls on separate timeslots and to fully capture identifiers associated with calls.
=> 1110 DMR MBE Frame Recorder - Identifiers

src/main/java/io/github/dsheirer/module/decode/dmr/DMRDecoder.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1Decoder.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/P25P2Decoder.java
Resolves #1130 - restores real time PPM measured frequency error broadcasts from DMR, P25P1 and P2 decoders.
=> #1130 Decoder PPM Measured Frequency Error Broadcasts

build.gradle, src/main/java/io/github/dsheirer/util/Dispatcher.java
#1150 resolves issue with inability to create HTTPS SSL connections.
Closes #1150
=> 1150 HTTPS SSL Connections Inop

.github/workflows/gradle.yml
Added Github Actions that is able to automate build testing under windows, linux, and macosx.
Closes #1101
=> Github Actions

src/main/java/io/github/dsheirer/module/decode/dmr/DMRDecoderState.java, src/main/java/io/github/dsheirer/module/decode/dmr/DMRSyncPattern.java, src/main/java/io/github/dsheirer/module/decode/dmr/audio/DMRAudioModule.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/DMRMessageFactory.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/voice/VoiceAMessage.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/voice/VoiceEMBMessage.java
Closes #1173 
Updates DMR decoder to support DCDM
=> #1173 DMR Decoder - DCDM Support

src/main/java/io/github/dsheirer/controller/channel/ChannelProcessingManager.java, src/main/java/io/github/dsheirer/gui/SDRTrunk.java
Patch from @ImagoTrigger to implement headless operation:
https://github.com/DSheirer/sdrtrunk/pull/1184/files/9e4d2adfa99e2676b77aed021b8f461f4f78fda1..c597d1967b57bf2e958d56b69c1aa967febe25a4
=> Implements Headless Operation

src/main/java/io/github/dsheirer/audio/broadcast/AudioStreamingBroadcaster.java, src/main/java/io/github/dsheirer/audio/convert/MP3Setting.java
Resolves issue with audio stream bit rate scheduling that was causing stream disconnects for data rate under flows.
Closes #1194
=> #1194 Audio Streaming Scheduler Causing Stream Disconnects (Underflow)

src/main/java/io/github/dsheirer/audio/broadcast/broadcastify/BroadcastifyCallBroadcaster.java
Runs a Broadcastify Calls test every 15 minutes to update the 'last seen' and avoid errant warnings about the node being offline.
=> Check in with Broadcastify Calls to stay online while otherwise idle

src/main/java/io/github/dsheirer/source/tuner/manager/TunerManager.java
1181 Adds logging for mac users to install libusb if sdrtrunk can't load library.
=> #1181 Adds Logging for Mac Users - LibUsb Not Installed

build.gradle, src/main/java/io/github/dsheirer/source/tuner/manager/TunerManager.java
#1181 Updates libusb osx aarch64 driver library and gradle build.
=> #1181 Update LibUsb OSX aarch64 Driver Library and Gradle Build

src/main/java/io/github/dsheirer/jmbe/JmbeCreator.java
Closes #1179.
Resolves issue with JMBE Creator running on OSX.
=> #1179 JMBE Creator Should Run On OSX

src/main/java/io/github/dsheirer/source/tuner/usb/USBTunerController.java
#1253 Updates USB tuner controller to handle LibUsb bug where on resubmitting a completed transfer LibUsb tells us that the transfer is already submitted.  This is happening on some Window systems.
=> #1253 USB Tuner Controller - USB Transfer Resubmit Anomaly Handling

src/main/java/io/github/dsheirer/module/log/EventLogger.java, src/main/resources/logback.xml
#1338 Updates logger to include date in log entries.  Removes info logger when creating channel log files.
=> #1338 Adds Date to Log Entries

build.gradle
Closes #1346 
Updates library to 15.1.9
=> #1346 Updates radio reference library to version 15.1.9

src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelManager.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelSource.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/SynthesisFilterManager.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/output/ChannelOutputProcessor.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/output/IPolyphaseChannelOutputProcessor.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/output/OneChannelOutputProcessor.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/output/TwoChannelOutputProcessor.java, src/main/java/io/github/dsheirer/sample/complex/ComplexSampleListenerModule.java, src/main/java/io/github/dsheirer/sample/complex/ComplexSamplesNativeBufferAdapter.java, src/main/java/io/github/dsheirer/util/Dispatcher.java
Closes #1353.
Resolves issue where polyphase channelizer would mis-tune channels after a period of time resulting in idle decoding channels.
=> #1353 Polyphase Channelizer Produces Idle Decode Channels After Period of Time

src/main/java/io/github/dsheirer/dsp/filter/channelizer/AbstractComplexPolyphaseChannelizer.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/ComplexPolyphaseChannelizerM2.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelSource.java
Closes #1360 
Resolves issue with Polyphase channelizer and decoded message timestamps for P25 and other protocols.
=> #1360 Polyphase Channelizer - Decoded Message Timestamps Show Epoch

src/main/java/io/github/dsheirer/source/tuner/usb/USBTunerController.java, src/main/java/io/github/dsheirer/util/Dispatcher.java
#1364 Enhancements to resolve issue with tuner shutdown hang on application shutdown.
=> #1364 Application Shutdown Tuner Shutdown Hang

src/main/java/io/github/dsheirer/audio/convert/MP3Header.java
=> Correctly identify padded MP3 frames

src/main/java/io/github/dsheirer/bits/BinaryMessage.java, src/main/java/io/github/dsheirer/module/decode/ip/ars/DeviceRegistration.java, src/main/java/io/github/dsheirer/module/decode/ip/ars/UserRegistration.java, src/main/java/io/github/dsheirer/module/decode/ip/ars/identifier/ARSDevice.java
Closes #1399 
Resolves device ID parsing issue for Motorola ARS Device Registration.  Changes ARSDevice base format from Integer to String.
=> #1399 ARS Device Identifier Parsing Issue

src/main/java/io/github/dsheirer/source/tuner/usb/USBTunerController.java
Closes #1419 
Reduces quantity of logging from USBTunerController for (temporary) failed transfer buffer resubmits.
Now only logs if/when the transfer buffer error holding queue size exceeds half of the available USB transfer buffers.
=> #1419 Reduce Logging of Failed USB Transfer Buffer Submissions

build.gradle
Closes #1426 
Adds JRE accessibility module to support assistive technologies.
=> #1426 Add JRE Accessibiity Support

src/main/java/io/github/dsheirer/edac/BerlekempMassey.java, src/main/java/io/github/dsheirer/edac/Checksum_5_DMR.java, src/main/java/io/github/dsheirer/edac/ReedSolomon_12_9_4_DMR.java, src/main/java/io/github/dsheirer/gui/dmr/DMRMessageViewer.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/lc/LCMessageFactory.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/lc/full/FLCAssembler.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/lc/full/FullLCMessage.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/lc/full/GroupVoiceChannelUser.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/lc/full/motorola/CapacityPlusGroupVoiceChannelUser.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/lc/full/motorola/CapacityPlusVoiceChannelUser.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/lc/full/motorola/CapacityPlusWideAreaVoiceChannelUser.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/type/CapacityPlusServiceOptions.java, src/main/java/io/github/dsheirer/record/binary/BinaryReader.java
Closes #1422 
Resolves issue where MotoTRBO IP Site Connect and Capacity Plus voice group user message not decoding Radio & Talkgroup IDs correctly.  Creates standalone application for viewing DMR messages from recordings.
=> #1422 DMR Radio IDs Incorrect on MotoTRBO Cap+ & IPSC

build.gradle
Closes #1449.  Updates version
=> #1449 Updates Version To 0.5.1 beta-2

build.gradle
Closes #1459 Updates gradle build to fix bug related to building releases for each OS
=> #1459 Gradle Doesn't Produce Correct OS Releases in Version 0.6.0

src/main/java/io/github/dsheirer/spectrum/ComplexDftProcessor.java
=> #1485 Sets Blackman-Harris 7 As Default FFT Window

src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelManager.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelSource.java, src/main/java/io/github/dsheirer/sample/Broadcaster.java, src/main/java/io/github/dsheirer/source/tuner/channel/StreamProcessorWithHeartbeat.java
#1487 Updates hot code classes to remove usage of reentrant locks for thread synchronization.
=> #1487 Thread Locking Impacting Processing Workload

src/main/java/io/github/dsheirer/controller/channel/ChannelAutoStartFrame.java, src/main/java/io/github/dsheirer/gui/SDRTrunk.java, src/main/java/io/github/dsheirer/gui/preference/PreferenceEditorFactory.java, src/main/java/io/github/dsheirer/gui/preference/PreferenceEditorType.java, src/main/java/io/github/dsheirer/gui/preference/UserPreferencesEditor.java, src/main/java/io/github/dsheirer/gui/preference/application/ApplicationPreferenceEditor.java, src/main/java/io/github/dsheirer/preference/PreferenceType.java, src/main/java/io/github/dsheirer/preference/UserPreferences.java, src/main/java/io/github/dsheirer/preference/application/ApplicationPreference.java
Closes #1500 
Makes Channel Auto-Start timeout a user-preference item to select in range 0-30 seconds.
=> #1500 Channel Auto-Start Timeout As a User Preference

src/main/java/io/github/dsheirer/source/tuner/TunerFactory.java, src/main/java/io/github/dsheirer/source/tuner/manager/TunerManager.java, src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/SDRplay.java
#1511 Resolves issue with SDRPlay library crashes application when linux service is in stopped state.
=> #1511 SDRPlay API Crashes App on Startup When Linux Service is Stopped

src/main/java/io/github/dsheirer/dsp/filter/channelizer/ComplexPolyphaseChannelizerM2.java
Closes #1519 
Adds null checking to channel results array to detect null on tuner shutdown.
=> #1519 Polyphase NPE On Tuner Shutdown

src/main/java/io/github/dsheirer/log/LoggingSuppressor.java, src/main/java/io/github/dsheirer/sample/Broadcaster.java
Closes #1529 
Adds logging suppression framework and updates Broadcaster to limit total logged error messages.
=> #1529 Broadcaster & Logging Suppression

src/main/java/io/github/dsheirer/gui/control/JFrequencyControl.java
Closes #1605 
Resolves issue where certain Linux users were unable to display the tuner editor panel due to an issue with the frequency control editor's usage of custom cursor.
=> #1605 Blank Tuner Editor Panel on Certain Linux Configurations

src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/tsbk/Opcode.java
Closes #1623 
Resolves issue with handling of unknown P25 trunking opcode in message filter set.
=> #1623 P25 Message Filter Set - Unknown Vendor Opcode

src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DecoderState.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/LinkControlOpcode.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/LinkControlWordFactory.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/motorola/LCMotorolaUnitGPS.java
#1666 Adds support for P25 Motorola unit self-reported GPS location parsing and plotting to map.
=> #1666 P25 Motorola Unit GPS Parsing & Plot to Map

build.gradle, src/main/java/io/github/dsheirer/identifier/patch/PatchGroup.java
Closes #1689 Increment Build 0.6.0 Beta 3 and Remove TG/RA prefixes for Harris patch groups.
=> #1689 Increment Build 0.6.0 Beta 3 and Remove TG/RA prefixes for Harris Patch Groups

src/main/java/io/github/dsheirer/gui/playlist/channel/ChannelEditor.java
Closes #1654 
Playlist channel editor sorts by frequency numerically (vs lexicographically)
=> #1654 Playlist Channel Editor Frequency Column Sort

src/main/java/io/github/dsheirer/identifier/patch/PatchGroup.java
#1704 Updates patch group format for compatibility.
=> #1704 Patch Group Formatting

src/main/java/io/github/dsheirer/alias/AliasFactory.java, src/main/java/io/github/dsheirer/gui/playlist/alias/AliasBulkEditor.java
Closes #967 
Updates bulk alias editor to support editing alias recordable status.
=> #967 Multi-Alias Editor Supports Changing Record Audio Status

src/main/java/io/github/dsheirer/gui/JavaFxWindowManager.java
Fixes #1619
You pointed me in enough of a direction.
Based on comments in https://github.com/AlmasB/FXGL/issues/764
=> Update JavaFxWindowManager.java for #1619

build.gradle
=> Fix osx nightly architectures

src/main/java/io/github/dsheirer/module/decode/p25/phase2/message/mac/structure/l3harris/L3HarrisTalkerAlias.java
#1783 P25P2 L3Harris Talker Alias - resolves issue with trying to parse too many bits.
=> #1783 P25P2 L3Harris Talker Alias Index Out Of Bounds Exception

src/main/java/io/github/dsheirer/module/decode/dmr/DmrCrcMaskManager.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/csbk/standard/announcement/AdjacentSiteInformation.java
Closes #1787 
Enhances DMR CSBK message processing by auto-detecting alternate CRC mask values employed by the DMR network.
=> #1787 Enhance DMR CSBK CRC Calculations - Auto-Detect Alternate CRC Mask Values

src/main/java/io/github/dsheirer/source/tuner/TunerFactory.java
Closes #1819 
SDRPlay RSP1B tuner is now constructed correctly.
=> #1819 SDRPlay RSP1B Tuner Detection

src/main/java/io/github/dsheirer/channel/metadata/ChannelMetadata.java, src/main/java/io/github/dsheirer/channel/metadata/ChannelMetadataModel.java, src/main/java/io/github/dsheirer/controller/channel/ChannelProcessingManager.java, src/main/java/io/github/dsheirer/dsp/filter/channelizer/PolyphaseChannelManager.java, src/main/java/io/github/dsheirer/gui/SDRTrunk.java, src/main/java/io/github/dsheirer/log/ApplicationLog.java, src/main/java/io/github/dsheirer/monitor/DiagnosticMonitor.java, src/main/java/io/github/dsheirer/source/tuner/manager/DiscoveredTuner.java, src/main/java/io/github/dsheirer/source/tuner/manager/HeterodyneChannelSourceManager.java, src/main/java/io/github/dsheirer/source/tuner/manager/TunerManager.java, src/main/java/io/github/dsheirer/source/tuner/ui/DiscoveredTunerModel.java, src/main/java/io/github/dsheirer/util/TimeStamp.java
Closes #1824
Adds new File menu item with two  report generation options:
* Thread Dump Report
* Processing Diagnostic Report
=> #1824 Diagnostic Report Generation

src/main/java/io/github/dsheirer/map/PlottableEntityHistory.java
Resovles issue with concurrent modification of plottable entity's history trail by creating a new array list.
Closes #1843
=> #1843 Map Entity Plotter Concurrent Modification Exception

src/main/java/io/github/dsheirer/source/tuner/TunerController.java, src/main/java/io/github/dsheirer/source/tuner/manager/PolyphaseChannelSourceManager.java
Updates polyphase tuner channel manager to avoid retuning for a new channel if all channels will continue to fit using the current center frequency
Closes #1845
=> #1845 Tuner Don't Change Frequency Unless Have To

src/main/java/io/github/dsheirer/gui/control/FrequencyTextField.java, src/main/java/io/github/dsheirer/source/tuner/ui/TunerEditor.java
Updates the FrequencyTextField to allow values as small as 1 Hertz.
Closes #1854
=> #1854 Tuner Min Frequency - Allow 1 Hertz Minimum

src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DecoderState.java, src/main/java/io/github/dsheirer/module/decode/p25/reference/VoiceServiceOptions.java
Closes #1905
Resolves P25 Phase 1 calls not consistently showing encrypted call status.
=> #1905 P25 Phase 1 Encrypted Call Status

src/main/java/io/github/dsheirer/gui/SDRTrunk.java, src/main/java/io/github/dsheirer/map/MapPanel.java, src/main/java/io/github/dsheirer/map/MapService.java, src/main/java/io/github/dsheirer/map/PlottableEntityHistory.java, src/main/java/io/github/dsheirer/map/PlottableEntityModel.java, src/main/java/io/github/dsheirer/map/PlottableEntityPainter.java, src/main/java/io/github/dsheirer/map/PlottableEntityRenderer.java, src/main/java/io/github/dsheirer/map/TimestampedGeoPosition.java, src/main/java/io/github/dsheirer/map/TrackGenerator.java, src/main/java/io/github/dsheirer/map/TrackHistoryModel.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/timeslot/LinearFeedbackShiftRegister.java, src/main/java/org/jdesktop/swingx/JXMapViewer.java, src/main/java/org/jdesktop/swingx/input/ZoomMouseWheelListenerCursor.java, src/main/java/org/jdesktop/swingx/mapviewer/GeoPosition.java
#1849 Adds:
* Track list
* Track location history list
* Zoom to selection
* History trail size
* Track following
* Delete, delete all, clear map, and replot all buttons
* Other smaller features.
=> #1849 Map Enhancements

src/main/java/io/github/dsheirer/service/radioreference/RadioReference.java
Closes #1781 Radio Reference API - adds logging to log results of test connection or user login attempt for troubleshooting RR enterprise user login issues.
=> #1781 Radio Reference API Login Enhanced Logging

src/main/java/io/github/dsheirer/source/tuner/sdrplay/api/Version.java
Closes # 1944 
Add support for SDRPlay API version 3.16
=> #1944 SDRPlay API version 3.16

src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DecoderState.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/pdu/PDUMessageFactory.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/pdu/ambtc/osp/AMBTCFrequencyBandUpdateTDMA.java
Closes #1981 
Adds P25 Phase1 support for foreign system IDEN_UPD_TDMA messages on control channel.
=> #1981 P25P1 Foreign System IDEN_UPD_TDMA Message Support

src/main/java/io/github/dsheirer/audio/playback/AudioOutput.java
Closes #1915 
Audio playback can randomly stop playing audio despite everything else appears to be normal.
=> #1915 (P25) Audio Stops Playing While Calls Continue To Process

.github/workflows/gradle.yml, .github/workflows/nightly.yml, .idea/misc.xml, build.gradle
Updates the JDK to use version 23 and updates the GitHub automated builds.
=> #1985 Update to JDK 23

src/main/java/io/github/dsheirer/preference/identifier/talkgroup/APCO25TalkgroupFormatter.java
Closes #2002 
P25 fully qualified identifiers now formatted correctly in now playing window.
=> #2002 P25 Fully Qualified Identifier Formatting For Not Fixed Width Preference

src/main/java/io/github/dsheirer/module/decode/p25/identifier/radio/APCO25FullyQualifiedRadioIdentifier.java, src/main/java/io/github/dsheirer/module/decode/p25/identifier/talkgroup/APCO25FullyQualifiedTalkgroupIdentifier.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DecoderState.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1MessageProcessor.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/ExtendedSourceLinkControlWord.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/IExtendedSourceMessage.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/LinkControlWordFactory.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/l3harris/HarrisTalkerAliasAssembler.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/standard/LCExtendedFunctionCommandExtended.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/standard/LCGroupVoiceChannelUser.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/standard/LCMessageUpdateExtended.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/standard/LCSourceIDExtension.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/standard/LCStatusUpdateExtended.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/standard/LCUnitToUnitVoiceChannelUserExtended.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/ldu/LDU1Message.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/tdu/TDULinkControlMessage.java, src/main/java/io/github/dsheirer/record/AudioRecordingManager.java, src/main/java/io/github/dsheirer/record/wave/AudioMetadataUtils.java
Closes #2004 P25P1 Link Control Extended Source messages now process through decoder state correctly and display in Now Playing.
=> #2004 P25P1 Link Control Extended Source Message Processing & ISSI Radio IDs

build.gradle
=> #2028 Windows ARM/aarch64 Operating System Support

src/main/java/io/github/dsheirer/alias/AliasModel.java, src/main/java/io/github/dsheirer/controller/channel/ChannelModel.java, src/main/java/io/github/dsheirer/gui/playlist/IAliasListRefreshListener.java, src/main/java/io/github/dsheirer/gui/playlist/alias/AliasConfigurationEditor.java, src/main/java/io/github/dsheirer/gui/playlist/channel/ChannelEditor.java, src/main/java/io/github/dsheirer/playlist/PlaylistManager.java
Closes #1060 
Adds Alias List delete and rename operations to playlist editor
Feature/changes implemented by @whelgeson
=> #1060 Alias List Delete and Rename Operations To Playlist Editor @whelgeson

src/main/java/io/github/dsheirer/module/log/DecodeEventLogger.java
Closes #1867.
Event logger logs the source radio ID and not the system transmitted radio alias.
=> #1867 Event Logger - Log Radio ID and Not Network Radio Alias

build.gradle
Closes #2084 Updates usb4java native library for windows aarch64
=> #2084 Updates usb4java native library for windows aarch64

src/main/java/io/github/dsheirer/map/PlottableEntityModel.java, src/main/java/io/github/dsheirer/module/decode/dmr/DMRDecoderState.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/packet/PacketSequenceMessageFactory.java, src/main/java/io/github/dsheirer/module/decode/dmr/message/data/packet/UDTShortMessageService.java
Closes #2122 
Removes extraneous logging from DMR processing.
=> #2122 DMR Remove Extraneous Logging

src/main/java/io/github/dsheirer/gui/viewer/DmrViewer.java, src/main/java/io/github/dsheirer/module/decode/dmr/DMRDecoderState.java
Closes #2138 
* DMR audio segments get chopped with every invalid link control message.  Updates decoder state to ignore any DMR message that is not valid.
* Removes the insert of Talkgroup 1 as a default value for conventional and direct mode channels.
=> #2138 DMR Audio Segments Chopped and Remove Talkgroup 1 As Default for DIRECT and CONVENTIONAL

src/main/java/io/github/dsheirer/record/AudioRecordingManager.java, src/main/java/io/github/dsheirer/util/StringUtils.java
Resubmitting this after renaming branches in my fork. Still getting the hang of working on opensource projects with github.
Reference #2128
=> Cleanup of recording paths #2128

src/main/java/io/github/dsheirer/module/decode/dmr/DMRDecoderState.java, src/main/java/io/github/dsheirer/module/decode/event/DecodeEventType.java, src/main/java/io/github/dsheirer/module/decode/ip/PacketMessageFactory.java, src/main/java/io/github/dsheirer/module/decode/ip/mototrbo/tms/TMSHeader.java, src/main/java/io/github/dsheirer/module/decode/ip/mototrbo/tms/TMSPacket.java
Closes #2175 
Adds support for DMR Text Message Service (TMS) events.
=> #2175 DMR Text Message Service (TMS) support.

src/main/java/io/github/dsheirer/audio/playback/AudioOutput.java
Closes #2157 
Resolves audio output getting 'stuck' when the thread is blocking on an attempt to write audio to the data line and that blocking call is not executing.  
Also, updates previous attempt at fixing a stalled data line by closing and reopening the line, without having to recreate the data line, which was causing related issues with the gain and muting behavior.
=> #2157 Audio Output Gets Stuck & Loss of Gain/Mute Control

src/main/java/io/github/dsheirer/gui/control/IntegerFormatter.java
Fixes #2185 
Two issues:
(1)documentation for change.getText() says it can be an empty string but never null.  (2)Need to allow for typing a minus sign before validating min/max.
=> #2185 Update IntegerFormatter.java for negative squelch value

src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1DecoderState.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/P25P1MessageProcessor.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/LinkControlOpcode.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/LinkControlWordFactory.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/l3harris/LCHarrisTalkerGPSBlock1.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/l3harris/LCHarrisTalkerGPSBlock2.java, src/main/java/io/github/dsheirer/module/decode/p25/phase1/message/lc/l3harris/LCHarrisTalkerGPSComplete.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/message/mac/structure/l3harris/L3HarrisGPS.java, src/main/java/io/github/dsheirer/module/decode/p25/phase2/message/mac/structure/l3harris/L3HarrisTalkerGpsLocation.java
Closes #2149 
* Adds P25 Phase 1 L3Harris Talker GPS support
=> #2149 P25P1 L3Harris Talker GPS Support

src/main/java/io/github/dsheirer/audio/broadcast/openmhz/FormField.java, src/main/java/io/github/dsheirer/audio/broadcast/openmhz/OpenMHzBroadcaster.java
Adds patched Talkgroup and Talker Alias information to the OpenMHz broadcaster.
=> #2207 OpenMHz Broadcast Enhancements

src/main/java/io/github/dsheirer/gui/playlist/manager/PlaylistManagerEditor.java
Closes #2209 
Double clicking on a playlist in the Playlist Manager is the same as selecting the playlist and then clicking the 'Select' button.
=> #2209 Playlist Manager double click selects the playlist

src/main/java/io/github/dsheirer/gui/squelch/NoiseSquelchView.java
#2265 NBFM noise squelch view saves user applied squelch changes and settings.
=> #2265 NBFM Noise Squelch View - Saving User-Applied Setting Changes
